### ISSUE TITLE
mongodb: transparently disable transactions while allowing use in code 

### ISSUE THREAD

**Issue by xenoterracide** [mikro-orm/mikro-orm#3992] opened 2023-01-31 15:30 UTC
This error makes total sense to me, something to do with using the in memory mongo server. However, it would be nice to be able to execute my code in spite of this so it works in the real environment

```
      previous MongoServerError: Transaction numbers are only allowed on a replica set member or mongos
      at Connection.onMessage (../../node_modules/@mikro-orm/mongodb/node_modules/mongodb/src/cmap/connection.ts:440:20)
      at MessageStream.<anonymous> (../../node_modules/@mikro-orm/mongodb/node_modules/mongodb/src/cmap/connection.ts:240:56)
      at processIncomingData (../../node_modules/@mikro-orm/mongodb/node_modules/mongodb/src/cmap/message_stream.ts:189:12)
      at MessageStream._write (../../node_modules/@mikro-orm/mongodb/node_modules/mongodb/src/cmap/message_stream.ts:70:5)
```

```ts
      return await this.em.transactional(async () => {
        const aggregate = await this.repository.findOneOrFail(
          storefrontId,
          productId,
        );
        aggregate.offerModificationRule(modificationRuleId, offerDuring);
        return await this.repository.save(aggregate);
      });
    });
```
I think I'd be ok if I could set `transactions: false` on the global config and then just having transaction code being called be a no-op (transaction wise).

**Comment by B4nan** [comment] 2023-01-31 15:47
FYI you can have a replica set with in-memory mongodb too.

https://github.com/nodkz/mongodb-memory-server#replica-set-start

Kind of a duplicate of #3747, we could support both if we design this properly.

**Closed** 2023-04-23 19:38 UTC
Labels: enhancement
