### ISSUE TITLE
"Error: Cannot find path to entity" when using @babel/preset-typescript [v4.0.0-rc4]

### ISSUE THREAD

**Issue by darkadept** [mikro-orm/mikro-orm#790] opened 2020-08-27 22:50 UTC
I'm not using Typescript to run my code. I'm using `@babel/preset-typescript`.

I have two packages.
  * My domain package has all of my entities in it and I'm compiling that into a single library index.js file using Webpack (Using @babel/preset-typescript as mentioned).
  * My server package uses `@babel/register` (in my development environment only) together with `@babel/preset-typescript`. I then import my domain package with the entities in it.

I'm using decorators (with `@babel/plugin-proposal-decorators`, plus tsconfig `experimentalDecorators: true`).
This is what my entity looks like in TS code, before webpack bundles it:

```
@Entity()
export class MyEntity {
  @PrimaryKey({type: 'uuid'})
  id = v4();
}
```

I actually stripped out the `MikroORM.init(...)` code, so I'm not even creating an instance of MikroORM, just using the decorators for now. The error happens inside the `@PrimaryKey` decorator.

I receive the following errors:

**Stack trace**
```
/home/user/dev/myproject/node_modules/@mikro-orm/core/utils/Utils.js:385
            throw new Error('Cannot find path to entity');
            ^

Error: Cannot find path to entity
    at Function.lookupPathFromDecorator (/home/user/dev/myproject/node_modules/@mikro-orm/core/utils/Utils.js:385:19)
    at Function.getMetadataFromDecorator (/home/user/dev/myproject/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:21:36)
    at /home/user/dev/myproject/node_modules/@mikro-orm/core/decorators/PrimaryKey.js:8:49
    at /home/user/dev/myproject/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:14:12
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (/home/user/dev/myproject/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:13:39)
    at Object../user/MyEntity.ts (/home/user/dev/myproject/packages/examples/domain/dist/index.js:1525:70)
    at __webpack_require__ (webpack://@myproject/example-domain/webpack/bootstrap:19:1)
    at Object../user/User.ts (webpack://@myproject/example-domain/user/User.ts:4:1)
    at __webpack_require__ (webpack://@myproject/example-domain/webpack/bootstrap:19:1)
```

**Additional context**
This setup used to work with Mikro-orm v3.x. I've traced the problem from `PrimaryKey.js` line 8, which calls `MetadataStorage.js` `getMetadataFromDecorator(target)` which calls `Utils.js` `lookupPathFromDecorator(stack)`.

The comments in Mikro-orm say: 
```
* Uses some dark magic to get source path to caller where decorator is used.
* Analyses stack trace of error created inside the function call.
```

And I see that it's using an Error().stack for information on the files. I console.logged that stack output and I get this:
```
[
  'Error: ',
  '    at Function.lookupPathFromDecorator (/home/user/dev/myproject/node_modules/@mikro-orm/core/utils/Utils.js:373:26)',
  '    at Function.getMetadataFromDecorator (/home/user/dev/myproject/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:21:36)',
  '    at /home/user/dev/myproject/node_modules/@mikro-orm/core/decorators/PrimaryKey.js:8:49',
  '    at /home/user/dev/myproject/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:14:12',
  '    at Array.reduce (<anonymous>)',
  '    at _applyDecoratedDescriptor (/home/user/dev/myproject/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:13:39)',
  '    at Object../user/Services.ts (/home/user/dev/myproject/packages/examples/domain/dist/index.js:1525:70)',
  '    at __webpack_require__ (webpack://@myproject/example-domain/webpack/bootstrap:19:1)',
  '    at Object../user/User.ts (webpack://@myproject/example-domain/user/User.ts:4:1)',
  '    at __webpack_require__ (webpack://@myproject/example-domain/webpack/bootstrap:19:1)'
]
```

The function is trying to find a line with `__decorate` or `_compile` but I don't have any of those.
This doesn't have anything to do with the MetadataProvider because it's not even getting to that point in my code.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.7.0 |
| typescript | 3.9.7 |
| mikro-orm | 4.0.0-rc4 |
| your-driver | "@mikro-orm/postgresql": "^4.0.0-rc.4", |

**Comment by B4nan** [comment] 2020-08-28 07:05
You probably also need `babel-plugin-transform-typescript-metadata`, at least that is what someone on slack said he used together with `@babel/plugin-proposal-decorators` to make it work. 

https://github.com/mikro-orm/mikro-orm/commit/fe6862a956f9746e3a8e23d38e3093093b79ad1a

**Comment by elendirx** [comment] 2020-08-28 20:00
Maybe this will help - I'm successfully using following plugins in `.babelrc` to make it work with Next.js:
```
"plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }]
  ]
```

**Comment by darkadept** [comment] 2020-08-28 20:23
I already have `emitDecoratorMetadata` but I didn't have `babel-plugin-transform-typescript-metadata`, so I added that.

That does work but only for entities that I bundle together with my app. The problem is still persisting when I import entities from a different package that was bundled using webpack (with the `babel-plugin-transform-typescript-metadata` babel plugin too). The problem seems to be in the stack trace that you are extracting the file name from.

---

## Step 1
This is the stack array from an entity that is bundled with my app. This is working fine now. It's working because it detects the `_compile` line. It extracts the line: `/home/user/dev/myproject/packages/examples/server/src/core/MyEnt.ts`.
```
[
  'Error: ',
  '    at Function.lookupPathFromDecorator (/home/user/dev/myproject/node_modules/@mikro-orm/core/utils/Utils.js:373:26)',
  '    at Function.getMetadataFromDecorator (/home/user/dev/myproject/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:23:36)',
  '    at /home/user/dev/myproject/node_modules/@mikro-orm/core/decorators/PrimaryKey.js:8:49',
  '    at /home/user/dev/myproject/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:14:12',
  '    at Array.reduce (<anonymous>)',
  '    at _applyDecoratedDescriptor (/home/user/dev/myproject/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:13:39)',
  '    at Object.<anonymous> (/home/user/dev/myproject/packages/examples/server/src/core/MyEnt.ts:32:66)',
  '    at Module._compile (internal/modules/cjs/loader.js:777:30)',
  '    at Module._compile (/home/user/dev/myproject/node_modules/pirates/lib/index.js:99:24)',
  '    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)'
]
```

---

## Step 2
This is the stack array from the entity that is imported from my bundled package. This give me the same error as I mentioned previously. There is no `_compile` line.
```
[
  'Error: ',
  '    at Function.lookupPathFromDecorator (/home/user/dev/myproj/node_modules/@mikro-orm/core/utils/Utils.js:373:26)',
  '    at Function.getMetadataFromDecorator (/home/user/dev/myproj/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:23:36)',
  '    at /home/user/dev/myproj/node_modules/@mikro-orm/core/decorators/PrimaryKey.js:8:49',
  '    at /home/user/dev/myproj/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:14:12',
  '    at Array.reduce (<anonymous>)',
  '    at _applyDecoratedDescriptor (/home/user/dev/myproj/node_modules/@babel/runtime/helpers/applyDecoratedDescriptor.js:13:39)',
  '    at Object../entities/MyPkgEnt.ts (/home/user/dev/myproj/packages/examples/domain/dist/index.js:1531:70)',
  '    at __webpack_require__ (webpack://@myproj/example-domain/webpack/bootstrap:19:1)',
  '    at Object../entities/index.ts (webpack://@myproj/example-domain/entities/index.ts:1:1)',
  '    at __webpack_require__ (webpack://@myproj/example-domain/webpack/bootstrap:19:1)'
]
```

I guess the corresponding line would be the one that has `MyPkgEnt.ts` in it, but since it's webpacked up the filename is `/home/user/dev/myproj/packages/examples/domain/dist/index.js` which would be where ALL my entities would be together.

---

## Step 3
I tried solving this by modifying `Util.js`. (I just did it directly in the `@mikro-orm` node_modules folder for testing). I added the following code after the `if` statement where it looks for `_compile`.
```
        if (line === -1) {
            line = stack.findIndex(line => line.includes('_applyDecoratedDescriptor'));
            if (line !== -1) {
                line++;
                compiled = true;
            }
        }
```

This works a bit more by grabbing the filename of my webpacked library: `/home/user/dev/myproj/packages/examples/domain/dist/index.js`.

---

## Step 4
Now I get the same error but from a different stack trace. This is for the same entity, as I only have a single entity right now.

```
[
  'Error: ',
  '    at Function.lookupPathFromDecorator (/home/user/dev/myproj/node_modules/@mikro-orm/core/utils/Utils.js:373:26)',
  '    at Function.getMetadataFromDecorator (/home/user/dev/myproj/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:23:36)',
  '    at /home/user/dev/myproj/node_modules/@mikro-orm/core/decorators/Entity.js:8:49',
  '    at Object../entities/MyPkgEnt.ts (/home/user/dev/myproj/packages/examples/domain/dist/index.js:1522:58)',
  '    at __webpack_require__ (webpack://@myproj/example-domain/webpack/bootstrap:19:1)',
  '    at Object../user/index.ts (webpack://@myproj/example-domain/entities/index.ts:1:1)',
  '    at __webpack_require__ (webpack://@myproj/example-domain/webpack/bootstrap:19:1)',
  '    at Object../core/entities.ts (webpack://@myproj/example-domain/core/entities.ts:1:1)',
  '    at __webpack_require__ (webpack://@myproj/example-domain/webpack/bootstrap:19:1)',
  '    at Object../core/createDomain.ts (webpack://@myproj/example-domain/core/createDomain.ts:10:1)'
]
```

This time I don't have a `_applyDecoratedDescriptor` line so it fails again. So I added the following bit to `Utils.js` again.

```
        if (line === -1) {
            line = stack.findIndex(line => line.includes('__webpack_require__'));
            if (line !== -1) {
                line--;
                compiled = true;
            }
        }
```

---

## Conclusion
Now my project is running again, but I don't think this is correct way to fix this issue.

You mentioned using a hash with the whole stack trace and I don't think this will work. The reason being that I get two different stack traces for the same entity. I experimented a bit with hashing the whole stack trace and it doesn't seem to work as it doesn't add meta information to the same entity.

Using this stack trace method may prevent me from compiling my entities in a separate package. Or at least with using a bundler like webpack. 

## Afterthought
I did one more experiment and just completely removed the need for the stack trace. I modified the `MetadataStorage.js` file.

```
static getMetadataFromDecorator(target) {
        // const path = utils_1.Utils.lookupPathFromDecorator();
        const path = target.name;
        const meta = MetadataStorage.getMetadata(target.name, path);
        Object.defineProperty(target, '__path', { value: path, writable: true });
        return meta;
    }
```

So instead of getting the path from the stack trace I just used the target name instead. The hashed value would be something like `MyEnt-<hash of MyEnt>`. I have no idea if this will break anything else though.

**Comment by elendirx** [comment] 2020-08-29 11:06
I'm getting the same error with RC4. The problem is that the `lookupPathFromDecorator()` method is based on the assumption that the application structure is somehow consistent. But Webpack or Babel can really mess it up. In my case, the `stack` variable (result of `stack = stack || new Error().stack!.split('\n')`) for my `User` entity looks like this:
```
'Error',
  '    at Function.lookupPathFromDecorator (C:\\projects\\cloudgarden\\cleanext\\node_modules\\@mikro-orm\\core\\utils\\Utils.js:373:26)',
  '    at Function.getMetadataFromDecorator (C:\\projects\\cloudgarden\\cleanext\\node_modules\\@mikro-orm\\core\\metadata\\MetadataStorage.js:21:36)',
  '    at C:\\projects\\cloudgarden\\cleanext\\node_modules\\@mikro-orm\\core\\decorators\\PrimaryKey.js:8:49',
  '    at C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:642:410',
  '    at Array.reduce (<anonymous>)',
  '    at _applyDecoratedDescriptor (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:642:367)',
  '    at Module../lib/security/User.ts (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:670:27)',
  '    at __webpack_require__ (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:23:31)',
  '    at Module../lib/security/IdentityManager.ts (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:558:63)',
  '    at __webpack_require__ (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:23:31)',
  '    at Module../lib/api/resources/ModelResource.ts (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:195:86)',
  '    at __webpack_require__ (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:23:31)',
  '    at Module../lib/di/inversify.config.ts (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:310:89)',
  '    at __webpack_require__ (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:23:31)',
  '    at Module../lib/api/ApiHandler.ts (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:106:81)',
  '    at __webpack_require__ (C:\\projects\\cloudgarden\\cleanext\\.next\\server\\pages\\api\\model.js:23:31)'
```
Not much info about the `User` entity, right?

If I understand, this dark magic was introduced because of HMR? It would be nice if it worked, but if it's too hard, maybe it could be developer's responsibility to attach correct entities on each reload. Maybe something like `orm.refreshMetadata()` that one can call manually?

**Comment by B4nan** [comment] 2020-08-29 11:46
Yeah its mainly for HMR where the entity can coexist twice for a short time. We could make it optional, so if it fails to find the path, we just use the entity name.

**Comment by darkadept** [comment] 2020-08-29 12:29
Would that still work? The first time around my stack trace had a `_compile` line but the second time it did not. Wouldn't that create two different hash keys?

I'm also curious about HMR on a server app? I thought HMR was a client-only thing? Or are people using entities on the client side too?

**Comment by elendirx** [comment] 2020-08-29 14:02
> Or are people using entities on the client side too

I'm using Next.js with API routes. It HRMs the backend too. I have to say it sucks big time. I'm still struggling to make any ORM work with it (failed with TypeORM, now experimenting with MikroORM).

**Comment by B4nan** [comment] 2020-08-29 16:10
You could always use EntitySchema instead of decorators to get around those things...

**Comment by darkadept** [comment] 2020-08-30 15:02
> You could always use EntitySchema instead of decorators to get around those things...

True. That is definitely an option, but I love the decorator approach! 😉

I've been digging deeper into the Mikro-orm source code and trying to figure out how things are working. 

Like you mentioned before, you essentially just use a hash to identify the source "thing". Entity, primarykey, property, etc... Which, I think, is how you collect info as these decorator functions are being called. I guess if you just use the `target.name` for the hash it would conflict if you have different entities with the same named primary key or property, etc?

The core problem would then be identifying each decorator target uniquely, no matter how or where it is in the code. I guess I'm a bit surprised that the decorators get called multiple times during program start, and with different stack traces. But I don't fully understand how that works.

### Idea 1
From the few examples in this thread it looks like we could use the `_applyDecoratedDescriptor` keyword to find the name of the file as well, but it would require a potentially different regexp depending on the stack.

I'm also going to experiment with source maps in my webpack project, and see if that changes the stack trace.

### Idea 2
Probably not a great idea, but could we provide or use the decorator options in some way to identify the item?

### Unknown
You also store the path in the metadata and I'm not sure where you are using this or how. I'm not sure if it's important or not.

I'd love to help out where I can with Mikro-orm. It's a fantastic library with awesome implementations of design patterns.

**Comment by B4nan** [comment] 2020-09-02 14:04
The main reason for this was to allow HMR (but regular TS watch mode was also causing issues when used with source map support), that caused one validation to be thrown - "Multiple property decorators used...", which is there to disallow using `@Property()` together with e.g. `@ManyToOne()` on the same property. 

Another reason is metadata caching, which is currently (in v4) used only with ts-morph (and there you need to compile via TS anyway). So nothing we need to care about here.

I removed the bit with `_compile` and made the `path` optional, this should allow the babel build to work (or at least pass this particular issue). I also improved the validation for multiple decorators, by throwing only if we try to override existing property with different type, so really when doing `@Property()` + `@ManyToOne()`, but not when we override `@Property()` with another `@Property()`. I also did allow merging of the metadata, so override is a wrong word here.

This will be part of `rc.5`, will ship it within an hour or so. Let me know if it helped, will be happy to reopen.

**Closed** 2020-09-02 14:04 UTC
Labels: bug
