### ISSUE TITLE
Typescript support for migration files

### ISSUE THREAD

**Issue by VBukharov** [mikro-orm/mikro-orm#705] opened 2020-08-04 17:15 UTC
Hi @B4nan

I'm trying to add mikro-orm to my project. I use it with an electron and react. 

And I have a few problems with migrations. I use them programmatically.
I created a [reproduction repository](https://github.com/VBukharov/mikroorm-example) so you can take a look. To start application use `npm run dev`.

Looks like these problems are about with webpack configuration, not mikro-orm itself

1. **Typescript syntax**
It works well when migration file was written in JS only. When I use typescript then an error occurs:
![ts-error](https://user-images.githubusercontent.com/13729061/89320565-4f26df80-d68a-11ea-963e-425282ecfed6.png)

This problem seems to be similar to [this one](https://github.com/mikro-orm/mikro-orm/issues/604).

[First commit](https://github.com/VBukharov/mikroorm-example/tree/af93059ff21cf7f3281f6dcbd6107b64052a61dc)  JS syntax is used for migration file. 

[Second commit](https://github.com/VBukharov/mikroorm-example/tree/83e899cacda8d677e245f6f0a315d4d529d8561e) TS syntax is used for migration file

2. **Webpack production mode**

I think this problem is about webpack configuration but I'm stuck with it.  I would really appreciate it if you could give me some advice on this)

When I use webpack with `production` mode it create application bundle in `dist` folder. When I execute `npm run start` script error occurs
![start-error](https://user-images.githubusercontent.com/13729061/89322455-e725c880-d68c-11ea-9091-a059094051b8.png)

There are no migration file at runtime and I have no idea how to add it(

**Versions**

| Dependency | Version |
| - | - |
| node | v12.18.2 |
| typescript | 3.9.7 |
| mikro-orm | 3.6.15 |
| your-driver | SQLite |

**Comment by B4nan** [comment] 2020-08-07 18:24
Migrations currently work only based on actual files in the migrations folder, which is not compatible with webpack. Not a webpack user myself, and I am not aware of any workaround currently. 

Check out this repo, it uses different way for migrations, which should be compatible with webpack:

https://github.com/thekevinbrown/express-ts-webpack-example-app

**Comment by B4nan** [comment] 2020-08-25 11:58
Latest RC of v4 supports passing list of migrations in the configuration, which is compatible with webpack:

https://mikro-orm.io/docs/next/migrations#importing-migrations-statically

**Comment by B4nan** [comment] 2020-09-03 12:07
So from what I understand, you would like to use TS migrations but execute them in the bundled code. That will never work, unless you register ts-node there, which is hardly what you want. So to your first question, use JS migrations - if you would like to have TS migrations, you will need to compile them first and adjust the `migrations.pattern` so it finds the JS files. Executing TS files is possible only with `ts-node`.

Btw I see you are using `sqlite3` v5 - that version is buggy when it comes to storing dates (it will store them as strings in some nonstandard format, while v4 will store them as timestamps - so its not even possible to upgrade on existing database). I would suggest to revert it to v4.

Your second error is pretty much connected to what you are trying -- if you want to bundle everything, you need to use the `migrationsList` feature, as noted above. The error is caused by calling `Migrator.up()`, that by default searches the migrations folder for new migrations. The folder is not there. If you use `migrationsList`, it will skip the folder lookup and prefer the list you provide there.

Will close this now, as tbh I am a bit tired of issues where I talk to myself only...

**Closed by B4nan** 2020-09-03 12:07 UTC
Labels: bug
