### ISSUE TITLE
Custom Many-to-Many attributes in pivot table

### ISSUE THREAD

**Issue by PhilippMolitor** [mikro-orm/mikro-orm#697] opened 2020-07-31 10:03 UTC
First of all, thanks for creating an ORM that is really concise and does not rely on strings in my queries in favor of the actual objects attributes, this is why I will continue to opt for this library.

I was wondering, because I think there are still a lot of examples missing in the docs, if you can create a custom model for the pivot table used by a many-to-many relationship (which is the nicest implementation i've seen so far with those `Collection<T>` types, thank you for that!).

Example:

`User <-- n:m --> Repository`
where the pivot table should not only hold the usual `n:m` relation, but also something like `readonly: boolean` and `createdOn: Date`.
This way I could get rid of extra Models I would have to join in a more complex way.

I'm thinking of something like a second generic parameter to collection which is another Entity class.
Example for the User model:

```typescript
@ManyToMany(() => Repository, repo => repository.owners, { owner: true })
workspaces: Collection<Repository, UserWorkspaceRelation> = new Collection<Workspace, UserWorkspaceRelation>(this)
```

```typescript
@Entity({ manyToManyPivot: true })
class UserWorkspaceRelation {
  // you should only define the non-key attributes here

  @Property()
  readonly: boolean = true

  @Property()
  createdOn: Date = new Date()
}
```

Are there any plans on something like this, or did I even overlook an implementation for my purposes in the docs?

**Comment by B4nan** [comment] 2020-07-31 10:13
Not supported and not planned. If you want to have additional props in the pivot table, it is no longer a pivot table (and the relation is no longer many to many). 

Duplicate of #333.

https://mikro-orm.io/docs/composite-keys#use-case-3-join-table-with-metadata

**Closed by B4nan** 2020-07-31 10:13 UTC
Labels: enhancement

**Comment by B4nan** [comment] 2020-07-31 11:04
The reason here is that there is no way to read and write such additional props, making it work on the schema level is easy, but without being able to work with such props, I don't see a reason why to allow this.

**Comment by simplenotezy** [comment] 2022-01-07 22:42
@B4nan It's something I am missing from MikroORM. If you look at Laravels Eloquent (which is by far the best ORM I have _ever_ worked with), you'll see they have "pivot" tables, and it's possible to define custom properties to this table: https://laravel.com/docs/8.x/eloquent-relationships#retrieving-intermediate-table-columns

TypeORM [have something similar](https://orkhan.gitbook.io/typeorm/docs/many-to-many-relations#many-to-many-relations-with-custom-properties) although not natively implemented.

Perhaps there is another way to implement this, without using custom attributes in the pivot table? I am curious for your input.

Let's say you have a User that is part of different Projects. Where would you store the date for when the user joined a specific project? Or if a user is "admin" of this specific project? Or if this user is marked as "inactive"? Etc.

btw - just for the record - i _love_ working with MikroORM; slowly learning it!
