### ISSUE TITLE
When Key is BigInt Type, unnecessary Update Query executed for related Entity

### ISSUE THREAD

**Issue by clwmem** [mikro-orm/mikro-orm#1038] opened 2020-11-05 08:43 UTC
**Describe the bug**
When Key is BigInt Type, unnecessary Update Query executed for related Entity
```ts
@Entity({ abstract: true })
abstract class BaseEntity {

  @PrimaryKey({ type: BigIntType })
  id!: string;

  @Property({
    type: 'Date',
    onCreate: () => new Date(),
    onUpdate: () => new Date(),
  })
  modifiedAt!: Date;

}

@Entity()
class User extends BaseEntity {

  constructor(name: string) {
    super();
    this.name = name;
  }

  @Property()
  name: string;

}

@Entity()
class Position extends BaseEntity {

  constructor(name: string) {
    super();
    this.name = name;
  }

  @Property()
  name: string;

}

@Entity()
class PositionBookmark extends BaseEntity {

  constructor(user: User, position: Position) {
    super();
    this.user = user;
    this.position = position;
  }

  @ManyToOne(() => User)
  user: User;

  @ManyToOne(() => Position)
  position: Position;

}

const user1 = new User('user1');
const position1 = new Position('position1');
await orm.em.persistAndFlush([user1, position1]);
const originUserModifiedAt = user1.modifiedAt;

const positionBookmark = new PositionBookmark(user1, position1);
await orm.em.persistAndFlush([positionBookmark])
```
```
[query] begin
[query] insert into `position` (`modified_at`, `name`) values (1604563982941, 'position1') [took 0 ms]
[query] insert into `user` (`modified_at`, `name`) values (1604563982952, 'user1') [took 0 ms]
[query] commit

[query] begin
[query] insert into `position_bookmark` (`modified_at`, `position_id`, `user_id`) values (1604563982956, '1', '1') [took 0 ms]
[query] update `position` set `id` = '1', `modified_at` = 1604563982957 where `id` = '1' [took 0 ms]
[query] update `user` set `id` = '1', `modified_at` = 1604563982961 where `id` = '1' [took 0 ms]
[query] commit
```
removeAndFlush Also unnecessary Update Query executed.
If the PrimaryKey is uuid, there was no problem, so it looks like some problem with the BigIntType.

**To Reproduce**
We have created a test code to reproduce it
https://github.com/mikro-orm/mikro-orm/commit/0669c34b277c93e1e87d2d8a190d4e3671b4c079

**Expected behavior**
Will be not Update Query executed for related Entity

**Versions**

| Dependency | Version |
| - | - |
| node | v12.18.3 |
| typescript | 3.9.7 |
| mikro-orm | 4.2.1 |
| your-driver | @mikro-orm/mysql@^4.2.1 |

**Comment by B4nan** [comment] 2020-11-05 10:30
This is actually caused by the `mysql2` connector under the hood (and apparently it's the same for `sqlite3`). It returns numeric value for the PK even when its defined as bigint (and therefore should be returned as string).

There is not much I can do, I could workaround that by casting the number to string, but that won't work for numbers higher than max int in JS. This should be fixed at the db connector level so we do not loose precision. 

Will need to verify if this is actually caused by knex or the db connector, but as the issue is same for different connectors...

**Comment by B4nan** [comment] 2020-11-05 10:49
So playing a bit with this, looks like it correctly returns the string number when the value is higher than the max int value, so it should be safe to just narrow the type to string at the ORM level.

**Closed** 2020-11-07 16:04 UTC
Labels: bug
