### ISSUE TITLE
Extraneous migrations created

### ISSUE THREAD

**Issue by evantrimboli** [mikro-orm/mikro-orm#1602] opened 2021-03-25 04:43 UTC
**Describe the bug**
Some constraints are dropped/re-created unnecessarily when creating a new migration. Sorry if this is a little long winded, I've cut down this test case from a larger set of code. Imports omitted for brevity.

**Setup**
```typescript
// src/model/base-item.ts
@Entity({ discriminatorColumn: 'discriminator', abstract: true })
export default abstract class BaseItem {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  id!: string

  @Index()
  @ManyToOne(() => Organization)
  organization!: Organization

  @ManyToOne()
  spec!: Spec
}
```
```typescript
// src/model/organization.ts
@Entity()
export default class Organization {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  id!: string

  @Property()
  name!: string
}
```
```typescript
// src/model/spec.ts
// Export for discovery
export { BarType, FooType }

@Entity()
export default class Spec {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  id!: string

  @Enum()
  fooType!: FooType

  @Enum()
  barType!: BarType
}
```
```typescript
// src/model/sub-item.ts
@Entity()
export default class SubItem extends BaseItem {
  @Property()
  customProp!: string
}
```
```typescript
// src/types.ts
export enum FooType {
  A = 'a',
  B = 'b',
}

export enum BarType {
  C = 'c',
}
```
**To Reproduce**
- `npx mikro-orm migration:create --initial`
- `npx mikro-orm migration:up`
- `npx mikro-orm migration:create`

**Expected behavior**
Nothing to do after running the second migration create.

**Actual behavior**
The second migration produces the following:
```typescript
this.addSql('alter table "spec" drop constraint if exists "spec_bar_type_check";');
this.addSql('alter table "spec" alter column "bar_type" type text using ("bar_type"::text);');
this.addSql('alter table "spec" add constraint "spec_bar_type_check" check ("bar_type" in (\'c\'));');

this.addSql('alter table "base_item" drop constraint if exists "base_item_discriminator_check";');
this.addSql('alter table "base_item" alter column "discriminator" type text using ("discriminator"::text);');
this.addSql('alter table "base_item" add constraint "base_item_discriminator_check" check ("discriminator" in (\'sub_item\'));');
```

**Additional context**
Using `TsMorphMetadataProvider` for metadata.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.0 |
| your-driver | postgresql - 4.5.0 |

**Comment by B4nan** [comment] 2021-03-25 07:45
Enum diffing should be tested pretty well, and it looks weird that apparently the enum items were extracted properly. What postgres version are you using? Is the initial migration creating the enums correctly?

Even weirder that your `fooType` is ok but `barType` is not - what are the actual differences in your code?

Would be much better if you provide something executable (and minimal, this looks too huge for such a small issue - you should be able to reproduce it with one entity and one enum), as this feels like you are omitting too much from the repro.

Ideally try to prepare a test case, similar to [those in the repo](https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues).

Btw here are some enum diffing tests in postgres, but they are not using `ts-morph` so it might be also caused by that. On the other hand in v4.5 I also changed the way ts-morph is getting enum item values (now via reflection instead of require). 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/SchemaGenerator.test.ts#L323

Would be good to verify if using `reflect-metadata` helps, as well as downgrade to v4.4.x helps, to narrow it down a bit.

**Comment by evantrimboli** [comment] 2021-03-25 11:18
Thanks for your reply, some notes:

- Postgres version: `"PostgreSQL 12.4, compiled by Visual C++ build 1914, 64-bit"`
- Explicitly specifying the type ` @Enum(() => FooType)` didn't appear to make any difference
- The same issue seemed to occur with `reflect-metadata`

I've created a test repo here: https://github.com/evantrimboli/mikro-orm-bug-1602

Below should contain all that is needed to trigger it
```
# change db details in src/mikr-orm-config.ts
npm install
npx mikro-orm migration:create --initial
npx mikro-orm migration:up
npx mikro-orm migration:create
```

There appears to be 2 issues, not sure if they are related, but both are constraint related:
1. The enum constraint
2. The discriminator constraint

**Comment by B4nan** [comment] 2021-03-25 11:23
Thanks a lot for the details. I am already in the middle of large rewrite of schema diffing, so not planning to change anything there in v4. I hope first dev versions will be available during a month, maybe sooner - new schema diffing will be the very first thing in there.

**Comment by evantrimboli** [comment] 2021-03-25 11:31
Interesting. Thanks again for your help, will wait for the next version and see how it works out.

**Comment by B4nan** [comment] 2021-04-04 21:29
So the problem is with single item enums in postgres, nothing ts-morph related. Will be addressed in v5.

**Comment by evantrimboli** [comment] 2021-04-06 11:50
Cool thanks for that.

Out of interest, do you think it would take much extra effort to incorporate the built-in enum types for postgres?

https://www.postgresql.org/docs/9.1/datatype-enum.html

**Comment by B4nan** [comment] 2021-04-06 11:58
It would be doable for sure, I believe knex does support them too, but the diffing would add some complexity I guess. 

I don't like the huge difference in how the rest of the drivers would behave (e.g. impossible to use string/numeric operators). Personally I would rather use regular entities instead of native pg enums, but I am not against supporting it. Open for PR :]

**Closed** 2021-04-16 21:12 UTC
Labels: bug
