### ISSUE TITLE
RequestContext always returns undefined

### ISSUE THREAD

**Issue by jsprw** [mikro-orm/mikro-orm#315] opened 2020-01-26 23:55 UTC
**Describe the bug**
The RequestContext always returns undefined after creating.

**Stack trace**
-

**To Reproduce**
1. Use beneath code as middleware:
```
const DatbaseContextLoader = async (_req: Request, _res, next) => {
        RequestContext.create((await Database.getConnection()).em, next);
        console.log("Req context",RequestContext.currentRequestContext());
    };
```
2. It always logs `Req context undefined`

**Expected behavior**
Return a forked em.

**Additional context**
Using ts-node.

https://github.com/mikro-orm/mikro-orm/blob/96d771a7799a901fa0594176d64247383ee38418/lib/utils/RequestContext.ts#L31

The active property is always undefined, even after just creating.

**Versions**

| Dependency | Version |
| - | - |
| node | v13.7.0 |
| typescript | v3.7.3 |
| mikro-orm | v3.0.1 |
| your-driver | myslql2 |

**Comment by B4nan** [comment] 2020-01-27 07:30
This is not how it works, the context is available only in the handler (next function).

**Comment by jsprw** [comment] 2020-01-27 10:00
I completely misunderstood how this works then..

However, no matter where I log it, it’s always undefined: in every handler that’s called with next as well (I placed a log in your code where it retrieved the RequestContext and there it always returns undefined as domain.active is never defined?). 

Also, isn’t domain deprecated in Node? https://nodejs.org/api/domain.html

**Comment by B4nan** [comment] 2020-01-27 10:26
> However, no matter where I log it, it’s always undefined:

You must be doing something wrong then, this is all covered in ORM's tests and it works in all node versions. 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/RequestContext.test.ts

E.g. this is being tested:

```typescript
test('create new context', async () => {
  expect(RequestContext.getEntityManager()).toBeUndefined();
  RequestContext.create(orm.em, () => {
    expect(RequestContext.currentRequestContext()).not.toBeUndefined();
  });
  expect(RequestContext.currentRequestContext()).toBeUndefined();
});
```

> I placed a log in your code where it retrieved the RequestContext and there it always returns undefined as domain.active is never defined?

That sounds like you did not even started the context (or you did but for a different handler than you are in). Try adding logs also to the place where the context is created, using breakpoints and debugger would also help you understand better what is the exact code path.

> Also, isn’t domain deprecated in Node? https://nodejs.org/api/domain.html

Yes it is, but without a proper replacement. There is `async_hooks` which is on the other hand experimental. First I used that, but it was leaking hard, making it unusable (I suspect it is caused by bluebird and other native api replacements). Afaik they won't remove domain api without making `async_hooks` really work without leaks. I was able to see those leaks also in a bare bone express example without the ORM being used, so it is really not problem with "my code", but rather something more fundamental (probably).

**Comment by jsprw** [comment] 2020-01-27 12:23
Correcting myself:

I currently have this scenario:
```
this.app
            .set("port", configService.get("port"))
            .use(cookieParser())
            .use(bodyParser.json())
            .use(useragent.express())
            .use(
                StateLoader({
                    additionalConfig: configuration.additionalConfig 
                }) // <-- returns an array of RequestHandlers which load configuration etc and executes RequestContext. The RequestContext is available in every handler within this StateLoader.
            )
            .use(configService.get("api_url"), await api) <-- however, here it is undefined again. The api object is a Express Router
```

In this scenario it works:

```
            .use(async (req, res, next) => RequestContext.create((await Database.getConnection()).em, next))
            .use((req, res, next) => console.log("dd", RequestContext.currentRequestContext(), next()))
```

But still undefined in the router. If I define it in the api-Router as first middleware (before all get and post), it does not work either in the routes.

Do you have any idea to make it work without setting it to the Request object?

**Comment by B4nan** [comment] 2020-01-27 12:32
Not at all, you will need to debug this yourself (I really suggest you use the node debugger instead of console.logging). 

The reason will be most probably what I already said - you are not really inside a handler that use registered in the `RequestContext.create()` call. Only there the context will be set. 

Btw what I do not understand is why you are creating the context inside another class/function or what it is (`StateLoader`). Second approach should be the one to go. 

```typescript
this.app
            .set("port", configService.get("port"))
            .use(cookieParser())
            .use(bodyParser.json())
            .use(useragent.express())
            .use(async (req, res, next) => RequestContext.create((await Database.getConnection()).em, next))
            .use(
                StateLoader({
                    additionalConfig: configuration.additionalConfig 
                }) // get rid of the `RequestContext.create` call you got somewhere inside of this
            )
            .use(configService.get("api_url"), await api)
```

Without a reproduction repository I can't help more...

**Comment by B4nan** [comment] 2020-01-27 12:41
Maybe one more question, you said:

```
.use(configService.get("api_url"), await api) <-- however, here it is undefined again. The api object is a Express Router
```

Does that mean it is undefined inside the `api` promise you are awaiting here? Because that does not happen inside the handler, that is in the "global" scope of the script, you can't get the request scope there.

**Comment by jsprw** [comment] 2020-01-27 23:14
> Does that mean it is undefined inside the api promise you are awaiting here? Because that does not happen inside the handler, that is in the "global" scope of the script, you can't get the request scope there.

The api promise returns a [router object](https://expressjs.com/en/api.html#router). Even if I define the RequestContext in there, it won't resolve either.

> Without a reproduction repository I can't help more...
I'm currently transforming the express example to a reproduction repo. It only works a function that is called by next right? Aren't all handlers triggered by a next call?

**Comment by B4nan** [comment] 2020-01-28 08:57
>  It only works a function that is called by next right? Aren't all handlers triggered by a next call?

Yes, only inside the next handler. And yes, all handlers should be like that, but without the reproduction it's hard to tell where the actual problem is. There must be something non-standard...

**Comment by B4nan** [comment] 2020-02-04 09:12
Closing this now as I am pretty sure that `RequestContext` is working as it should, but if you manage to get the reproduction repository, let me know, will be happy to look into that.

**Closed by B4nan** 2020-02-04 09:12 UTC
Labels: question

**Comment by jsprw** [comment] 2020-09-24 12:48
I found out (after lots of headaches) that zone.js (which is used by Angular SSR) was bugging the RequestContext (also in the async_hooks update).. If more people encounter this issue with zone.js, this how to create a forked em within a zone:

In any middleware that is executed befor database calls:
```
const em = orm.em.fork();
Zone.current
    .fork({
      name: "mikro-orm",
      properties: {
        id: em.id,
        em,
      },
      onHandleError: (
        delegate: ZoneDelegate,
        current: Zone,
        target: Zone,
        error: any
      ): boolean => {
        console.error("Database error:", error);
        return false;
      },
    })
    .run(() => {
      next();
    });
```

and then you can access the em within the zone with:
`Zone.current.get("em")`

This requires zone.js to be imported in the top most file (for me it's `server.ts`):
```
import "zone.js/dist/zone-node";
```

And to stop typescript complaining that types are missing (at least in `zone.js 0.11.1`, see https://github.com/angular/angular/pull/38585) add this to your `tsconfig.json`:
```
"types": ["node", "zone.js/zone.js"],
```
