### ISSUE TITLE
 Embeddable column names are converted incorrectly in order by

### ISSUE THREAD

**Issue by bozorgmehr96** [mikro-orm/mikro-orm#4841] opened 2023-10-18 08:52 UTC
**Describe the bug**
When using an embeddable's property in `order by`, the name of the property remains unchanged in the query, however it should be respect naming strategy.
```ts
@Embeddable()
class SomeMetrics {
  @Property()
  short!: number; // column name => 'short'

  @Property()
  veryLongColumnName!: number; // column name => 'very_long_column_name'
}

@Entity()
class Metrics {
  @OneToOne({ primary: true })
  asset!: Asset;

  @Embedded(() => SomeMetrics)
  something = new SomeMetrics();
}

@Entity()
class Asset {
  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @OneToOne(() => Metrics, (metrics) => metrics.asset)
  metrics!: Metrics;
}

em.find(
      Asset,
      {},
      { orderBy: { metrics: { something: { veryLongColumnName: QueryOrder.ASC } } } },
    );
```
In code above order by section of query will be:
```sql
order by "m1"."something_veryLongColumnName" asc
```

**Expected behavior**
It should be:
```sql
order by "m1"."something_very_long_column_name" asc
```

**Versions**

| Dependency | Version |
| - | - |
| node | v18.15.0 |
| typescript | Version 5.2.2 |
| mikro-orm | 5.8.7 |
| your-driver | postgres |

**Comment by B4nan** [comment] 2023-10-18 08:57
This is a duplicate of #2165, #4371 and probably a few others - embeddables do not support field names (nor naming strategies) in general and just use the property name.

I want to fix this in v6, as it is in fact heavily breaking.

**Closed by B4nan** 2023-10-18 08:57 UTC
