### ISSUE TITLE
Enumerable Arrays

### ISSUE THREAD

**Issue by duckies** [mikro-orm/mikro-orm#476] opened 2020-04-12 23:34 UTC
Hello, I am coming from TypeORM and quite enjoying this library so far, however I seem to have a bit of a snag around arrays of enumerables. This using PostgreSQL by the way.

**Is your feature request related to a problem? Please describe.**
A typical case with this for me is storing the static roles of users as string enumerables so it doesn't have to be converted in frontend code.

**Describe the solution you'd like**
I have tried a few variations of the following, however the schema generator does not seem to understand it. The `Role.Unverified`, as the desired default value, is seemingly referenced as a column in this instance.

```TypeScript
@Enum({ items: () => Role })
roles: Role[] = [Role.Unverified];
```
or
```TypeScript
 @Enum({ items: () => Role, default: [Role.Unverified] })
  roles: Role[] = [Role.Unverified];
```
> error: alter table "user" add column "roles" text check ("roles" in ('Admin', 'Educator', 'Volunteer', 'Verified', 'Unverified')) not null default Unverified; - column "unverified" does not exist

**Describe alternatives you've considered**
It also did not work with an enum of numbers, so I am assuming they are not supported currently.

**Comment by B4nan** [comment] 2020-04-12 23:38
Not natively supported, but should be possible via custom type: https://mikro-orm.io/docs/custom-types

**Comment by jackiboy** [comment] 2020-04-20 12:42
Here is an example of creating and retriving an array in postgres.

note `toJSON` is used instead of `convertToJSValue`. This ensures a JSON array is returned in your response.

```ts
export class RoleType extends Type {
  convertToDatabaseValue(value: any): string {
    if (value.length) {
      return `{${value.join(',')}}`;
    }
    throw ValidationError.invalidType(RoleType, value, 'JS');
  }

  toJSON(value: any) {
    return value;
  }

  getColumnType() {
    return 'text[]';
  }
}

```

**Comment by jshearer** [comment] 2020-10-14 19:09
@B4nan I see you mentioned this issue in that commit ☝️ , is it possible to define a column as `ArrayType` of an Enum, and have the postgres driver create the appropriate constraints?

**Comment by B4nan** [comment] 2020-10-15 06:38
Not really tbh, I am not sure how it could work. Enums are implemented via text fields in postgres (that's how knex is working), same as arrays, but I don't see a way to have "enum like check constraints" for arrays. Using native postgres enums might help, but that would mean a lot of additional work, and still the pg array type is basically just a concatenated string (so we would still have no type safety on the array value afaict). 

That is the reason why I did not close this just yet, but thinking about it now, I really do not see a clear way to support it, so I might just close it now... :]

You could implement your own custom type that would validate the items for you. We could have such type in the repository, prepared for anyone, that would work based on the enum metadata.

**Comment by duckies** [comment] 2020-10-15 07:09
I have had no complaints using the `ArrayType`, but before then it was fairly simple to make a custom type for native postgres enums.

I prefer to keep validation on a layer above the ORM, so strict enum checking has not been necessary. I haven't checked, but is it possible to access (or add access) to add custom metadata in the property decorator that could be checked in a custom type, or maybe a validation callback?

**Comment by B4nan** [comment] 2020-10-15 14:17
You could pass anything to the custom type via constructor and provide a configured instance of the type:

```ts
@Property({ type: new MyEnumType(['a', 'b', 'c']) })
enumArray: ('a' | 'b' | 'c')[]
```

**Closed** 2020-10-17 12:35 UTC
Labels: enhancement

**Comment by B4nan** [comment] 2020-10-17 12:37
v4.2 will allow this:

```ts
enum Role {
  User = 'user',
  Admin = 'admin',
}

@Enum({ items: () => Role, array: true, default: [Role.User] })
roles: Role[] = [Role.User];
```

And the items will be checked on flush automatically to mimic the db constraints.

**Comment by mehulchauhan** [comment] 2020-12-26 06:46
First of all many thanks for this library. I am new to Typescript, Node.JS eco-system. Any help will be really appreciated.

@B4nan : I just tried v4.2 allowed pattern to define role. and still facing error: 

```javascript
DriverException: create table `user` (`id` int unsigned not null auto_increment primary key, `created_at` datetime not null, `updated_at` datetime not null, `roles` text not null default 'PUBLIC') default character set utf8mb4 engine = InnoDB; - BLOB, TEXT, GEOMETRY or JSON column 'roles' can't have a default value
```

I am having MySQL DB and plain User.ts for defining entity. I am new to Typescript, can you please help me to resolve this error also I wanted to make roles column as varchar NOT text with defined length?

command I used for DB are:
```
npx mikro-orm migration:create
npx mikro-orm migration:up
```

**Comment by B4nan** [comment] 2020-12-27 15:25
You might want to try `defaultRaw` and wrap the value in parens, as apparently mysql 8 requires you to provide the default value for `TEXT` columns as expression (god knows why, it feels like very artificial limitation, and I'd expect this to be handled on knex's side).

https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-type-defaults-explicit

**Comment by linkthai** [comment] 2023-10-12 02:43
> v4.2 will allow this:
> 
> ```ts
> enum Role {
>   User = 'user',
>   Admin = 'admin',
> }
> 
> @Enum({ items: () => Role, array: true, default: [Role.User] })
> roles: Role[] = [Role.User];
> ```
> 
> And the items will be checked on flush automatically to mimic the db constraints.

For some reason, when I run migration with this, it always create a new migration file like
```ts
export class Migration20231012023939 extends Migration {

  async up(): Promise<void> {
    this.addSql('alter table "admin" alter column "permissions" type text[] using ("permissions"::text[]);');
  }

  async down(): Promise<void> {
    this.addSql('alter table "admin" alter column "permissions" type text[] using ("permissions"::text[]);');
  }

}
```

I add a bracket outside the enum and the migration command doesn't create a new file anymore
```
  @Enum({
    items: () => [AdminPermission],
    array: true,
    default: [],
  })
  permissions: AdminPermission[];
```

**Comment by B4nan** [comment] 2023-10-12 09:23
>     items: () => [AdminPermission],

This is indeed wrong, the callback is supposed to be returning the enum, not an array with the enum being its element. When it returns an array, it needs to return the items, e.g. `items: () => [AdminPermission.Foo, AdminPermission.Bar]`.

I can't help you without seeing a complete repro, hard to guess what you are doing and what your setup is.

Note that you can enable verbose logging to see why the schema comparator issues new migration - just add `MIKRO_ORM_VERBOSE=1` before the CLI call.

**Comment by linkthai** [comment] 2023-10-12 10:43
@B4nan thank for the answer, this is what I did
```ts
export enum AdminPermission {
  ROOT = 'ROOT', // the root admin, required to manage other admins
  ACCESS = 'ACCESS', // give access to the dashboard for other admin
}

@Entity()
export class Admin extends Base {
  @Enum({
    type: 'enumArray',
    items: () => AdminPermission,
    columnType: 'text',
    array: true,
    default: [],
  })
  permissions: AdminPermission[];
}
```
After I removed the `items: () => AdminPermission`, it actually stops creating new file in migration like expected. And it still checks for validation for the AdminPermission without that option, I don't know why but it seem like the items isn't needed? So it's solved for me.

These are the verbose logging if I add the `items: () => AdminPermission` in the @Enum decorator:
```bash 
[schema] 'enumItems' changed for column public.admin.permissions { column1: { name: 'permissions', type: 'text', mappedType: TextType {}, length: null, precision: null, scale: null, nullable: false, default: "'{}'", unsigned: false, autoincrement: false, comment: null, primary: false, unique: false, enumItems: [] }, column2: { name: 'permissions', type: 'text', mappedType: TextType {}, unsigned: false, autoincrement: false, primary: false, nullable: false, default: "'{}'", enumItems: [ 'ROOT', 'ACCESS' ] }}
[schema] column public.admin.permissions changed { changedProperties: Set(1) { 'enumItems' } }
[schema] 'enumItems' changed for column public.admin.permissions { column1: { name: 'permissions', type: 'text', mappedType: TextType {}, unsigned: false, autoincrement: false, primary: false, nullable: false, default: "'{}'", enumItems: [ 'ROOT', 'ACCESS' ] }, column2: { name: 'permissions', type: 'text', mappedType: TextType {}, length: null, precision: null, scale: null, nullable: false, default: "'{}'", unsigned: false, autoincrement: false, comment: null, primary: false, unique: false, enumItems: [] }}
[schema] column public.admin.permissions changed { changedProperties: Set(1) { 'enumItems' } }
```

**Comment by B4nan** [comment] 2023-10-12 11:10
Works fine for me, I need to see a complete reproduction.

**Comment by linkthai** [comment] 2023-10-12 16:08
@B4nan oh yeah, I should probably drop it, the original problem exist before I added `columnType`

Sorry, that's all there is to it, so I don't even know what else to reproduce. I'll give some more information that I think could help. I'm using Postgres and Fastify.

This is the migration command, I'm using this because the mikro-orm .bin bash file doesn't work well with my `src/...` path.
```"migration": "node --no-warnings -r tsconfig-paths/register --loader ./loader.js ./node_modules/@mikro-orm/cli/cli.js migration:create",```

I tried to remove the `permissions` field
```ts 
  async up(): Promise<void> {
    this.addSql('alter table "admin" drop column "permissions";');
  }
```

Then readd it and run migration
```ts
  async up(): Promise<void> {
    this.addSql('alter table "admin" add column "permissions" text[] not null default \'{}\';');
  }
```
then run migration again
```ts
async up(): Promise<void> {
    this.addSql('alter table "admin" alter column "permissions" type text[] using ("permissions"::text[]);');
  }
```
If this doesn't give you any hint, I'm probably gonna just remove the `items` field as I already did application level validation. Thanks for your time.

**Comment by B4nan** [comment] 2023-10-13 07:25
> Sorry, that's all there is to it, so I don't even know what else to reproduce.

You gave me one property definition, I want you to give me full entity definition (simplified, but complete), ORM config, tsconfig.json, package.json, that is a complete reproduction - something I can just pull and run myself. All those things matter, right now I don't even know what version are you using.

> If this doesn't give you any hint

What could give me some hint is the debug logs, the ones you provided before were generated with the wrong `columnType`, since they mention the `TextType`, while this should be `ArrayType` (or `EnumArrayType`) instead.

One thing that might confuse you here is the [snapshotting](https://mikro-orm.io/docs/next/migrations#snapshots), maybe try disabling that when you debug things.

**Comment by linkthai** [comment] 2023-10-15 11:21
@B4nan I made a Codesandbox with the files you need here: https://codesandbox.io/p/sandbox/hardcore-allen-qc869r

The loader.js I'm using to resolve the "src/modules/..." path since ts-node can't get it right. I'm running `pnpm run migration` to create new migration. I did turn off snapshot by default.

This is the verbose logging for the migrations with the correct `columnType`
```
[schema] 'enumItems' changed for column public.admin.permissions { column1: { name: 'permissions', type: 'text[]', mappedType: ArrayType { hydrate: [Function: hydrate] }, length: null, precision: null, scale: null, nullable: false, default: "'{}'", unsigned: false, autoincrement: false, comment: null, primary: false, unique: false, enumItems: [] }, column2: { name: 'permissions', type: 'text[]', mappedType: ArrayType { hydrate: [Function: hydrate] }, unsigned: false, autoincrement: false, primary: false, nullable: false, default: "'{}'", enumItems: [ 'ROOT', 'ACCESS' ] }}
[schema] column public.admin.permissions changed { changedProperties: Set(1) { 'enumItems' } }
[schema] 'enumItems' changed for column public.admin.permissions { column1: { name: 'permissions', type: 'text[]', mappedType: ArrayType { hydrate: [Function: hydrate] }, unsigned: false, autoincrement: false, primary: false, nullable: false, default: "'{}'", enumItems: [ 'ROOT', 'ACCESS' ] }, column2: { name: 'permissions', type: 'text[]', mappedType: ArrayType { hydrate: [Function: hydrate] }, length: null, precision: null, scale: null, nullable: false, default: "'{}'", unsigned: false, autoincrement: false, comment: null, primary: false, unique: false, enumItems: [] }}
[schema] column public.admin.permissions changed { changedProperties: Set(1) { 'enumItems' } }
````

**Comment by B4nan** [comment] 2023-10-15 11:54
Thanks, will try to look into that soon. It's weird I wasn't able to reproduce this in the tests, I can definitely see the problem in the code.

**Comment by linkthai** [comment] 2023-10-16 02:54
@B4nan I upgraded to the latest version and everything works fine now. Thank you so much.

There is one more question regarding the `type` in @Enum decoration, in your test and examples, you don't even have the property `type`, but if I omit it I get an error from `ReflectMetadataProvider` so I always have to included it. I have enabled the emitDecoratorMetadata in tsconfig.json.
```
Error: Please provide either 'type' or 'entity' attribute in Admin.permissions. If you are using decorators, ensure you have 'emitDecoratorMetadata' enabled in your tsconfig.json.
at ReflectMetadataProvider.initPropertyType (/.../node_modules/.pnpm/@mikro-orm+core@5.8.9_@mikro-orm+migrations@5.8.9_@mikro-orm+postgresql@5.8.9/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:14:19)
```

**Comment by B4nan** [comment] 2023-10-16 05:54
I believe that is about you working with TS in "non-standarad" ways, as `tsc` (and therefore `ts-node`) will emit the medatada here correctly.
