### ISSUE TITLE
Question: How to set primary key as an identity column, not serialize

### ISSUE THREAD

**Issue by Amir-Zouerami** [mikro-orm/mikro-orm#1922] opened 2021-06-11 07:40 UTC
I fiddled with the documentation for a bit and I could not find it. In PostgreSQL you use serial as the default type for primary keys:

```sql
create table t1 (id serial primary key);
```

but you can use the new identity columns in PostgreSQL:
```sql
create table t2 (id integer primary key generated always as identity);
```

I would like to set it as identity columns through the decorators in my entities file:

```ts
import { Property, Entity, PrimaryKey } from "@mikro-orm/core";

@Entity()
export class Post {
  @PrimaryKey()
  id!: number;

  @Property({ type: "date" })
  createdAt: Date = new Date();

  @Property({ onUpdate: () => new Date() })
  updatedAt: Date = new Date();

  @Property()
  title!: string;
}
```

the above example shows how to set createdAt column as `date` type but I do not know how to set the id column as identity column. Is there a way to do this?

**Comment by B4nan** [comment] 2021-06-18 19:48
Virtual columns are not supported as knex does not support them. What you can do is to use `columnType`, which will work for initial migration, but not for schema diffing. 

Closing as duplicate of #1904 that is about the schema diffing issue. For knex support of virtual columns, you can subscribe to https://github.com/knex/knex/issues/3987

**Closed by B4nan** 2021-06-18 19:48 UTC
