### ISSUE TITLE
Missing `EntityRepository.merge()` function

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#868] opened 2020-09-25 00:47 UTC
The v3 documentation mentions a `merge()` function at the entity repository level: https://mikro-orm.io/docs/3.6/repositories/#mergedata-entitydatat-t

The method only seems to exist at the EntityManager level in both v3 and v4.

Is there a way to merge from the repository?

**Comment by maphe** [comment] 2020-09-25 05:51
Also forgot to ask confirmation, still regarding the merge, would the following work?
```ts
const entity = new Entity();
entity.id = 123;
entityRepo.merge(entity);

// does this not trigger a db query?
const search = entityRepo.findOne({ id: 123 });

// does this work?
console.log(entity === search)
```
Assuming id is set as the primary key.

**Comment by B4nan** [comment] 2020-09-25 06:22
You should not use the entity constructor there. If this is about merging detached entity from cache, you should do `em.merge(Entity, data)`. Constructor should be used only when you expect insert query, so for new entities.

And nope, the method was never there, butt sure we can have it.

**Comment by maphe** [comment] 2020-09-25 06:43
Our use case is something like:
```ts
for (/* loop */) {
  let entity = entityRepo.findOne({ id: value });
  if (!entity) {
    entity = new Entity();
    entity.something = 'whatever';
  } else {
    exiting.something = 'some value';
  }
  repo.persist(entity);
}
await repo.flush();
```

The issue we're running into is that some loop iterations handle the same data, leading to:
- 1st loop doesn't find, instantiate entity and persist
- 2nd loop doesn't find, instantiate entity and persist
- flush triggers 2 inserts with the same values on a pair of columns that have unique index -> fails

One solution would be flush within the loop but that doesn't seem right, and I imagine will hit the performance.

The second idea was be to change the if clause to
```ts
  if (!entity) {
    entity = new Entity();
    entity.something = 'whatever';
    repo.merge(entity);
  }
```
So that in the second loop iteration, the `find` could retrieve the record that got persisted in the first even thought it didn't get flushed yet.

**Comment by B4nan** [comment] 2020-09-25 06:57
Not sure I understand the snippet (also it has some typos, like `existing` var never defined).

Do you understand what `merge` is doing? After you merge an entity, it will never produce a query, as its current state will be saved, so diffing won't find any changes. It is mainly for cached merging entities to the current context.

And what I said applies, you should not use entity ctor here, do `em.merge(Entity, data)` instead.

**Comment by maphe** [comment] 2020-09-25 07:15
(fixed the typo)

Hmm then I guess `merge` wouldn't work for that use case... cause we want the first entity to actually be inserted. Unless maybe combining merge with the ctor, something like
```ts
const ids = ['a', 'b', 'a', 'c']; // will process 'a' twice
for (const id of ids) {
  let entity = entityRepo.findOne({ id: id });
  if (!entity) {
    entity = new Entity(); // this is for the insert to happen during the flush
    entity.id = id;
    repo.merge(Entity, { id: id }); // this is for the EM to find a record when looping on the second `a`
  } else {
    // do something
  }
  repo.persist(entity);
}
await repo.flush();
```
but that's getting a bit convoluted. Might just have to flush within the loop...

**Comment by B4nan** [comment] 2020-09-25 07:56
Why don't you just make sure the ids are unique? Anyway, the code is wrong for sure, you don't want that `merge` there, for the reasons I stated above.

If you really need this, then instead of `merge`, you can do `em.getUnitOfWork().registerManaged(entity)`. That will add it to the identity map, but won't update the original entity data - so it will be still considered as new entity and will produce an insert. 

Maybe it would be cleaner (as this way you are using internal APIs) if you just store a set of processed ids, so you can check it from there. Or maybe a map so you can retrieve the instance by id. 

But let me say right here, that I won't be adding the uow getter to the repository, if you need this, inject the EM (or define custom method on repository, as there you have access to the EM). Repository is not EM, you can't expect all the methods to be there.

**Closed** 2020-09-25 14:31 UTC
Labels: enhancement

**Comment by B4nan** [comment] 2020-09-25 14:34
`repo.merge()` will be in next version, so closing this now. I would suggest something like this for your use case:

```ts
const ids = ['a', 'b', 'a', 'c']; // will process 'a' twice
const map = new Map();
for (const id of ids) {
  let entity = map.get(id) ?? await repo.findOne(id);
  if (!entity) {
    entity = new Entity();
    entity.id = id;
    map.set(id, entity);
    repo.persist(entity); // only new entities need to be persisted
  } else {
    // do something
  }
}
await repo.flush();
```

**Comment by epechuzal** [comment] 2020-09-25 16:47
@B4nan I understand using `merge()` might not be what we want, but can we ask for some advice? Our use case is something like:
```ts
class ExampleEntity {
  @ManyToOne({ entity: () => ParentEntityA, primary: true })
  parentA!: ParentEntityA;

  @ManyToOne({ entity: () => ParentEntityB, primary: true })
  parentB!: ParentEntityB;

  [primaryKeyType]: [number, number] // primary key type is type of `id` column in each parent entity
}
```

Now we have some loop which is supposed to create `ExampleEntity` if they do not already exist in database, e.g.
```ts
for (const entry of array) {
  // entry.parentA is instance of ParentEntityA, entry.parentB is instance of ParentEntityB
  let entity = this.repo.findOne([parentA.id, parentB.id])
  
  if (!entity) {
   let entity = new ExampleEntity()
   // add desired entity attributes
   this.repo.persistLater(entity)
  } else {
   // update desired entity attributes
   this.repo.persistLater(entity)
  }
}
// at end of array we flush everything to have a single transaction
this.repo.flush()
```

The issue is the check for existing entity. If entity exists in the DB then `this.repo.findOne([parentA.id, parentB.id])` will catch it, and we will not get any issue.

However, if the entity only exists as something to `persistLater()`, then `this.repo.findOne([parentA.id, parentB.id])` will NOT find it, and when we `flush()` we get duplicate key error. 

We thought using `merge()` could help here because then the object would be present in the identity map, but based on your reply I am thinking maybe we are missing something. What do you think?

**Comment by B4nan** [comment] 2020-09-25 17:21
Well, everything is already said here I guess. Dont use merge, and either use a map as I described above, or the uow.registerManaged() method. 

And again, there is no need to persist managed entities (those loaded from database).

**Comment by epechuzal** [comment] 2020-09-25 18:45
Got it - thank you for your help :)
