### ISSUE TITLE
docs: How to consume serialized Entity interface

### ISSUE THREAD

**Issue by datrinh** [mikro-orm/mikro-orm#2674] opened 2022-01-26 10:34 UTC
What is the best way to consume existing entity class interfaces in mikro-orm?

## Example

```js
@Entity()
export class FlowEntity extends BaseEntity {
    @Property()
    name: string;

    @OneToMany({ entity: () => NodeEntity, mappedBy: 'flow', orphanRemoval: true })
    nodes = new Collection<NodeEntity>(this);

    @OneToMany({ entity: () => OptionEntity, mappedBy: 'flow', orphanRemoval: true })
    options = new Collection<OptionEntity>(this);

    @OneToMany({ entity: () => LinkEntity, mappedBy: 'flow', orphanRemoval: true })
    links = new Collection<LinkEntity>(this);

    constructor(name: string) {
        super();
        this.name = name;
    }
}
```

When I import `FlowEntity` in a frontend app, it works just fine for the most part. The tricky part is that `nodes` and the other attributes aren't arrays, but `Collections`, which causes type mismatches within the compiler. The data itself is serialized and hence a simple serialized JS object with arrays instead of collections. How can I "convert" those collections to arrays? I hope manually declaring and maintaining the interfaces isn't the only option.

On the consuming side it looks something like this:
![image](https://user-images.githubusercontent.com/3518618/151147984-58ab1b57-2439-45ab-98a0-e4b719338a3f.png)

**Comment by B4nan** [comment] 2022-01-26 10:45
This is not really supported, I guess we can call it a duplicate of #1972. That issue is marked as help wanted - if you want to see it happen, its best if you try to contribute. I never needed such use case myself, and have no idea how others are setting up their project to accomodate it. 

I am not really sure what people expect from using entities on frontend - they should contain backend code, and they can get serialized to some other shape than how the entity looks like. There are no `Collection` wrappers on frontend, just arrays. Even if we had a browser shim, we still have different shape than on backend.

Worth noting that `Collection` is array like structure, it does have `length` getter, index access and implements iterator. So as long as you want to read from it, it acts just like an array even on backend.

You might be able to use `EntityDTO` type, in the end that's what you actually get from methods like `toJSON()` - it's not the entity type itself. `EntityDTO` maps `Collection`s to arrays and unwraps `Reference`s. Something like this maybe:

```ts
import { EntityDTO } from '@mikro-orm/core';
import type { FlowEntityBackend } from '...';

export type FlowEntity = EntityDTO<FlowEntityBackend>;
```

**Closed by B4nan** 2022-01-26 10:45 UTC
Labels: documentation

**Comment by datrinh** [comment] 2022-01-26 11:51
Thanks for the pointers. I can't import `EntityDTO`. Is it available on v4.5?

**Comment by B4nan** [comment] 2022-01-26 11:57
Nope, but you can copy its code and use that if you dont want to upgrade.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/typings.ts#L174-L187

**Comment by datrinh** [comment] 2022-01-26 12:10
A little off topic, but how production ready would you deem v5? 😅

**Comment by B4nan** [comment] 2022-01-26 12:21
RC is out, I dont plan more major changes. If you ask me, v5 is in better shape than v4 already.

**Comment by datrinh** [comment] 2022-01-27 12:08
@B4nan How would you rate the projected ease of migration from v4 to v5?

**Comment by B4nan** [comment] 2022-01-27 12:25
That obviously depend on how complex your project is and how much "weird stuff" you do :] BCs are mainly about strict types and method signatures (options parameters are now the only way). Rest is rather internal.

https://mikro-orm.io/docs/next/upgrading-v4-to-v5/
