### ISSUE TITLE
Add limit and offset to Collection init

### ISSUE THREAD

**Issue by njeirath** [mikro-orm/mikro-orm#1068] opened 2020-11-10 21:38 UTC
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to specify a limit and offset to support paginating through large collections.

**Describe the solution you'd like**
Something like the following would be nice: 
```
const user = await em.findOneOrFail(User, {id: userId})
user.comments.init({offset: 0, limit: 50})
```

**Describe alternatives you've considered**
The only alternative I've considered so far would be to write up my own custom SQL query to achieve this but definitely open to other ways to accomplish this.

**Comment by B4nan** [comment] 2020-11-10 21:39
Duplicate of #334

**Closed by B4nan** 2020-11-10 21:39 UTC
Labels: enhancement
