### ISSUE TITLE
Remove and Add from collection in same transaction with composite PK

### ISSUE THREAD

**Issue by maphe** [mikro-orm/mikro-orm#1914] opened 2021-06-08 23:11 UTC
**Describe the bug**
I'm running into different kinds of errors trying to both remove from and add to a OneToMany collection that contains objects with composite PKs. I can't tell for sure if it's the composite PK that breaks it, but it's not working regardless.

**To Reproduce**
https://gist.github.com/maphe/4a894b5b2a115de73781c6d0d6b51752

**Expected behavior**
First block should allow removing a single element then adding a single element in a single flush, instead I'm getting:
```
NotNullConstraintViolationException: update `site_category` set `site_id` = NULL - SQLITE_CONSTRAINT: NOT NULL constraint failed: site_category.site_id
```
which is scary I'm not sure how it came to generate this query that basically would corrupt the entire table.

Second block, I'd like to vanish the collection and start with a new fresh one, it looks like the insert happens before the delete, so the constraints make it fail:
```
UniqueConstraintViolationException: insert into `site_category` (`site_id`, `category_id`) values (1, 2), (1, 3) - SQLITE_CONSTRAINT: UNIQUE constraint failed: site_category.site_id, site_category.category_id
```

**Additional context**
When trying to make the first use case work, I've also run into a `Expected 1 bindings, saw 2` knex error, unfortunately I was not able to reproduce in the spec file, but that's another potential issue. I suspect fixing the 2 use cases above should fix this one as well.

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.6 |
| your-driver | sqlite and mysql |

**Comment by B4nan** [comment] 2021-06-09 09:17
Note that your test case it not fully correct, you can't use the `Category` entities you created in the hook, as you clear the EM afterwards. After this will be fixed, you would end up with insert statements for those, as they are considered as new entities (the current EM is cleared as is not aware of them).

But I can confirm that both issues are there even with the test being fixed. The problem is with propagation of changes, in general 1:m is inverse side, nothing is really handled from it, it just propagates the changes you do to the owning side (where the FKs are stored).

So you can probably get around issues like this by working with the owning side. Need to add new item? Just create it without working with the collection, all what's important is to pass the FKs there, the inverse side - the collection - is purely virtual thing.

**Comment by B4nan** [comment] 2021-06-09 14:55
Actually, what do you expect from your code? Removing from 1:m collection normally unsets the property on the owning side, or if you use `orphanRemoval: true` such entity gets removed. Your owning side is a nonnullabe PK, it can't be unset, that is why you are getting the `NOT NULL constraint failed` error. So if you want to be able to remove an item from such collection, you should enable orpah removal for it. 

Both test cases are still buggy, just wanted to point this out, as without the orpah removal it does not make sense to me.

**Comment by maphe** [comment] 2021-06-09 17:49
By suggesting to work with the owning side, do you mean basically replacing `s.siteCategories.remove(sc2);` by `orm.em.getRepository(SiteCategory).remove(sc2);`? I tried it, there's no delete statement in the transaction.
It does work tho using `remove` from the collection with `orphanRemoval` enabled, so that's a win.

I think I can work with that, the removeAll would be a nice to have but not really a blocker. Thanks for the help.

**Closed** 2021-06-18 17:45 UTC
Labels: bug
