### ISSUE TITLE
OneToOne inverse relationship causing entity to be marked as touched

### ISSUE THREAD

**Issue by christiaan-lombard** [mikro-orm/mikro-orm#4323] opened 2023-05-05 13:27 UTC
**Describe the bug**

This issue caused some very bad side effects for us:

When loading an entity using find with a OneToOne relationship, the related entity is always marked as touched. 
Should you call flush after loading the entity, the related entity will revert to its default values!

**To Reproduce**

Repo to reproduce bug: https://github.com/christiaan-lombard/mikro-orm-touched-one-to-one-issue

See comments below:

```ts
import { MikroORM } from "@mikro-orm/sqlite";
import {
  Entity,
  FlushMode,
  OneToOne,
  OptionalProps,
  PrimaryKey,
  Property,
} from "@mikro-orm/core";

@Entity()
class Blog {
  @PrimaryKey()
  id!: number;

  @Property({ length: 64, nullable: true })
  title: string | null = null;

  // Note the OneToOne relationship with inverse
  @OneToOne(() => "User", (e: User) => e.blog, { owner: true })
  author!: any;
}

@Entity()
class User {
  [OptionalProps]!: "createdAt" | "updatedAt" | "balance" | "blog" | "version";

  @PrimaryKey()
  id!: number;

  @Property({ length: 64, nullable: false, default: "Default" })
  name: string = "Default";

  @Property()
  balance: number = 0;

  // Note the OneToOne relationship with inverse
  @OneToOne(() => "Blog", (e: Blog) => e.author)
  blog!: Blog;
}

async function runTest() {
  const orm = await MikroORM.init({
    dbName: "test.db",
    port: 33070,
    forceEntityConstructor: true,
    entities: [Blog, User],
    allowGlobalContext: true,
    debug: true,
    validateRequired: false,
    validate: false,
    strict: false,
    flushMode: FlushMode.COMMIT,
  });

  await orm.schema.dropSchema();
  await orm.schema.createSchema();

  const id = 1;

  const author = orm.em.create(User, {
    id,
    name: "Some User",
    balance: 5000,
  });

  orm.em.create(Blog, {
    id,
    title: "Test Blog",
    author,
  });

  await orm.em.flush();
  // begin
  // insert into `user` (`id`, `name`, `balance`) values (1, 'Some User', 5000) returning `id`, `name`, `balance`
  // insert into `blog` (`id`, `title`, `author_id`) values (1, 'Test Blog', 1) returning `id`
  // commit
  orm.em.clear();

  const entity = await orm.em.findOneOrFail(Blog, { id });
  // select `b0`.* from `blog` as `b0` where `b0`.`id` = 1

  const work = orm.em.getUnitOfWork();
  await work.computeChangeSets();

  // BUG: entity.author is marked as touched!!
  console.log(entity.author.__helper.__touched); // = true

  const changes = work.getChangeSets();
  console.log(changes[0].payload); // {name: 'Default', balance: 0}

  await orm.em.flush();
  // NOOOO!! ENTITY IS RESET TO DEFAULT VALUES !!!!!!!
  // begin
  // update `user` set `name` = 'Default', `balance` = 0 where `id` = 1
  // commit

  await orm.close();
}

runTest().then(() => console.log("done"), console.error);

```

**Expected behavior**
An unpopulated related entity in OneToOne relationship should not be marked as touched.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.14.0 |
| typescript | ? |
| mikro-orm | 5.7.4 |
| your-driver | sqlite/mysql |

**Comment by B4nan** [comment] 2023-05-06 09:39
This is caused by the `forceEntityConstructor` option. I don't think this is really a bug, using that in combination with property initializers seems to be wrong by definition. I will take a closer look if we can get around that before closing.

**Comment by B4nan** [comment] 2023-05-06 11:06
I am a bit afraid that fixing this will introduce more edge cases, but since it can be a scoped fix only for those using `forceEntityConstructor`, I will give it a go. With that said, I would still discourage the combination of `forceEntityConstructor` with property initializers. The fix might be reverted if it will end up breaking for existing users.

Note that new entities created via `em.create` _will_ use the constructor regardless of this option, the flag controls the very opposite - construction of managed entity instances.

**Closed** 2023-05-06 12:08 UTC

**Comment by christiaan-lombard** [comment] 2023-05-08 07:57
Thanks @B4nan 

Yeah, we already removed all property initializers just to be sure.
