### ISSUE TITLE
"After" life cycle hooks should run after successful commit, not flush (UoW commit)

### ISSUE THREAD

**Issue by rhyek** [mikro-orm/mikro-orm#1160] opened 2020-12-04 06:53 UTC
I noticed this behavior while working with explicit transaction.

https://github.com/mikro-orm/mikro-orm/blob/75452007eb9cf20077c0feb2567a24f701c1b15d/packages/core/src/EntityManager.ts#L352-L356

Basically, if you call `commit` on the entity manager, it itself calls `flush` which calls the unit of work's `commit` which in turn dispatches all the "after" entity life cycle hook events such as `afterCreate`, etc.

Only after doing all this does the entity manager's commit method actually send out the commit statement to the sql database. Since commits can fail for several reasons, it would be safer to dispatch said hooks after the actual commit statement has been sent out and no error occurred.

There should also be an `afterCommit` event so that it could be used instead of `afterFlush` when wanting to account for similar cases.

**Comment by B4nan** [comment] 2020-12-04 08:17
Not sure how you expect that could work. Hooks are bound to the entity lifecycle, there is no guarantee they will be executed only if the TX succeeds, there is even no guarantee there will be a TX. In general you should clear the EM after you catch failed TX, mainly because of this. I don't see a way we could make those changes only when the TX is successful, especially because of nested transactions (not talking about that being a huge breaking change).

> There should also be an afterCommit event so that it could be used instead of afterFlush when wanting to account for similar cases.

I also don't see a difference between `afterCommit` and `afterFlush` (let's forget for a while there is EM.commit method - that is only to allow working with the current transaction context of the EM - but in general `commit` is what the UoW does, and it is the same as EM's flush). Those are literally the same operations. Both can fail, the problem is the same. Making `afterCommit` to be bound only to EM.commit sounds very weird/unexpected - and with explicit nested TXs the issue you are raising here would be the very same again (as in context of inner TX you don't know how the outer one will end up). 

In the ORM context, the commit phase is what happens when you flush, where the changes are computed, hooks executed, ... And calling `em.flush()` is literally the same as `em.commit()` in this regard. 

Also `afterFlush` is not fired if the TX was not successful. 

The problem as I understand it is not about hooks, but about the identity map. You make changes to entities, and when the TX fails, you end up with entities in the state that broke the database. At this stage we don't even have the original entity data so we could somehow rollback the state of the entities. The rule of thumb is to clear the EM and start over - if you use explicit TXs with `em.transactional()`, the inner EM is already a fork with clear EM, so doing it like this, you can simply ignore the inner EM, and start new TX from the outer one (with another clear fork). 

I will close this, hooks are designed based on doctrine, and I believe it works the same in hibernate too. I doubt such big players would make it "wrong". But staying subscribed, please don't take that as if there can't be any further discussions :]

**Closed by B4nan** 2020-12-04 08:17 UTC

**Comment by rhyek** [comment] 2020-12-04 10:02
> Also afterFlush is not fired if the TX was not successful

How can this be? The event is emitted before this line or am I missing something?:
https://github.com/mikro-orm/mikro-orm/blob/75452007eb9cf20077c0feb2567a24f701c1b15d/packages/core/src/EntityManager.ts#L354

If you meant UnitOfWork/application level commit, then I am not concerned with that. My concern is with transaction commits at the database level.

Since you mentioned Doctrine, I came accross this open [issue](doctrine/orm#7103) that basically asks for the same `afterCommit` so there is some relevant discussion there already.

> The rule of thumb is to clear the EM and start over - if you use explicit TXs with em.transactional()

I am not very much concerned with latent state in-memory after a commit fails as I am using NestJS and request-scoped entity managers anyways, so this failed state is discarded anyways.

The fact of the matter is, these "after" events are being sent out before the actual database commit is being done.

I will explain my use-case, but I believe this is an issue with a wider impact.

I am writing a GraphQL API where I want to handle multiple mutations per operation (request). This is something the gql spec and Apollo handle perfectly well. The mutations are all run in sequence and not in parallel. One strategy to handle circumstances where one of these mutations fails while the others do not is to undo all the changes of every mutation so that error recovery is more straight-forward from a client perspective. The natural way to implement this behavior would be to use a single database transaction for all the mutations and in case of any error just roll back everything. This is what that looks like:

```ts
@Plugin()
export class SqlTransactionForMutations implements ApolloServerPlugin {
  requestDidStart(ctx: GraphQLRequestContext) {
    const em: EntityManager = ctx.context.req._ormEm;
    let isMutation = false;
    let hadErrors = false;
    return {
      async didResolveOperation(ctx) {
        if (ctx.operation.operation === 'mutation') {
          isMutation = true;
          await em.begin();
        }
      },
      didEncounterErrors() {
        hadErrors = true;
      },
      async willSendResponse() {
        if (isMutation) {
          if (hadErrors) {
            await em.rollback();
          } else {
            await em.commit();
          }
        }
      },
    } as GraphQLRequestListener;
  }
}
```

Now, since in GraphQL mutations you can optionally request result data that may result in further `select` queries (table joins), it is important to execute a `flush` before that final `commit` so that the order of database queries for, for example, two update mutations is the following:

- mutation 1:
  - select query for current value
  - update query
  - select query for result
- mutation 2:
  - select query for current value
  - update query
  - select query for result
- em.commit
  - commit

and NOT:

- mutation 1:
  - select query for current value
  - select query for result
- mutation 2:
  - select query for current value
  - select query for result
- em.commit
  - update 1
  - update 2
  - commit

So to avoid leaving those `updates` up until the end, I am doing something like this in my domain service:
```ts
  async update(id: number, values: Partial<Contact>) {
    const contact = await this.contactRepository.findOneOrFail(id);
    Object.assign(contact, values);
    await this.contactRepository.flush(); // send update query
    return contact;
  }
```

The problem is that since I need to do those preliminary flushes, they are triggering the "after" hooks way too early (not just before the final `commit`, but also even before any further mutations are resolved).

That is essentially my problem.

**Comment by B4nan** [comment] 2020-12-04 10:08
> How can this be? The event is emitted before this line or am I missing something?:

That line won't be even executed if TX fails. The UoW.commit is what fires that event. 

> If you meant UnitOfWork/application level commit, then I am not concerned with that. My concern is with transaction commits at the database level.

That is exactly what I was talking about. And it needs to stay like this, commit is what UoW does. You can never have commit without flush and vice versa, they are the same things. 

> it is important to execute a flush before that final commit

This is literally impossible, as again, commit = flush. UoW does not care about what db commit is, which is what you are referring to. 

> So to avoid leaving those updates up until the end, I am doing something like this in my domain service:

Using `Object.assign()` is dangerous, don't update entities like this, it will never handle collections and references.

**Comment by B4nan** [comment] 2020-12-04 10:26
The code of `EM.commit`:

```ts
  async commit(): Promise<void> {
    await this.flush(); // this will create nested transaction and execute it, here is where hooks are handled, and here is where the TX will fail - the failure results in thrown error, so the rest of the code won't be executed
    await this.getConnection('write').commit(this.transactionContext); // if we reach this line, the queries were already executed successfully, this will only issue the final commit query
    delete this.transactionContext;
  }
```

The second line could fail only if it was some inconsistency in the data. I can't come up with an example where this would happen, but it most probably can if there are parallel requests in place. Still the failure would be caused not by the state of entities, but rather by the parallel request making changes at the same time. Failures like this won't fire any event, the event system is based on what UoW does and this happens outside of it.

**Comment by rhyek** [comment] 2020-12-04 23:05
@B4nan thank you for your detailed responses.

> The second line could fail only if it was some inconsistency in the data. I can't come up with an example where this would happen, but it most probably can if there are parallel requests in place.

These are exactly the cases I am worried about. Commits can fail on the database side for a number of reasons including concurrency issues.

I have prepared a repo with a number of integration tests trying to show the different behaviors when using the supported transaction setups. https://github.com/rhyek/mikro-orm-flush-test

Since purposely causing a `commit` failure on the database side is not very straightforward/easy to do, I am showing all transaction setups with an additional dimensional criteria: when constraints are checked on DML queries (`insert`) and when they are checked until the `commit` statement is sent (what this github issue is about). Please interpret those commit failures as representation of what happens during concurrency errors (like the one you mentioned about multiple requests).

A screenshot of the results:
![image](https://user-images.githubusercontent.com/702922/101223527-d6dd2480-3651-11eb-88e6-986b53af012f.png)

Here I am confirming that when using explicit transactions with explicit `begin`, `commit`, and `rollback` method calls, the "after" hooks are in fact being called even when a commit on the database side fails, but additionally, I found that the `em.commit` method does not capture that error and it goes on to resolve instead of rejecting its promise.

**Comment by rhyek** [comment] 2020-12-05 20:32
> Still the failure would be caused not by the state of entities, but rather by the parallel request making changes at the same time. Failures like this won't fire any event, the event system is based on what UoW does and this happens outside of it.

I want to understand if the behavior I showed is considered a bug. I believe the ORM should account for failed SQL `commit` statements. As it stands now, working with "after" hooks for side-effects (email notifications and such) seems dangerous to me when using explicit transactions, but even without the use of hooks, requests could appear to a client to have been successful when in fact they weren't.

Furthermore, some use-cases may or may not include the need to send out DML statements at different times than the `commit`, like my own with my GraphQL API. So, the current (and working) behavior as of version 4.3.2 of being able to do `em.flush` to send out those `update`, `insert`, `delete` statements and then separately using `em.commit` for the `commit` is perfect.
