### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by imcm7** [mikro-orm/mikro-orm#4681] opened 2023-09-07 18:51 UTC
mikro-orm schema:update --run 

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

What it want from me?

**Comment by B4nan** [comment] 2023-09-07 18:59
Duplicate of #4679. Try using latest dev version, should be fixed there.

**Closed by B4nan** 2023-09-07 18:59 UTC
