### ISSUE TITLE
MikroORM is difficult to find using NPM search

### ISSUE THREAD

**Issue by rafsawicki** [mikro-orm/mikro-orm#438] opened 2020-03-30 20:37 UTC
I've been introduced to this project by a friend of mine and I was wondering why I haven't heard of this project earlier - after all I've been looking for TypeORM replacement for quite some time and it looks like an amazing alternative.

My other friend have noticed that when you search for "orm" in NPM registry (either via [text query](https://www.npmjs.com/search?q=orm) or [keyword query](https://www.npmjs.com/search?q=keywords:orm)), MikroORM is nowhere to be found on first few pages, even though quite a few projects with way lower weekly downloads count are there. On the [fifth page](https://www.npmjs.com/search?q=orm&page=4&perPage=20), a helper library `@mikro-resources/fixtures` is visible, but no main package in sight.

I believe that this situation hurts project discoverability a lot. Are you aware of this issue? Maybe something can be done about it.

**Comment by B4nan** [comment] 2020-03-30 21:01
Hmm that's strange. I was trying hard to appear at the top on npms.io, where I am on 7th place currently. 

https://npms.io/search?q=orm

And the package quality on npmjs.com should be the very same thing (although recently they removed the link to npms.io: https://stackoverflow.com/a/49867121/3665878). 

I found it on 10th page, and the quality numbers are very low, not the same as on npms.io. I guess I will try to concat their support.

**Comment by rafsawicki** [comment] 2020-03-31 07:06
I've did some digging and using NPM analyzer API I've compared [MikroORM](https://api.npms.io/v2/package/mikro-orm) results with [one of the less popular results from the first page](https://api.npms.io/v2/package/w-orm-mongodb). MikroORM has better score across the board and yet it's quality bar is lower when using npm search (I've found it on 12h page). Hopefully their support will be able to help, as currently it looks like something is broken on their end, maybe some caching issue.

**Comment by B4nan** [comment] 2020-04-01 08:11
Quick updat, managed to pass thru the first level support, issue is now escalated to higher level, hopefully they will help. 

Also they confirmed that npm is using the data from npms.io, it can be also found in their docs: 

> You can use the npm search bar to find packages to use in your projects. npm search uses npms and the npms analyzer; for more information on both, see https://npms.io/about.

https://docs.npmjs.com/searching-for-and-choosing-packages-to-download

**Comment by B4nan** [comment] 2020-04-08 10:40
Still no update from their end, but we might get around this in v4 anyway, as v4 will be monorepo with multiple packages, so hopefully those will be analyzed correctly.

**Comment by B4nan** [comment] 2020-04-14 17:50
Lol, so after 2 weeks of waiting, CTO of npm just replied that the algo they use is not the same, confirmed it sucks and is not transparent, but they are not planning to do anything about it :D there might be some revamp "in near future". or not :D 

So closing this, as I have no clue on what should I improve (I am quite sure the problem is on their end, so hopefully with the new v4 packages I will be more lucky...)

**Closed by B4nan** 2020-04-14 17:50 UTC

**Comment by rafsawicki** [comment] 2020-04-15 16:04
That's really disappointing response from them. I also hope that the new package structure will allow MikroORM to be more visible in NPM search results again -fingers crossed :) .
