### ISSUE TITLE
flush on entities with jsonb field behaving differently based on number of entities flushed

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#2293] opened 2021-10-21 13:53 UTC
**Describe the bug**
Example Entity
```typescript
@Entity()
export class TestEntity {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string;

  @Property()
  jsonField: { name: string }[] = [{ name: 'hello' }];
}
```

If i create a new entity and persist it and call flush or persistAndFlush, it will work and produces the correct result in the DB. (`[{"name": "hello"}]`). 

But if i create more than one entity and try to flush them all at once i get an error:
`insert into "test_entity" ("json_field") values ('[object Object]'), ('[object Object]') returning "id" - invalid input syntax for type json`.
This only happens if i use an array for jsonField, if it's just and object it will work correctly.
I have a workaround for this by defining my own custom mikro-orm type for this, which works correctly. But this behavior is still very odd.

**Stack trace**
```
DriverException: insert into "test_entity" ("json_field") values ('[object Object]'), ('[object Object]') returning "id" - invalid input syntax for type json
    at PostgreSqlExceptionConverter.convertException (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
    at PostgreSqlDriver.convertException (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:202:54)
    at /home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:206:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PostgreSqlDriver.nativeInsertMany (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:211:19)
    at ChangeSetPersister.persistNewEntitiesBatch (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:79:21)
    at ChangeSetPersister.persistNewEntities (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:72:13)
    at UnitOfWork.commitCreateChangeSets (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:520:9)
    at UnitOfWork.persistToDatabase (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:473:13)
    at PostgreSqlConnection.transactional (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:53:25)
    at UnitOfWork.commit (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:184:17)
    at SqlEntityManager.flush (/home/patrick/development/gastromatic/invoice-service/node_modules/@mikro-orm/core/EntityManager.js:497:9)
    at /home/patrick/development/gastromatic/invoice-service/src/app.ts:38:5

```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.10.0 |
| typescript | 4.4.3 |
| mikro-orm | 4.5.9 and next |
| mikro-orm/postgres | 4.59 and next |

**Comment by B4nan** [comment] 2021-11-15 17:50
Weird, it actually behaves the same with a single entity flush on my end. And the problem is, that the type is infered as text array, not a JSON, so the serialization ends up with `insert into "test_entity" ("json_field") values ('{[object Object]}') returning "id"`. Specifying the type is needed here:

```ts
  @Property({ type: 'json' })
  jsonField: { name: string }[] = [{ name: 'hello' }];
```

Then it works fine (for both single and multi entity flush, both 4.x and 5.0). Will close this with a passing test case, if you can find a way to make it fail, will be happy to reopen.

(it might be something fixed but not yet released, so if you see issues with 4.5.9, try latest 4.x dev version)

**Closed** 2021-11-15 17:51 UTC
