### ISSUE TITLE
Both `count()` and `findAndCount()` throw when using sqlite driver and entity has composite primary key

### ISSUE THREAD

**Issue by itsame-luigi** [mikro-orm/mikro-orm#3045] opened 2022-04-21 19:25 UTC
**Describe the bug**
When using the sqlite driver, calling `count` or `findAndCount` on an `EntityManager` when the entity has a composite primary key results in an error:

**Stack trace**
```
      at SqliteExceptionConverter.convertException (packages/core/src/platforms/ExceptionConverter.ts:8:12)
      at SqliteExceptionConverter.convertException (packages/sqlite/src/SqliteExceptionConverter.ts:61:18)
      at SqliteDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:246:50)
      at packages/core/src/drivers/DatabaseDriver.ts:251:18
      at SqlEntityManager.count (packages/core/src/EntityManager.ts:649:19)
      at Object.<anonymous> (tests/issues/GHxxxx.test.ts:59:19)
      previous Error: select count(distinct `m0`.`provider_id`, `m0`.`user_id`) as `count` from `member` as `m0` - SQLITE_ERROR: wrong number of arguments to function count()
```

```
      at SqliteExceptionConverter.convertException (packages/core/src/platforms/ExceptionConverter.ts:8:12)
      at SqliteExceptionConverter.convertException (packages/sqlite/src/SqliteExceptionConverter.ts:65:18)
      at SqliteDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:240:50)
      at packages/core/src/drivers/DatabaseDriver.ts:245:18
      at SqlEntityManager.count (packages/core/src/EntityManager.ts:681:19)
          at async Promise.all (index 1)
      at SqlEntityManager.findAndCount (packages/core/src/EntityManager.ts:325:31)
      at Object.<anonymous> (tests/issues/GHxxxx.test.ts:64:24)
      previous Error: select count(distinct `m0`.`provider_id`, `m0`.`user_id`) as `count` from `member` as `m0` - SQLITE_ERROR: wrong number of arguments to function count()
```

**To Reproduce**
The error is illustrated by the following test case:

```ts
import { Entity, ManyToOne, MikroORM, PrimaryKey } from '@mikro-orm/core';

@Entity()
export class Provider {

  @PrimaryKey()
  id: number;

  constructor(id: number) {
    this.id = id;
  }
}

@Entity()
export class User {

  @PrimaryKey()
  id: number;

  constructor(id: number) {
    this.id = id;
  }

}

@Entity()
export class Member {

  @ManyToOne(() => Provider, { eager: true, primary: true })
  provider: Provider;

  @ManyToOne(() => User, { eager: true, primary: true })
  user: User;

  constructor(a: Provider, b: User) {
    this.provider = a;
    this.user = b;
  }

}

describe('issue', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Provider, User, Member],
      dbName: `:memory:`,
      type: 'sqlite',
    });
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(async () => {
    await orm.close(true);
  });

  it('should be able to call count', async () => {
    const count = await orm.em.count(Member);
    expect(count).toBe(0);
  });

  it('should be able to call findAndCount', async () => {
    const [_, count] = await orm.em.findAndCount(Member, {});
    expect(count).toBe(0);
  });
});
```

**Expected behavior**
Both `count()` and `findAndCount()` should succeed for a composite primary key just as they do for a single primary key.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.12.0 |
| typescript | 4.6 |
| mikro-orm | 5.1.2 |
| your-driver | sqlite |

**Comment by B4nan** [comment] 2022-04-21 21:07
This is actually a duplicate of #889 and what I said there is still valid, this should be fixed in knex rather than worked around here. There is even a PR for that (https://github.com/knex/knex/pull/2977).

cc @kibertoad pretty please? 🙏

**Comment by kibertoad** [comment] 2022-04-21 21:11
Thanks for the ping, bumped priority. If Olivier is not available, I'll try to get to it myself over weekend.

**Comment by B4nan** [comment] 2022-06-27 11:09
I will close this, its not actionable from our end (not without patching knex again or working it around completely, which is far bigger change than Im willing to do).

**Closed by B4nan** 2022-06-27 11:09 UTC
Labels: bug
