### ISSUE TITLE
Indexes in sub-document for mongodb

### ISSUE THREAD

**Issue by anlauren** [mikro-orm/mikro-orm#2129] opened 2021-08-16 10:27 UTC
**Describe the bug**
It seems that mikro-orm mondodb driver doesn't support sub-document indexing. That makes sense for SQL but it's common practice in mongodb. It looks like it's not possible to create an index like `myField.mySubField`.
Now it could be because of how i've written the embedding that's it's not working.
**Stack trace**
```
[Nest] 79737   - 08/16/2021, 11:19:23 AM   [ExceptionHandler] Entity Test has wrong index definition: 'testEmbedded.a' does not exist. You need to use property name, not column name. +47ms
MetadataError: Entity Test has wrong index definition: 'testEmbedded.a' does not exist. You need to use property name, not column name.
    at Function.unknownIndexProperty (/Users/antoinelaurent/virtual-event-service/node_modules/@mikro-orm/core/errors.js:126:16)
    at MetadataValidator.validateIndexes (/Users/antoinelaurent/virtual-event-service/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:109:50)
    at MetadataValidator.validateEntityDefinition (/Users/antoinelaurent/virtual-event-service/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:26:14)
    at MetadataDiscovery.processEntity (/Users/antoinelaurent/virtual-event-service/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:297:24)
    at filtered.forEach.meta (/Users/antoinelaurent/virtual-event-service/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:52:63)
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.discover (/Users/antoinelaurent/virtual-event-service/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:52:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
```typescript

@Embeddable()
export class TestEmbedded {
  @Property()
  a: number;
}

@Entity({ tableName: 'test' })
@Index({ properties: ['testEmbedded.a'] })
export class Test extends BaseEntity {
  @Embedded({
    entity: () => TestEmbedded,
    object: true,
  })
  testEmbedded: TestEmbedded;
}

```
**Expected behavior**
Should be able to use a `.` notation in mongodb indexes

**Additional context**
My original problem arises when i tried to create a compound index with a sub-field and a field of a document.

**Versions**

| Dependency | Version |
| - | - |
| node | v10.22.0 |
| typescript | v4.0.5 |
| mikro-orm | v4.3.4|
| @mikro-orm/mongodb |v4.3.4 |

**Comment by B4nan** [comment] 2021-08-16 10:43
Indeed, this is not supported -> this is a feature request, not a bug report.

**Comment by andrey-hohlov** [comment] 2022-08-03 07:48
Hi, @B4nan 
Any plans on it?

It works for ```@Index``` decorator : 

```
@Index({ options: { 'embedded.property': 1 } })
```

But nothing works for ```@Unique```.

**Comment by B4nan** [comment] 2022-08-03 08:03
Fastest way to see this happen by sending a PR 🤷

**Comment by bebjakub** [comment] 2023-08-04 07:00
@andrey-hohlov This works for a unique index, also with a sparse index if needed...
```
@Property({ nullable: true, unique: true })
```
more #4495

**Comment by B4nan** [comment] 2023-08-04 09:28
Interesting, maybe this got fixed by some unrelated change over time. Will keep this open till we have some explicit tests for it so we can be sure it actually works (and it will remain working over time as well)

**Comment by B4nan** [comment] 2023-08-26 11:33
Okay, this apparently works as expected, not sure what fixed it. Added tests to ensure it really works, will mark it as a feature commit so it gets into the changelog, although it will just add the test.

**Closed** 2023-08-26 11:35 UTC
Labels: enhancement, mongodb
