### ISSUE TITLE
TypeError: domain.enter is not a function

### ISSUE THREAD

**Issue by SDAdham** [mikro-orm/mikro-orm#1220] opened 2020-12-19 07:14 UTC
**Describe the bug**
I am trying to migrate to `Mikro-Orm` and I have been stuck with this error for > 3 days, where the problem with the error is that it's not helping me knowing where it's coming from, and the problem is that it happens on random areas, I commented a lot of code and trying to isolate where it's coming from but it's unpredictable. I've did a lot of research and I came up with this https://github.com/mysqljs/mysql/issues/1949 and https://github.com/sipcentric/node-pbx-client/issues/4 , the only i can think about it's the `mysql` which is why i'm guessing it might be liked to MikroOrm.

Any expert advise would be a lot appreciated please.

The problem is that nestjs api that I'm bolding is not responding with the response

**Stack trace**
```
domain.js:547
  domain.enter();
         ^

TypeError: domain.enter is not a function
    at IncomingMessage.EventEmitter.emit (domain.js:547:10)
    at resume_ (_stream_readable.js:972:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**To Reproduce**
I don't know how it's occurring.

**Expected behavior**

**Additional context**

**Versions**
Below are all the dependencies of the project:
```
 "dependencies": {
    "@angular/animations": "~10.1.4",
    "@angular/cdk": "^10.2.3",
    "@angular/common": "~10.1.4",
    "@angular/compiler": "~10.1.4",
    "@angular/core": "~10.1.4",
    "@angular/forms": "~10.1.4",
    "@angular/localize": "^10.0.4",
    "@angular/material": "^10.2.3",
    "@angular/platform-browser": "~10.1.4",
    "@angular/platform-browser-dynamic": "~10.1.4",
    "@angular/router": "~10.1.4",
    "@fortawesome/angular-fontawesome": "^0.7.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/free-regular-svg-icons": "^5.14.0",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@mikro-orm/core": "^4.3.4",
    "@mikro-orm/mariadb": "^4.3.4",
    "@mikro-orm/mysql": "^4.3.4",
    "@mikro-orm/nestjs": "^4.2.0",
    "@mikro-orm/reflection": "^4.3.4",
    "@mikro-orm/sql-highlighter": "^1.0.1",
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/passport": "^7.1.0",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/schedule": "^0.4.1",
    "@nestjs/swagger": "^4.6.1",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@tinymce/tinymce-angular": "^4.1.0",
    "angular-calendar": "^0.28.16",
    "angular-google-charts": "^1.1.4",
    "basic-auth": "^2.0.1",
    "bootstrap": "^4.5.0",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "clipboard": "^2.0.6",
    "cookie-parser": "^1.4.5",
    "core-js": "^3.6.5",
    "credit-card-type": "^9.1.0",
    "cryptojs": "^2.5.3",
    "date-fns": "^2.15.0",
    "express": "^4.17.1",
    "express-list-routes": "^0.1.4",
    "express-mysql-session": "^2.1.4",
    "express-session": "^1.17.1",
    "font-awesome": "^4.7.0",
    "helmet": "^4.1.1",
    "imap": "^0.8.19",
    "jquery": "^3.5.1",
    "locutus": "^2.0.14",
    "mermaid": "^8.6.0",
    "mikro-orm": "^4.3.4",
    "monaco-editor": "^0.20.0",
    "mysql": "^2.18.1",
    "nest-winston": "^1.4.0",
    "nestjs-mikro-orm": "^1.0.3",
    "nestjs-session": "^1.0.1",
    "ng-pick-datetime": "^7.0.0",
    "ngx-avatar": "^4.0.0",
    "ngx-bootstrap": "^5.6.1",
    "ngx-clipboard": "^13.0.1",
    "ngx-cookie-service": "^3.0.4",
    "ngx-monaco-editor": "^9.0.0",
    "node-cryptojs-aes": "^0.4.0",
    "passport": "^0.4.1",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "~6.6.0",
    "swagger-ui-express": "^4.1.4",
    "tslib": "^2.0.0",
    "winston": "^3.3.3",
    "xlsx": "^0.16.8",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.4",
    "@angular/cli": "~10.1.4",
    "@angular/compiler-cli": "~10.1.4",
    "@angular/language-service": "^10.0.4",
    "@compodoc/compodoc": "^1.1.11",
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/clipboard": "^2.0.1",
    "@types/cryptojs": "^3.1.29",
    "@types/express": "^4.17.3",
    "@types/express-session": "^1.17.3",
    "@types/imap": "^0.8.31",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "26.0.10",
    "@types/jquery": "^3.5.4",
    "@types/jqueryui": "^1.12.13",
    "@types/node": "12.12.41",
    "@types/passport-local": "^1.0.33",
    "@types/supertest": "^2.0.8",
    "@types/webpack-env": "^1.15.3",
    "@typescript-eslint/eslint-plugin": "3.9.1",
    "@typescript-eslint/parser": "3.9.1",
    "codelyzer": "^6.0.0",
    "eslint": "7.7.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-prettier": "^3.1.3",
    "husky": "^4.2.5",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jest": "26.4.2",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.19.1",
    "pretty-quick": "^2.0.1",
    "protractor": "~7.0.0",
    "supertest": "^4.0.2",
    "ts-jest": "26.2.0",
    "ts-loader": "^6.2.1",
    "ts-node": "9.0.0",
    "tsconfig-paths": "^3.9.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2",
    "wait-on": "^5.2.0",
    "webpack-env": "^0.8.0"
  },
```
| Dependency | Version |
| - | - |
| node |v14.15.1|
| your-driver | mysql |

**Comment by B4nan** [comment] 2020-12-19 14:11
There is no such code in MikroORM, it uses the domain api, but it is not calling `domain.enter()` anywhere - it uses `domain.run()`. Based on the docs, it looks like `domain.run()` is [using this method](https://nodejs.org/api/domain.html#domain_domain_enter) under the hood, still I don't see how this could be connected to what MikroORM does. 

But `domain.enter()` is a valid method so the issue is more like where is this code executed - as if this is executed in browser context it can't work - there is no domain api.

Btw you should not use the `mikro-orm` metapackage, use just the new packages like `@mikro-orm/core` etc... But that is definitely not causing this.

Will close this, as without a reproduction I don't see a way I could help. You can check this project, its for v3 but the rest looks up to date and upgrading th ORM should not be that difficult.

https://github.com/wilberalx/mikro-orm-angular-electron

Btw the other issues you found are interesting, this seems like a good candidate of what it could be: https://github.com/mysqljs/mysql/issues/1949#issuecomment-386899783

I can assure you MikroORM is not doing that, domain api is used only on 2 places:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/RequestContext.ts
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/TransactionContext.ts

**Closed by B4nan** 2020-12-19 14:11 UTC

**Comment by SDAdham** [comment] 2020-12-21 23:01
@B4nan , i was able to finally capture the full stack trace, can you please take a look at it?https://github.com/nestjs/nest/issues/5985#issuecomment-749236971
I see the following:
```
Domain.run (<node_internals>/domain.js:371)
create (<ProjectDir>\node_modules\@mikro-orm\core\utils\RequestContext.js:28)
use (<ProjectDir>\node_modules\@mikro-orm\nestjs\mikro-orm.middleware.js:20)
<anonymous> (<ProjectDir>\node_modules\@nestjs\core\router\router-proxy.js:9)
```

**Comment by SDAdham** [comment] 2020-12-21 23:03
![image](https://user-images.githubusercontent.com/11182824/102830225-f7bcbc80-443c-11eb-8543-b1503befabbe.png)

**Comment by SDAdham** [comment] 2020-12-21 23:17
Actually @B4nan , please ignore my last comment, I disabled `registerRequestContext` and that's when i realized it's not really related to mikroorm.

**Comment by SDAdham** [comment] 2020-12-21 23:20
I fixed the problem here at https://github.com/nestjs/nest/issues/5985#issuecomment-749249907
