### ISSUE TITLE
TypeError when running migration:up

### ISSUE THREAD

**Issue by mohammadraufzahed** [mikro-orm/mikro-orm#4468] opened 2023-06-20 07:24 UTC
When attempting to run the migration:up command, the following error occurs:

```
TypeError: core_1.Utils.mergeConfig is not a function
    at PostgreSqlConnection.getKnexOptions (/app/node_modules/.pnpm/@mikro-orm+knex@5.7.12_@mikro-orm+core@5.7.7_@mikro-orm+migrations@5.7.7_pg@8.10.0/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:118:37)
    at PostgreSqlConnection.createKnexClient (/app/node_modules/.pnpm/@mikro-orm+knex@5.7.12_@mikro-orm+core@5.7.7_@mikro-orm+migrations@5.7.7_pg@8.10.0/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:110:38)
    at PostgreSqlConnection.connect (/app/node_modules/.pnpm/@mikro-orm+postgresql@5.7.7_@mikro-orm+core@5.7.7_@mikro-orm+migrations@5.7.7/node_modules/@mikro-orm/postgresql/PostgreSqlConnection.js:12:28)
    at PostgreSqlDriver.connect (/app/node_modules/.pnpm/@mikro-orm+core@5.7.7_@mikro-orm+migrations@5.7.7_@mikro-orm+postgresql@5.7.7/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:53:31)
    at MikroORM.connect (/app/node_modules/.pnpm/@mikro-orm+core@5.7.7_@mikro-orm+migrations@5.7.7_@mikro-orm+postgresql@5.7.7/node_modules/@mikro-orm/core/MikroORM.js:70:46)
    at Function.init (/app/node_modules/.pnpm/@mikro-orm+core@5.7.7_@mikro-orm+migrations@5.7.7_@mikro-orm+postgresql@5.7.7/node_modules/@mikro-orm/core/MikroORM.js:39:23)
    at Function.handleMigrationCommand (/app/node_modules/.pnpm/@mikro-orm+cli@5.7.7_@mikro-orm+migrations@5.7.7_@mikro-orm+postgresql@5.7.7_pg@8.10.0/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:73:21)
```
To Reproduce

Run the migration:up command.
See the error mentioned above.
Expected behavior
The migration should run successfully without any errors.

Additional context

Node version: 18
TypeScript version: 5.1.3
Mikro-ORM version: 5.7.12
Driver: PostgreSQL
Please provide any additional context or information that might be helpful in troubleshooting the bug.

**Comment by B4nan** [comment] 2023-06-20 08:05
Duplicate of #4448. Upgrade to latest.

**Closed by B4nan** 2023-06-20 08:05 UTC
