### ISSUE TITLE
Postgres Inheritance support?

### ISSUE THREAD

**Issue by KevinMusgrave** [mikro-orm/mikro-orm#3510] opened 2022-09-16 07:01 UTC
### Is your feature request related to a problem? Please describe.
In Postgres, there are some nice features for tables [defined with the `INHERITS` operator](https://www.postgresql.org/docs/current/ddl-inherit.html).

I looked at the [mikro-orm documentation on inheritance](https://mikro-orm.io/docs/inheritance-mapping), and it seems to be more about code inheritance, rather than db inheritance.

### Describe the solution you'd like
I'd like to define entities that use the `INHERITS` postgres operator.

**Comment by B4nan** [comment] 2022-10-03 18:51
Isnt this basically the same as #1575, just with PG specific `inherits` operator?

**Comment by KevinMusgrave** [comment] 2022-10-03 19:17
Ah maybe, I don't know enough to say for sure. Anyway I ended up using a different design because there are too many [limitations with Postgres inheritance](https://www.postgresql.org/docs/current/ddl-inherit.html#DDL-INHERIT-CAVEATS).

**Comment by B4nan** [comment] 2022-10-03 19:33
That's the reason why I think this is in fact a duplicate of #1575 - this is much more complicated than just the schema support, we need to handle this in many other places in the ORM, namely in QB and driver level. 

Closing this in favour of #1575, I will consider using `inherits` operator for postgres with that feature, if I ever work on that (I feel like it will be quite a huge task to accomplish, so might never happy from my end...)

**Closed by B4nan** 2022-10-03 19:33 UTC
Labels: enhancement
