### ISSUE TITLE
Mutating class prototype incompatible with babel transpiled class

### ISSUE THREAD

**Issue by waihokwok** [mikro-orm/mikro-orm#840] opened 2020-09-16 04:53 UTC
**Describe the bug**
I try to define an entity with a SerializedPrimaryKey property. The id getter/setter can be correctly defined when using ts-jest. However, transpiling the code with babel in production build (I am using nestjs), the id getter/setter fails to be defined.
For example:
```typescript
@Entity()
class MyEntity {
  @PrimaryKey()
  _id!: ObjectId;

  @SerializedPrimaryKey()
  id!: string;
}

// some where in my code
const myEntity = new MyEntity();
wrap(myEntity).assign({ _id: new ObjectId() }, { em })
console.log(myEntity.id) // output string id in test but undefined in production
```

Later, after looking into the source code, I found that EntityHelper define the id property to the entity prototype. However, with above definition, the transpiled MyEntity class constructor would define id property with descriptor { value: undefined, writable: true, enumerable: true, configurable: true}. As a result, the entity instance will never reference to its prototype for its id property.

**Workaround**
I figured out two workarounds.

The first way is to use Object.create instead of constructor. The limitation is that property initializers would not be called.
```typescript
@Entity()
class MyEntity {
  @PrimaryKey()
  _id!: ObjectId;

  @SerializedPrimaryKey()
  id!: string;
}

// some where in my code
const myEntity = Object.create(MyEntity.prototype);
wrap(myEntity).assign({ _id: new ObjectId() }, { em })
console.log(myEntity.id) // output string id in both test and production
```
The second way is to define id as a dummy getter as it would be overwrite by EntityHelper anyway. The dummy getter is not looking good.
```typescript
@Entity()
class MyEntity {
  @PrimaryKey()
  _id!: ObjectId;

  @SerializedPrimaryKey()
  get id(): string { return '' };
}

// some where in my code
const myEntity = new MyEntity();
wrap(myEntity).assign({ _id: new ObjectId() }, { em })
console.log(myEntity.id) // output string id in both test and production
```

**To Reproduce**
Here is my babel.config.json:
``` json
{
	"presets": [
		[
			"@babel/env",
			{
				"targets": {
					"browsers": "> 0.5%, last 2 versions, Firefox ESR, not dead"
				},
				"useBuiltIns": "usage",
				"corejs": { "version": 3, "proposals": true }
			}
		],
		"@babel/preset-react",
		"@babel/preset-typescript"
	],
	"plugins": [
		"babel-plugin-transform-typescript-metadata",
		["@babel/plugin-proposal-decorators", { "legacy": true }],
		["@babel/plugin-proposal-class-properties", { "loose": true }]
	]
}
```

**Afterthought**
It seems that mutating class prototype may cause some inconsistent behaviors between untranspiled and transpiled code. Is there a better way to achieve this? Babel complies the ES6 spec and typescript may change in future. Thus, I think this issue should be addressed.
Thanks for the great work.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.8.0 |
| typescript | 4.0.2 |
| @mikro-orm/core | 4.0.0 |
| @mikro-orm/mongodb | 4.0.0 |
| @babel/cli | 7.10.5 |
| @babel/core | 7.11.4 |
| @babel/plugin-proposal-class-properties | 7.10.4 |
| @babel/plugin-proposal-decorators | 7.10.5 |
| @babel/preset-env | 7.11.0 |
| @babel/preset-react | 7.10.4 |
| @babel/preset-typescript | 7.10.4 |

**Comment by B4nan** [comment] 2020-09-16 06:31
please create a reproduction, I do not have any babel project I could test this on.

**Comment by waihokwok** [comment] 2020-09-16 08:38
This is just an example. I will create a reproduction soon.

In my use case (I am using nestjs), I am trying to write a abstract entity service that does the CRUD operation. The service will inject an EntityRepository.  For the creation case, I would like to insert a new entity to the database with some data (which may include primary key).

My first try was to use repository.create but the ctor will not be called if the data include primary key. Also, it does not work when using embedded property. So, I try to get the EntityMetadata and use the class in metadata to construct a entity instance then call repository.assign with the data afterward. My example above is based on this use case.

It would be great if EntityRepository/EntityManager has a method that support creating entity with primary key provided. This should be a feature request.

**Comment by B4nan** [comment] 2020-09-16 09:12
Do you really need that `@babel/plugin-proposal-class-properties`? Sounds like that is exactly the root cause here, especially with the `loose` option.

What is that good for?

**Comment by waihokwok** [comment] 2020-09-16 09:45
Class property syntax is not supported by old browser and nodejs. Without this plugin, it cannot read the class property syntax. For details, see [https://babeljs.io/docs/en/babel-plugin-proposal-class-properties](url)

**Comment by B4nan** [comment] 2020-09-16 09:47
Well, ES6 do support classes. Are you targeting older environments? Why? What exactly?

**Comment by waihokwok** [comment] 2020-09-16 11:02
Here is the reproduction [repo](https://github.com/waihokwok/mikro-orm-babel-project/tree/master)
If everything works as intended, all ids logged in console should be defined.

**Comment by B4nan** [comment] 2020-09-17 08:10
Weird, to me it looks like the `loose` option does not work. The docs states that it should use assignments instead of `defineProperty`:

https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

But regardless of the value, the compiled output looks the same. 

@elendirx you are using those babel plugins too right? how does your compiled entity look like in terms of the property definition?

**Comment by B4nan** [comment] 2020-09-17 10:00
Anyway, I will close this, I don't see a way around this from the ORM standpoint - I do not see a way to define the get/set on the actual instance, as the instance can be created via ctor and there we would not have any way to add the get/set. 

To me this is either not working `loose` option, wrong babel configuration, or a bug in babel. The property is already defined on the prototype, but babel is overriding it. From the docs, I would say its the first - `loose` option should not use `defineProperty` but it does. You might wanna open issue on babel's end.

This issue seems to be about something similar, but closed without a proper resolution :/ 

https://github.com/babel/babel/issues/9773

**Closed by B4nan** 2020-09-17 10:00 UTC
Labels: bug

**Comment by waihokwok** [comment] 2020-09-18 05:02
@B4nan Yes, I think the incompatibility comes from implementation of babel legacy decorator and ts decorator.

I have another workaround that is based on the fact that babel (with my configuration at least) will not call `Object.defineProperty` if the property decorator return a new property descriptor. So, the following would work.

``` typescript
function MySerializedPrimaryKey(): any {
	// Typescript property decorator will ignore property descriptor return.
	// Therefore, it should have no effect when running with tsc
	return function (target: Object, property: string): any {
		SerializedPrimaryKey()(target, property);
		return {}; // dummy descriptor
	};
}

export abstract class BaseEntity {
	@PrimaryKey()
	_id!: ObjectId;

	@MySerializedPrimaryKey()
	id!: string;

	@Property()
	created_at: Date = new Date();

	@Property({ onUpdate: () => new Date() })
	updated_at: Date = new Date();
}

```
The general rule is to return a property descriptor in property decorator whenever we want to overwrite it with getter/setter later on.

I don't I know if It is a good idea to "fix" the decorators in MikroOrm in this way. It should not break current typescript usage (of course, it needs further testing). I do think that it is an issue from babel legacy decorator though. Will it be better to just mention this issue somewhere in the document and propose some workarounds?

Anyway, thanks for your help :)

**Comment by B4nan** [comment] 2020-09-18 07:50
The thing is, I considered babel as not supported pretty much the whole time, just recently there were some people who tried, failed, reported, and we managed to find few ways to make it happen. Will be happy to accept a PR with "Using with Babel" recipe. 

And if all what's needed is to return something from the decorator, sure we can do it. I noticed I am already retuning the `target` from some decorators, so I did unify that and return from all of them now. Let's see if that helps, will be in `4.0.4` probably later today.

**Comment by B4nan** [comment] 2020-09-18 14:06
Maybe we could return the target conditionally - based on some environment variable like `BABEL_DECORATORS_COMPAT` (will be happy to hear better name suggestions hehe), as we do not have access to the ORM instance inside decorators.

**Comment by waihokwok** [comment] 2020-09-19 02:45
Returning target should be for class decorator only. Returning `target` for property decorator, which should be the prototype, may cause some issues when using babel. Let me further elaborate the workaround. Babel will call `Object.defineProperty(target, property, desc)` where desc is the return of decorator. In most cases, defining a configurable property in the prototype should be fine but it will be safer to just return a property descriptor if we are going to overwrite it later. See these two helper functions in transpiled code.

``` javascript
function _applyDecoratedDescriptor(
	target, // prototype of MyEntity
	property, // 'id'
	decorators,  // SerializedPrimaryKey and Reflect.metadata(design:type, ...)
	descriptor, // { configurable: true,  enumerable: true,  writable: true,  initializer: null } (default descriptor in babel)
	context // undefined
) {
	var desc = {};
	Object.keys(descriptor).forEach(function (key) {
		desc[key] = descriptor[key];
	});
	desc.enumerable = !!desc.enumerable;
	desc.configurable = !!desc.configurable;
	if ('value' in desc || desc.initializer) {
		desc.writable = true;
	}
	desc = decorators // should become the return of our decorator
		.slice()
		.reverse()
		.reduce(function (desc, decorator) {
			return decorator(target, property, desc) || desc;
		}, desc);
	if (context && desc.initializer !== void 0) {
		desc.value = desc.initializer ? desc.initializer.call(context) : void 0;
		desc.initializer = undefined;
	}
	if (desc.initializer === void 0) { // this block should run as we do not provide a initializer
		Object.defineProperty(target, property, desc); // may cause issue if target is returned
		desc = null;
	}
	return desc;
}

function _initializerDefineProperty(target, property, descriptor, context) {
	if (!descriptor) return; // This is the key why my workaround works
	Object.defineProperty(target, property, { // The root cause of my issue. This does not respect the class-property plugin loose options
		enumerable: descriptor.enumerable,
		configurable: descriptor.configurable,
		writable: descriptor.writable,
		value: descriptor.initializer
			? descriptor.initializer.call(context)
			: void 0,
	});
}
```
Although returning target is wrong in general, I wonder how it breaks tsc. **What does it exactly break?**  The type of PropertyDecorator:
``` typescript
type PropertyDecorator = (target: Object, propertyKey: string | symbol) => void
```
I assume that typescript will not use the return of decorator at all. If it just breaks type-checking, we can set return type to any. (like what i did).

Anyway, I may open an issue in babel later. If the workaround does not work, just hold on by now. I think patching this with a conditional return looks a bit hacky to me.

**Comment by B4nan** [comment] 2020-09-19 11:16
It does use the return value somehow, it won't allow me to override the properties which is needed later on. Returning `{}` or `{ writable: true }` won't help. 

Btw I found this post with few notes about the legacy option in babel:

https://github.com/babel/babel/issues/8864#issuecomment-688535867

Namely this bit:

> In Babel, if a legacy decorator returns a descriptor, this causes the class field to always use [[Define]] semantics, regardless of the value of the loose option for the plugin-proposal-class-properties option (which seems like a bug), which is opposite of TypeScript behavior.

I will go with the environment variable:

    if (process.env.BABEL_DECORATORS_COMPAT) {
      return {} as any;
    }

**Comment by B4nan** [comment] 2020-09-19 11:54
`4.0.4` with the `BABEL_DECORATORS_COMPAT` is out

**Comment by waihokwok** [comment] 2020-09-20 02:17
If it does use the return of decorator, using `BABEL_DECORATORS_COMPAT ` env will be safer options.
Btw, have you tried returning `{ configurable: true }` descriptor?

**Comment by Shan5152** [comment] 2022-08-28 03:46
MikroORM.init({
  forceEntityConstructor: true, // or specify just some entities via `[Author, 'Book', ...]` 
});
