### ISSUE TITLE
Problem with find in Entity Repositories

### ISSUE THREAD

**Issue by AstroCorp** [mikro-orm/mikro-orm#761] opened 2020-08-20 14:20 UTC
**Describe the bug**

this return a empty array, but in db return results

```
const oldRefreshTokens = await this.refreshTokenRepository.find({ 
			$and: [
				{ 
					expiresIn: { 
						$lte: new Date()
					} 
				}
			] 
		});

console.log(oldRefreshTokens);
```

Table:
![image](https://user-images.githubusercontent.com/22180346/90782684-6f4bd500-e2ff-11ea-87ed-d1262fb6a007.png)

![image](https://user-images.githubusercontent.com/22180346/90783233-1e88ac00-e300-11ea-9fab-dd942cf08805.png)

![image](https://user-images.githubusercontent.com/22180346/90783305-2e07f500-e300-11ea-9bf9-d5503ced4941.png)

**Versions**

| Dependency | Version |
| - | - |
| node | 14.3.0 |
| typescript | 3.9.7 |
| mikro-orm | 3.6.15 |
| your-driver | sqlite3 |

**Comment by B4nan** [comment] 2020-08-20 14:24
That does not really sound like ORM bug. I can already tell you that from this I can't reproduce anything :]

**Comment by B4nan** [comment] 2020-08-20 14:25
If the very same query is returning result and not from the ORM, you are most probably using different database.

**Comment by B4nan** [comment] 2020-08-20 14:28
I will close this, will be happy to reopen if you provide a reproduction repository, but I am quite sure this is just a misconfiguration (wrong db name, or actually path as in sqlite the db is a file).

**Comment by AstroCorp** [comment] 2020-08-20 15:21
await this.refreshTokenRepository.findAll() return results.

repo: https://github.com/AstroCorp/Ace-Books-Backend

src/tasks/tasks.service.ts

**Comment by B4nan** [comment] 2020-08-20 15:26
I see you have sqlite3 v5 there, that might be the issue, when I was trying to upgrade to that some tests were failing, they have some bug in there (don't have the link now but I am subscribed to the issue, so I know it is not yet resolved).

Btw it looks like you did not add any data to the dump? Both methods returning empty array for me:

```
[Nest] 73448   - 20. 08. 2020 17:24:03   [MikroORM] [query] select `e0`.* from `refresh_token` as `e0` where `e0`.`expires_in` <= '2020-08-20 17:24:03.004' [took 1 ms]
[]
[Nest] 73448   - 20. 08. 2020 17:24:03   [MikroORM] [query] select `e0`.* from `refresh_token` as `e0` [took 1 ms]
[]
```

**Comment by B4nan** [comment] 2020-08-20 15:37
Yeah it is definitely caused by sqlite 5, there is an issue with `Date` conversion, it stores it via wrong format so comparison won't work. 

Downgrade to v4.2 and it should work.

**Comment by B4nan** [comment] 2020-08-20 15:55
I am quite sure its caused by the date format in the db. Lets keep this open for now.

**Comment by AstroCorp** [comment] 2020-08-20 19:40
Yes, the problem is in the date format, in this way, I solved it:

In my entity:

`expiresIn!: Date|string;`

In my where:

```
const oldRefreshTokens = await this.refreshTokenRepository.find({ 
			$and: [
				{ 
					expiresIn: { 
						$lte: format(new Date(), 'yyyy-MM-dd HH:mm:ss'),
					},
				},
			],
		});
```

**Comment by B4nan** [comment] 2020-08-25 08:44
I don't think this is something we can handle from the ORM point of view (if something, this should be knex or sqlite3 issue). If you want to store dates as strings with sqlite, you should probably use custom type to have absolute control over the format (so the dates stored by ORM will also be strings and not timestamps). But still, there is #739, so it won't help much in terms of querying until that is resolved.

**Closed by B4nan** 2020-08-25 08:44 UTC
Labels: bug
