### ISSUE TITLE
Transaction query already complete, run with DEBUG=knex:tx for more info

### ISSUE THREAD

**Issue by kenspirit** [mikro-orm/mikro-orm#3074] opened 2022-04-29 03:19 UTC
**Describe the bug**
Occasionally, it's reported such an error in our code where `transactional` is used to execute some statement.  I know that we should not use a global entity manager and I do use such code to create it per request in express app.

```javascript
async function initDatabase(app, config, schemas) {
  await _initORM(config, schemas);

  app.use((req, res, next) => {
    RequestContext.create(orm.em, next);
  });
}
```

**Stack trace**

```
DriverException: Transaction query already complete, run with DEBUG=knex:tx for more info
    at MySqlExceptionConverter.convertException (/usr/src/app/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at MySqlExceptionConverter.convertException (/usr/src/app/node_modules/@mikro-orm/mysql/MySqlExceptionConverter.js:80:22)
    at MySqlDriver.convertException (/usr/src/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:173:54)
    at /usr/src/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:177:24
    at async SqlEntityManager.nativeDelete (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:431:21)
    at async _deleteDEK (/usr/src/app/server/replication/replication.service.js:286:5)
    at async /usr/src/app/server/util/repository.util.js:447:20
    at async em.getConnection.transactional (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:346:29)
    at async MySqlConnection.transactional (/usr/src/app/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25)
    at async deleteExportData (/usr/src/app/server/replication/replication.controller.js:40:14)
    at async /usr/src/app/server/config/routes.manager.js:28:13

previous Error: Transaction query already complete, run with DEBUG=knex:tx for more info
    at completedError (/usr/src/app/node_modules/knex/lib/execution/transaction.js:396:9)
    at /usr/src/app/node_modules/knex/lib/execution/transaction.js:362:24
    at Promise._execute (/usr/src/app/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/src/app/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/src/app/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL2.trxClient.query (/usr/src/app/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)
    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async MySqlConnection.executeQuery (/usr/src/app/node_modules/@mikro-orm/core/connections/Connection.js:68:25)
    at async MySqlConnection.execute (/usr/src/app/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:88:21)
    at async QueryBuilder.execute (/usr/src/app/node_modules/@mikro-orm/knex/query/QueryBuilder.js:358:21)
    at async SqlEntityManager.nativeDelete (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:431:21)
    at async _deleteDEK (/usr/src/app/server/replication/replication.service.js:286:5)
    at async /usr/src/app/server/util/repository.util.js:447:20
```

**Additional context**
Our code on starting an transaction and usage on mikro is like this.  The emphasis is that `_em()` dynamically detect and return the entity manager based on whether it's in transaction or not.  Would this usage cause problem?

```javascript
// This is how the utility class retrieves the entity manager
function _em() {
  let em = TransactionContext.getEntityManager();
  if (!em) {
    em = RequestContext.getEntityManager();
  }
  return em;
}

function _repo(model) {
  return _em().getRepository(model);
}

// This is our Repository utility class
async function executeWithTransaction(handler, options, ...params) {
  const opts = _.merge({}, { isolationLevel: IsolationLevel.READ_COMMITTED }, options);
  let fn = handler;
  if (opts.scope) {
    fn = handler.bind(opts.scope);
    delete opts.scope;
  }

  return _em().transactional(async (em) => {
    const result = await fn(MODELS, params);
    return result;
  }, opts);
}

async function _deleteDEK(models, [param1, param2]) {
  for (const dek of param2) {
    await models[dekModel].destroyAll(where);

    await models[dekModel].count(where);
  }
}

async function destroyAll({ model, where }) {
  return _repo(model).nativeDelete(convertWhere(where));
}

RepositoryUtil.executeWithTransaction(_deleteDEK, undefined, param1, param2);
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.1 |
| typescript | javascript |
| mikro-orm | ^5.0.4 |
| your-driver | ? |

**Comment by B4nan** [comment] 2022-04-29 07:38
I don't understand why are you wrapping things yourself. All of `_em`, `_repo` and `executeWithTransaction` methods seem to be useless, you don't need that, just work with the global instance - as long as you are inside the request context handler (so inside the middleware), it will use the contextual fork automatically. What you do in the `_em` method just mimics what is already done internally in `em.getContext()` and this method is used in all places where we work with the identity map.

> Occasionally

Closing, as you haven't provided any reproduction. Can't help with "Occasionally" :]

**Closed by B4nan** 2022-04-29 07:38 UTC

**Comment by jahudka** [comment] 2023-02-07 18:37
I'm having the same issue and unfortunately also only "occasionally". The thing is, I haven't been able to reproduce the issue no matter what I tried. I know that it happens in production, but nowhere else - and I can't very well debug it on the production instance. From what I've been able to gather, the issue seems to be that sometimes either MikroORM or Knex ends up using an old transaction context which has been already closed - I'd literally have something like this in my console output:

```
knex:tx trx5: Starting top level transaction
knex:client acquired connection from pool: __knexUid1
knex:tx trx2: Transaction completed: <sql query supposed to run on trx5>
knex:tx trx5: releasing connection
knex:client releasing connection to pool: __knexUid1
```

But I don't even know where to begin to look for the cause of this behaviour. I gather that it probably has something to do with `AsyncLocalStorage` and a broken async context tracking, but since there are like 17 different layers between my code and whatever is actually deciding which connection to use it's really hard to figure out where to put my `console.log()` calls. Knex being as labyrinthine as it is doesn't help. Is there really nothing more you can say to help debug this issue? I know that debugging reproducible issues is easy and fun, but some issues just aren't like that. I've been trying to fix this for two weeks. Anything, really anything you can tell me to point me in the right direction would be much appreciated.

**Comment by B4nan** [comment] 2023-02-07 22:44
If the problem is lost async context, I think it will be rather about the layers you put on top of the ORM/knex, it's often some middleware plugins (e.g. auth). I recall people with similar issues when trying to query the database from inside hooks. If you can, it would be also a good idea to go for the most up to date node version possible, bugs happen, bugs get fixed, and those issues are often at the lowest level. But I don't think the issue will be in knex.

But it can be as well some race condition either in your code or in the ORM, hard to say. This error is far away from being specific without any context. 

First step should be to replicate locally and somehow consistently, I'd use something like autocannon for that if you think it's about concurrent requests. And simplify while being able to trigger it...

**Comment by jahudka** [comment] 2023-02-19 16:03
So I think I found it at last.. I think it's [this line](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/EntityManager.ts#L115) in `EntityManager`.

Basically, whenever you call `em.getRepository()`, if that repository doesn't exist yet, it is created; the default `EntityRepository` class by itself doesn't do anything too magical, it just keeps a reference to the EM and then forwards all method calls to the respective EM methods, supplying the entity name as the first argument. But the crucial thing is that when a repository is being created, it is passed an EM instance resolved from the current execution context (that is, something like `transactionEm ?? requestEm ?? globalEm`). The repository is then stored in a repository map of the EM which created it, but that might be a different EM than the one which the repository keeps a reference to. In my case the repository was created on the global EM, but since the `em.getRepository()` call happened inside a transaction, the repository kept a reference to the _transaction's_ EM - _forever_ - so it kept reusing the transaction context long after it was supposed to be gone.

I'm not sure if this is for some reason intentional behaviour in Mikro. Is it?

**Comment by B4nan** [comment] 2023-02-19 18:26
Let me know if [this](https://github.com/mikro-orm/mikro-orm/commit/05fabb9c3b06fa8a811a9ef475281c0df5836ee2) helps.

**Comment by jahudka** [comment] 2023-02-19 23:12
I haven't actually tried it yet, but I can see well enough what the code does - I'm pretty sure this will fix the issue _in some scenarios_. It would fix it in mine, for example - because the code in question only had access to an entity manager and it was getting a repository instance out of it at the call site, right before calling the repository's `findOne()` method.

But consider a situation where somebody uses some kind of DI container and they want their repositories to be registered as services. If they define the repository service factories as something like `return di.get('em').getRepository(...)`, then they could run into exactly the same issue as I did, except the repository with the wrong EM reference would be stored in the DIC, instead of in the global EM's repository map.

What about just changing [this line](https://github.com/mikro-orm/mikro-orm/blob/3928e789d9efec0def8fd62f24d11b020a70ca25/packages/core/src/EntityManager.ts#L115) in the original version of the method to pass `this`, instead of `this.getContext(false)`, to the newly created repository? Since the repository just delegates to the EM and the EM always does context resolution anyway, it shouldn't break anything, and the user's only responsibility would then be to always work with the global EM (which they should be doing anyway). What do you think?

**Comment by B4nan** [comment] 2023-02-20 08:06
I don't see how the current could could break a DI container. You register services in global scope, so you end up with global EM repository map, storing global repository instances. Those always have `useContext: true`, so they won't fail the way you described - they always check the async local storage for context. Your problem was creating repository from a fork.

**Comment by jahudka** [comment] 2023-02-20 11:50
The problem is that most DICs I know create services on demand. Consider something like this:

```typescript
class DIC {
  private readonly services: Map<string, object> = new Map();

  async get(service: string): Promise<object> {
    if (!this.services.has(service)) {
      this.services.set(service, this.create(service));
    }

    return this.services.get(service)!;
  }

  async create(service: string): Promise<object> {
    switch (service) {
      case 'orm': return MikroORM.init(...);
      case 'em': return (await this.get('orm')).em;
      case 'someRepo': return (await this.get('em')).getRepository(SomeEntity);
    }
  }
}

const di = new DIC();
const app = express();

// #1
app.use(async (req, res, next) => RequestContext.create(await di.get('em'), next));

app.get('/example1', async (req, res, next) => {
  const repo = await di.get('someRepo'); // #2
  res.json(await repo.findOne(1));
});


app.get('/example2', async (req, res, next) => {
  const em = await di.get('em');

  await em.transactional(async () => {
    const repo = await di.get('someRepo'); // #3
    res.json(await repo.findOne(1));
  });
});
```

1. The DIC creates services on-demand and stores the instances it creates for later reuse.
2. If the first request the app handles is `GET /example1`, the following will happen:
    1. The middleware at `#1` will fork the EM
    2. The `/example1` handler will request the `someRepo` service from the DIC at `#2`, which will cause the service to be created; but the `RequestContext` is populated while creating the repository, so the repository is injected with the request-specific EM fork created at `#1`. The service is stored in the DIC.
    3. Anywhere in app code the `someRepo` service is requested after this, the one created during the first request will be returned, and it will have the wrong EM.
3. Same thing with having the first request go to `GET /example2`, except in that case it will be the `TransactionContext` and the transaction EM fork, instead of `RequestContext` and request fork.

Obviously, these things can happen in vastly distant parts of the actual app code when things are properly separated out into some semblance of an object model, so it won't be as easily apparent that it's happening.

**Comment by B4nan** [comment] 2023-02-20 13:49
I guess you are right.

Sidenote: need to change the visibility of `repo._em` to private to enforce the usage of the `em` getter, as `repo._em.id` will not respect the context anymore and it could confuse some people.

**Comment by jahudka** [comment] 2023-02-20 15:29
Actually, is that even needed? I mean the `_em` and the getter with `.getContext()` - doesn't the EM always call `.getContext()` internally where needed? Couldn't the repository just store the reference to the EM in a protected readonly property?

**Comment by Heniker** [comment] 2025-02-11 23:36
For me this error happened after I forgot to add `await` to `em.flush()` call.
Though I can't seem to reproduce this locally either.

**Comment by kenspirit** [comment] 2025-05-23 06:48
We found that using bluebird's `Promise.map` to call other DB access operation might occationally cause such issue but have not figured out why yet.
