### ISSUE TITLE
Incorrect import of MikroORM module

### ISSUE THREAD

**Issue by hugocruzlfc** [mikro-orm/mikro-orm#5472] opened 2024-04-18 11:23 UTC
### Describe the bug

I am trying to import the MikroORM module from '@mikro-orm/postgresql' following the new documentation:

# All drivers now re-export the @mikro-orm/core package
+import { Entity, PrimaryKey, MikroORM, EntityManager } from '@mikro-orm/mysql';

But I get error when I want to use it like this.

[Nest] 32002  - 04/18/2024, 1:21:42 PM     LOG [NestFactory] Starting Nest application...
[info] MikroORM version: 6.2.1
[discovery] ORM entity discovery started, using TsMorphMetadataProvider
[Nest] 32002  - 04/18/2024, 1:21:42 PM     LOG [InstanceLoader] MikroOrmModule dependencies initialized +15ms
[Nest] 32002  - 04/18/2024, 1:21:42 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AppModule (?). Please make sure that the argument PostgreSqlMikroORM at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If PostgreSqlMikroORM is a provider, is it part of the current AppModule?
- If PostgreSqlMikroORM is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing PostgreSqlMikroORM */ ]
  })

### Reproduction

import { MikroOrmModule } from '@mikro-orm/nestjs';
import { MikroORM } from '@mikro-orm/postgresql';
import { Module, OnModuleInit } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import config from './mikro-orm.config';

@Module({
  imports: [
    MikroOrmModule.forRoot(config),
    ConfigModule.forRoot({
      isGlobal: true,
      load: [configurations],
       cache: true,

    }),
  ],
  controllers: [],
  providers: [],
})
export class AppModule implements OnModuleInit {
  constructor(private readonly orm: MikroORM) {}

  async onModuleInit(): Promise<void> {
    await this.orm.getMigrator().up();
  }
}

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

├─┬ @mikro-orm/cli@6.2.1 │ ├── @mikro-orm/core@6.2.1 deduped │ └─┬ @mikro-orm/knex@6.2.1 │   └── @mikro-orm/core@6.2.1 deduped ├── @mikro-orm/core@6.2.1 ├─┬ @mikro-orm/migrations@6.2.1 │ └── @mikro-orm/core@6.2.1 deduped ├─┬ @mikro-orm/nestjs@5.2.3 │ └── @mikro-orm/core@6.2.1 deduped ├─┬ @mikro-orm/postgresql@6.2.1 │ └── @mikro-orm/core@6.2.1 deduped └─┬ @mikro-orm/reflection@6.2.1   └── @mikro-orm/core@6.2.1 deduped

### Node.js version

 v20.11.0

### Operating system

macOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tsangste** [comment] 2024-04-18 13:24
This is more an issue with the nestjs package. I've already mentioned (https://github.com/mikro-orm/nestjs/pull/153#issuecomment-2011968618) it in the mikro-orm v6 compatibility PR.

**Comment by B4nan** [comment] 2024-04-18 13:30
Closing as duplicate of https://github.com/mikro-orm/nestjs/issues/123, I want to look into this soon.

**Closed by B4nan** 2024-04-18 13:30 UTC
