### ISSUE TITLE
Indexes on subdocuments [Mongo]

### ISSUE THREAD

**Issue by murbanowicz** [mikro-orm/mikro-orm#2187] opened 2021-09-10 12:18 UTC
**Is your feature request related to a problem? Please describe.**
At this moment, when we have an embeddable (like an address in my case) with some index defined on it, the index is not being created.

**Describe the solution you'd like**
MikroORM would catch up the index on the embeddable and create it on the parent document with proper property name (place.address when `{object: true}`)

**Describe alternatives you've considered**
Manual creation of the indexes outside of the app - not great in the end.

Subdocuments are used a lot with Mongo and this should be possible.

**Comment by B4nan** [comment] 2021-09-10 12:22
duplicate of #2129

**Closed by B4nan** 2021-09-10 12:22 UTC
Labels: enhancement
