### ISSUE TITLE
Method convertToJSValue() from custom type is not invoked properly when calling it within the nested embeddables.

### ISSUE THREAD

**Issue by sevenryze** [mikro-orm/mikro-orm#5059] opened 2023-12-29 09:55 UTC
### Describe the bug

Method convertToJSValue() from custom type is not invoked properly when calling it within the nested embeddables. It gets an Object instead of string parameter.

### Reproduction

```typescript
class GeoPoint {
  constructor(
    readonly latitude: number,
    readonly longitude: number
  ) {}
}

class GeoPointType extends Type<GeoPoint | undefined, string | undefined> {
  override convertToDatabaseValue(
    value: GeoPoint | undefined
  ): string | undefined {
    if (!value) {
      return value;
    }

    return `point(${value.latitude} ${value.longitude})`;
  }

  override convertToJSValue(value: string | undefined): GeoPoint | undefined {
    const m = value?.match(/point\((-?\d+(\.\d+)?) (-?\d+(\.\d+)?)\)/i);

    if (!m) {
      return undefined;
    }

    return new GeoPoint(+m[1], +m[3]);
  }

  override convertToJSValueSQL(key: string) {
    return `ST_AsText(${key})`;
  }

  override convertToDatabaseValueSQL(key: string) {
    return `ST_PointFromText(${key}, 4326)`;
  }

  override getColumnType(): string {
    return "point SRID 4326";
  }
}

@Embeddable()
class SnapshotMore {
  @Property({
    type: GeoPointType,
  })
  position!: GeoPoint;

  @Property({
    nullable: true,
  })
  description?: string; // To make it work, delete this property, which is also weird :)
}

@Embeddable()
class Snapshot {
  @Embedded(() => SnapshotMore)
  ref!: SnapshotMore;
}

@Entity()
class Outer {
  @PrimaryKey()
  id!: number;

  @Embedded(() => Snapshot)
  bigSnapshot!: Snapshot;  // To make it work, change this property name from 'bigSnapshot' to 'snapshot', which is weird :)
}

async function main() {
  const orm = await MikroORM.init({
    driver: MySqlDriver,
    clientUrl: "",
    debug: true,
    entities: [Outer, Snapshot],
  });

  const em = orm.em.fork();

  const snapshotMore = new SnapshotMore();
  snapshotMore.position = new GeoPoint(21, 32);

  const snapshot = new Snapshot();
  snapshot.ref = snapshotMore;

  const outer = new Outer();
  outer.id = 123_456;
  outer.bigSnapshot = snapshot;

  await em.persistAndFlush([outer]);

  const result = await em.findOne(Outer, {
    id: outer.id,
  });

  await orm.close();
}

main();
```

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

5.9.6

### Node.js version

v20.3.1

### Operating system

MacOS 14.1.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sevenryze** [comment] 2023-12-29 09:57
I suspect this question might be related to this issue https://github.com/mikro-orm/mikro-orm/issues/4622#issuecomment-1692348238 . However, the original problem stated that it was resolved in version 5.8, so I'm not sure if it introduced some regression?

**Comment by B4nan** [comment] 2023-12-29 10:38
it works fine in v6, a lot of things changed in there, including some edge cases for custom types. i won't be backporting that at this point, some of the fixes were potentially breaking. this particular problem seems to be fixed by the support for naming strategy in embeddables, which on its own is surely not a portable change.

so closing as resolved in v6, i'd suggest you upgrade, v6 is pretty much ready and will be released to stable next week. 

---

btw I'd appreciate if reproductions contain the import statements too :]

**Closed by B4nan** 2023-12-29 10:38 UTC

**Comment by sevenryze** [comment] 2023-12-29 11:40
Haha, my bad. Next time, if given the chance, I'll definitely include the complete import statement. Also, congratulations on the arrival of V6! A lot of effort seems to have gone into improving developer experience and robustness, making it a highly dependable ORM tool. Once again, thank you for your hard work and dedication.
