### ISSUE TITLE
Remove/Add from a Collection isn't working

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#594] opened 2020-06-02 18:12 UTC
**Describe the bug**
I have a Rig, I add GPU's to it.
GPU burns out, I need to replace it with a new GPU.

I've tried to code this up, but it isn't working for some reason. It used to work when I coded it up, but with a newer version it is no longer working for some reason.

I've created a test case.

**To Reproduce**

* [clone the project](https://github.com/lookfirst/mikro-example/)
* yarn test
* this is the specific test: https://github.com/lookfirst/mikro-example/blob/master/test/db/rig2.spec.ts

**Expected behavior**
Tests should pass.

**Versions**

| Dependency | Version |
| node | latest |
| typescript | 3.9.3 |
| mikro-orm | 3.6.14 |
| postgres | latest |

**Comment by lookfirst** [comment] 2020-06-03 21:39
I figured out the issue. Can look at the diffs if you care enough. I wasn't passing the right object into remove(). I wonder if Collection should have a removeOrFail() method to make it more clear.

**Comment by B4nan** [comment] 2020-06-04 09:13
Hmm I don't really like the idea of `removeOrFail`, it would probably not help you here anyway, the logic in `Collection.remove()` is not bound to identity of the entity, we check the serialized PK, so basically two strings. That means it should be removed anyway... 

```typescript
remove(...items: (T | Reference<T>)[]): void {
  for (const item of items) {
    const entity = Utils.unwrapReference(item);
    const idx = this.items.findIndex(i => wrap(i, true).__serializedPrimaryKey === wrap(entity, true).__serializedPrimaryKey);

    if (idx !== -1) {
      delete this[this.items.length - 1]; // remove last item
      this.items.splice(idx, 1);
      Object.assign(this, this.items); // reassign array access
    }

    this.propagate(entity, 'remove');
  }
}
```

But I see your collection is actually 1:m, so its more about the propagation of the change, as you are adjusting the inverse side (but the change needs to happen on owning side, which is m:1).

**Comment by B4nan** [comment] 2020-06-07 09:07
I will close this one, as I don't see anything we can do here. The issue is only with a mistake in tests, it would not be present in the actual code (where you don't use `em.clear()` manually).

**Closed by B4nan** 2020-06-07 09:07 UTC
Labels: bug

**Comment by lookfirst** [comment] 2020-06-07 18:34
Absolutely. Thanks. Sorry for not closing it.
