### ISSUE TITLE
Unique constraints of the same name get removed twice, once lowercase once as-is

### ISSUE THREAD

**Issue by dotBeFoRE** [mikro-orm/mikro-orm#3126] opened 2022-05-19 10:57 UTC
**Describe the bug**
Since v5 I cannot use two Properties with the same unique name to create a shared unique constraint. I refactored the Entity to use the Unique decorator on the class itself, but once I create a migration mikro-orm removes the previous unique constraint twice once as the constraint was previously written and once converted to lowercase (a constraint that didn't exist on the table).
> It also tries to drop the constraint twice when you try to drop the migration

Previous situation:
```ts
@Entity()
class CoronaData extends BaseEntity<CoronaData, 'id'> {
  constructor(coronaInfo : CoronaInfo) {
    super();
    this.community = coronaInfo.Municipality_name;
    this.totalReported = coronaInfo.Total_reported;
    this.deceased = coronaInfo.Deceased;

    this.date = new Date(coronaInfo.Date_of_publication);
  }

  @PrimaryKey()
  id!: number;

  @Property({ unique: 'dateCommunity' })
  date!: Date;

  @Property({ unique: 'dateCommunity' })
  community!: string;

  @Property()
  totalReported!: number;

  @Property()
  deceased!: number;
}
```

Refactored situation:
```ts
@Entity()
@Unique({ properties: ['date', 'community'] })
class CoronaData extends BaseEntity<CoronaData, 'id'> {
  constructor(coronaInfo : CoronaInfo) {
    super();
    this.community = coronaInfo.Municipality_name;
    this.totalReported = coronaInfo.Total_reported;
    this.deceased = coronaInfo.Deceased;

    this.date = new Date(coronaInfo.Date_of_publication);
  }

  @PrimaryKey()
  id!: number;

  @Property()
  date!: Date;

  @Property()
  community!: string;

  @Property()
  totalReported!: number;

  @Property()
  deceased!: number;
}
```

With the generated migration looking like this
```ts
import { Migration } from '@mikro-orm/migrations';

export class Migration20220519103746 extends Migration {

  async up(): Promise<void> {
    this.addSql('create index "user_birthday_index" on "user" ("birthday");');

    // See here for instance
    this.addSql('alter table "user_corona_regions" drop constraint "userRegion";');
    this.addSql('alter table "user_corona_regions" drop constraint "userregion";');
    this.addSql('alter table "user_corona_regions" add constraint "user_corona_regions_user_id_region_unique" unique ("user_id", "region");');

    this.addSql('drop index "guild_user_guild_id_index";');
    this.addSql('drop index "guild_user_user_id_index";');

    this.addSql('alter table "quote" alter column "text" type varchar(2000) using ("text"::varchar(2000));');

    this.addSql('alter table "temp_channel" alter column "channel_id" type varchar(255) using ("channel_id"::varchar(255));');
    this.addSql('alter table "temp_channel" alter column "name" type varchar(98) using ("name"::varchar(98));');

    // And here is from the example
    this.addSql('alter table "corona_data" drop constraint "dateCommunity";');
    this.addSql('alter table "corona_data" drop constraint "datecommunity";');
    this.addSql('alter table "corona_data" add constraint "corona_data_date_community_unique" unique ("date", "community");');
  }

  async down(): Promise<void> {
    // It also tries to add the constraint twice once you drop the migration
    this.addSql('alter table "corona_data" add constraint "dateCommunity" unique ("date", "community");');
    this.addSql('alter table "corona_data" drop constraint "corona_data_date_community_unique";');
    this.addSql('alter table "corona_data" add constraint "dateCommunity" unique ("date", "community");');

    this.addSql('create index "guild_user_guild_id_index" on "guild_user" ("guild_id");');
    this.addSql('create index "guild_user_user_id_index" on "guild_user" ("user_id");');

    this.addSql('alter table "quote" alter column "text" type varchar using ("text"::varchar);');

    this.addSql('alter table "temp_channel" alter column "channel_id" type varchar using ("channel_id"::varchar);');
    this.addSql('alter table "temp_channel" alter column "name" type varchar using ("name"::varchar);');

    this.addSql('drop index "user_birthday_index";');

    this.addSql('alter table "user_corona_regions" add constraint "userRegion" unique ("user_id", "region");');
    this.addSql('alter table "user_corona_regions" drop constraint "user_corona_regions_user_id_region_unique";');
    this.addSql('alter table "user_corona_regions" add constraint "userRegion" unique ("user_id", "region");');
  }

}
```

**Stack trace**
```
DriverException: alter table "user_corona_regions" drop constraint "userregion"; - constraint "userregion" of relation "user_corona_regions" does not exist
```

**Expected behavior**
For only the correct constraint drop to be generated

**Versions**

| Dependency | Version |
| - | - |
| node | v18.1.0 |
| typescript | 4.6.4 |
| mikro-orm | 5.1.3 |
| postgresql (the driver) | 5.1.3 |

**Comment by B4nan** [comment] 2022-05-19 11:20
> Since v5 I cannot use two Properties with the same unique name to create a shared unique constraint

This was never supposed to be supported, your previous entity definition literally means "create two indexes with same name", that is not a compound index definition, its two separate and conflicting indexes - so it kinda makes sense there are two drop queries. What is weird that it even allowed you to have such entity definition in the first place, you should not be able to migrate to that state, are you sure you did not modify your migration before to even be able to get here? 

I am not sure if there is something to fix here, the drop queries are coming from what you had in your database schema, or in the schema snapshot generated from it - those are both dynamic things dependent on your environment.

When I tried to reproduce, your previous entity definition would produce two queries for the index (as expected), both with exact same name (same case). When executing, this obviously fails as we try to create the same index again. If I try to use `dateCommunity` for one and `datecommunity` for the other in the original entity description, the migration is correctly generated and both drop index queries succeed (as index names are case sensitive, so its valid to have those two).

I will close this, my bet is your migration snapshot was invalid because you made some changed directly do the database, not via the ORM migrator.

<details>
<summary>Here is the test case</summary>

```ts
import { Entity, Property, MikroORM, PrimaryKey, Unique } from '@mikro-orm/core';

@Entity({ tableName: 'a' })
class A1 {

  @PrimaryKey()
  id!: number;

  @Property({ unique: 'dateCommunity' })
  date!: Date;

  @Property({ unique: 'datecommunity' })
  community!: string;

}

@Entity({ tableName: 'a' })
@Unique({ properties: ['date', 'community'] })
class A2 {

  @PrimaryKey()
  id!: number;

  @Property()
  date!: Date;

  @Property()
  community!: string;

}

test('GH issue 3126', async () => {
  const orm = await MikroORM.init({ dbName: 'mikro_orm_test_3126', type: 'postgresql', entities: [A1] });
  await orm.getSchemaGenerator().ensureDatabase();
  await orm.getSchemaGenerator().dropSchema();
  const diff0 = await orm.getSchemaGenerator().getUpdateSchemaSQL({ wrap: false });
  expect(diff0).toMatchSnapshot();
  await orm.getSchemaGenerator().execute(diff0);

  orm.getMetadata().reset('A1');
  await orm.discoverEntity(A2);
  const diff1 = await orm.getSchemaGenerator().getUpdateSchemaSQL({ wrap: false });
  expect(diff1).toMatchSnapshot();
  await orm.getSchemaGenerator().execute(diff1);
  await orm.close();
});
```
</details>

**Closed by B4nan** 2022-05-19 11:20 UTC
