### ISSUE TITLE
More duplicate joins / unnecessary public schema usage

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#5019] opened 2023-12-14 11:38 UTC
### Describe the bug

In the following example it joins `site_sports` twice:

```ts
const sports = await orm.em.fork().find(Sport, { sites: 1 }, { populate: ["sites:ref"] });
[query] select "s0".*, "s1"."sport_id" as "s1__sport_id", "s1"."site_id" as "s1__site_id" from "sport" as "s0" left join "site_sports" as "s1" on "s0"."id" = "s1"."sport_id" left join "site_sports" as "s2" on "s0"."id" = "s2"."sport_id" where "s2"."site_id" = 1 [took 1 ms, 4 results]
```

Here it joins `site_sports` twice: once from "site_sports" and the second time from "public"."site_sports". It also joins `site` from "public"."site" instead of "site":
```ts
const sports = await orm.em.fork().find(Sport, { sites: 1 }, { populate: ["sites"] });
[query] select "s0".*, "s1"."id" as "s1__id", "s1"."created_at" as "s1__created_at", "s1"."updated_at" as "s1__updated_at", "s1"."name" as "s1__name", "s1"."location_id" as "s1__location_id", "s1"."cover" as "s1__cover" from "sport" as "s0" left join "site_sports" as "s2" on "s0"."id" = "s2"."sport_id" left join "public"."site" as "s1" on "s2"."site_id" = "s1"."id" left join "public"."site_sports" as "s3" on "s0"."id" = "s3"."sport_id" where "s3"."site_id" = 1 [took 1 ms, 4 results]
```

Here it joins `site` from "public"."site" instead of "site":
```ts
const sports = await orm.em.fork().find(Sport, { id: 1 }, { populate: ["sites"] });
[query] select "s0".*, "s1"."id" as "s1__id", "s1"."created_at" as "s1__created_at", "s1"."updated_at" as "s1__updated_at", "s1"."name" as "s1__name", "s1"."location_id" as "s1__location_id", "s1"."cover" as "s1__cover" from "sport" as "s0" left join "site_sports" as "s2" on "s0"."id" = "s2"."sport_id" left join "public"."site" as "s1" on "s2"."site_id" = "s1"."id" where "s0"."id" = 1 [took 2 ms, 2 results]
```

### Reproduction

Let me know if it's needed.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

v6

### Node.js version

20

### Operating system

Linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment] 2023-12-14 12:04
> Let me know if it's needed.

It's clear enough, but it would be good to use some existing entities from the tests, so it's clearer (or provide the definitions in the issue description). Ideally the `Author/Book/BookTag` example (author has 1:m books, book has m:n tags).

> unnecessary public schema usage

There are some internal places where things can break if the schema is not there iirc, this feels more like a cosmetic issue rather than an actual problem, I will see if its an easy fix, but its not important.

**Comment by darkbasic** [comment] 2023-12-14 12:27
> But reading this, it feels like we might fix both problems by removing the public schema from it...

That's exactly what I was meaning, even though the first example still has duplicate joins despite no public schema is being used.

**Comment by B4nan** [comment] 2023-12-15 22:39
this should be now resolved via 6ccfde0f1, the problem was the select-in fallback which technically always happen, and it wasnt respecting the `ref` hint (and saw not fully populated collection, so it did its job and populated it)

**Comment by B4nan** [comment] 2023-12-15 22:41
actually nope

**Comment by B4nan** [comment] 2023-12-15 23:04
actually yes, i am not able to reproduce this, will close with a passing test case - i just confused myself with a default filter which caused the second join for me (and that is correct behaviour, it should have its own join branch which only affects the root entity where, not the populate part). maybe same is happening for you? either way, if its still valid, lets reopen with a complete repro

**Comment by B4nan** [comment] 2023-12-15 23:06
ups, wrong issue number, but here is the commit https://github.com/mikro-orm/mikro-orm/commit/1ca683149250e18186b0b9d6450ac607d44056c9

**Comment by darkbasic** [comment] 2023-12-16 09:55
None of the previous examples has been fixed as of dev.273. I will provide a failing test.

**Comment by B4nan** [comment] 2023-12-16 10:02
Id really appreciate if we **reopen with failing test**, not reopen and **wait for the failing test** :]

**Comment by B4nan** [comment] 2023-12-19 19:05
This is correct behavior, one branch is for select, and one is for where query, as by default, `populateWhere` is set to `all` - the where condition does not apply to the populated relations.

**Closed by B4nan** 2023-12-19 19:05 UTC
