### ISSUE TITLE
Cannot populate on before/afterDelete method

### ISSUE THREAD

**Issue by abelland** [mikro-orm/mikro-orm#3719] opened 2022-11-09 17:38 UTC
**Describe the bug**
unable to populate M:1 relation on event subscriber's before/afterDelete if the child entity is removed from the parent collection (i know it's a bit tricky and this could easily be achieved by `em.remove(childEntity)`)

```
parent.childs.remove(child)
await this.em.flush();
```

**To Reproduce**
look at this repo (not the title since it was related to another issue) -> https://github.com/abelland/afterflush-populate
steps to reproduce the error are described in README file

**Expected behavior**
just having M:1 relation populated

**Additional context**
On mikro-orm v5.4 populate works as expected

**Versions**

| Dependency | Version |
| - | - |
| node | 14.20 or 16.10 |
| typescript | 4.6.3 |
| mikro-orm | 5.5.1 or 5.5.2 |
| your-driver | sqlite or postgres |

**Comment by B4nan** [comment] 2022-11-09 18:00
Simpler repro would be welcome, you dont need a complex web app to reproduce this... 

I hope you understand this is usually putting an extra hour of work for me to simplify things before I can even start debugging them.

**Comment by B4nan** [comment] 2022-11-09 18:03
Duplicate of #3687

**Closed by B4nan** 2022-11-09 18:03 UTC

**Comment by abelland** [comment] 2022-11-09 18:07
🙏
