### ISSUE TITLE
Creating a Postgres database fails since 5.5.3

### ISSUE THREAD

**Issue by briandiephuis** [mikro-orm/mikro-orm#3769] opened 2022-11-17 09:58 UTC
**Describe the bug**
Creating a Postgres database fails since 5.5.3. Since this [change](https://github.com/mikro-orm/mikro-orm/compare/v5.5.2...v5.5.3#diff-f664d33b3110fda8f3c4456b132180636ea807b7602e9ebd7270889ddde3ed82) our tests no longer run. In our integration tests we create a new database for just those tests, unfortunately automatically creating the database no longer works.

If we revert this method (manually in `node_modules/@mikro-orm/postgresql/PostgreSqlSchemaHelper.js`), everything works as expected: 
````
  getManagementDbName(): string {
    return undefined; // instead of ''
  }
````

Not sure why though 🤔 

**Stack trace**
```
DriverException: database "{ database username }" does not exist
```

*note that it logs the database username instead of the dbName 🤷 

**To Reproduce**
1. Set config to a non-existing `dbName`
2. Start app
3. Unable to create dbName

**Expected behavior**
Mikro-ORM should correctly create the desired database and connect to it.

**Additional context**
Connecting to an existing database works just fine.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 4.8.4 |
| mikro-orm | 5.5.3 |
| @mikro-orm/postgresql | 5.5.3 |

**Comment by B4nan** [comment] 2022-11-17 10:04
I've been fixing this 3 times already, I can't help without a complete reproduction, as I would almost certainly break something else (not to mention I have no idea how I would reproduce this).

Closing before you provide one.

**Comment by B4nan** [comment] 2022-11-17 10:06
Start with providing complete ORM config - and I really mean complete, no blank spaces and variables, I need all the actual values (mangled of course, I dont care about your user/pass/host, but I need to see exact values that reproduce this).

**Comment by B4nan** [comment] 2022-11-17 10:16
Also, are you using env vars? Client URL (connection string)? Any special characters (namely `:`) in your username/password?

**Comment by briandiephuis** [comment] 2022-11-17 10:18
Ok, thanks for the quick reply! I'll provide more info soon.

**Comment by briandiephuis** [comment] 2022-11-17 13:34
@B4nan I've created this repo with a minimal setup -that represents what we use as much without too much bloat- to reproduce the bug. Let me know if this is too much or if you need anything else! The readme shows how to reproduce it in 5.5.2 and 5.5.3.

https://github.com/briandiephuis/nestjs-mikro-orm-example

**Comment by briandiephuis** [comment] 2022-11-17 13:59
+ any feedback on our test-setup is much appreciated ;)

**Comment by B4nan** [comment] 2022-11-17 14:16
Hmmm looks like postgres requires the database name, and defaults to the user name when it is not present. Will need to revert the changes and allow overriding the management db name for those who dont have the `postgres` database.

**Closed** 2022-11-17 15:30 UTC
Labels: bug
