### ISSUE TITLE
Enum values are not updated when changed

### ISSUE THREAD

**Issue by Luxiorawa** [mikro-orm/mikro-orm#3955] opened 2023-01-17 11:26 UTC
**Describe the bug**

When defining and using an enum in Entity like this one : 

```ts
@Entity({ tableName: 'foo' })
export class Foo {
  @PrimaryKey()
  public id: number;

  @Enum({ items: () => FooTypes })
  public type: FooTypes;
}
```

If i update (add a value, change a value, or even delete one) in my enum that is like this : 

```ts
export enum FooTypes {
  A = 'A',
  B = 'B',
  C = 'C'
}
```

Nothing is taken into account. Whether i use schema:update, schema:fresh or even create a migration with migration:create, my changes are not detected. 

The only thing that worked, was change the column type, like make it a VARCHAR and reverted it back to the initial Enum it was, and it sucessfully updated.

**To Reproduce**

I created a [repository](https://stackblitz.com/edit/mikro-orm-repro-kyifxa?file=index.ts) so that you can better understand the issue, unfortunately i would like to keep a mysql database since it may come from here as well. So you would need to input a real database in the repro unfortunately. 

**Expected behavior**

Enum values should be updated in the database properly

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.0 |
| typescript | 4.8.4 |
| mikro-orm | 5.6.2 |
| mikro-orm/mysql | 5.6.2 |
| nest-js | 9.2.1 |

**Comment by B4nan** [comment] 2023-01-17 11:50
Not reproducible on my end, tried with mysql driver, and it correcly detects the change. Here is a passing test case, lets reopen with a failing one.

```ts
import { Entity, Enum, PrimaryKey } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/mysql';

enum FooTypes {
  A = 'A',
  B = 'B',
  C = 'C',
}

enum FooTypes2 {
  A = 'A',
  B = 'B',
}

@Entity({ tableName: 'foo' })
class Foo {

  @PrimaryKey()
  id!: number;

  @Enum({ items: () => FooTypes })
  type!: FooTypes;

}

@Entity({ tableName: 'foo' })
class Foo2 {

  @PrimaryKey()
  id!: number;

  @Enum({ items: () => FooTypes2 })
  type!: FooTypes2;

}

test('enum diffing with case sensitive column names (GH issue #2938)', async () => {
  const orm = await MikroORM.init({
    entities: [Foo],
    dbName: `mikro_orm_test_enum1`,
    port: 3308,
  });
  // create schema with Foo and FooTypes
  await orm.schema.refreshDatabase();

  // mimic change on the Foo entity to use FooTypes2
  await orm.discoverEntity(Foo2);
  orm.getMetadata().reset('Foo');
  const diff1 = await orm.schema.getUpdateSchemaSQL({ wrap: false });
  expect(diff1).toMatch("alter table `foo` modify `type` enum('A', 'B') not null;");
  await orm.schema.execute(diff1);

  await orm.close(true);
});
```

Note that I used mysql as well as tried this in the realworld example app (so a nestjs project), same outcome, no issues on my end. I guess you are oversimplifying?

**Comment by Luxiorawa** [comment] 2023-01-17 12:15
Maybe i explained badly, but what i mean by changing the enum is changing it's values. Like changing the file foo.enum.ts from 

```
enum FooTypes {
  A = 'A',
  B = 'B',
  C = 'C',
}
```

to 

```
enum FooTypes {
  A = 'A',
  B = 'B'
}
```

And i expect the database to receive this change. I say that because in your above example you are creating 2 entities, with 2 different enums.

**Comment by Luxiorawa** [comment] 2023-01-17 13:59
Okay so @B4nan i tried to play around a bit, and it seems that it successfully understand the enum modification if you create a new enum containing the changes. So doing this for example

```
export enum OldFooTypes {
  A = 'A',
  B = 'B'
}
```

```
export enum NewFooTypes {
  A = 'A',
  B = 'B',
  C = 'C'
}
```

Works, maybe because it somehow detect that the type changed.

But if you use the same enum file, and just change it's values, i think you will have the same issue.

**Comment by Luxiorawa** [comment] 2023-01-19 00:03
Should i create another tickets with the latest infos i got ? (i mean, my latest comment)

**Comment by B4nan** [comment] 2023-01-22 21:09
> Maybe i explained badly, but what i mean by changing the enum is changing it's values. Like changing the file foo-types.enum.ts from

I did understand fully, and I did test it exactly that way in the [realworld example project](https://github.com/mikro-orm/nestjs-realworld-example-app) - it works just fine there.

I don't want more tickets, I want complete reproduction that fails, then we can reopen this one.

**Comment by Luxiorawa** [comment] 2023-01-23 04:59
So, i'll include full pictures of what i did just to be sure. Because i also did the same things on the same project as you, [realworld example project](https://github.com/mikro-orm/nestjs-realworld-example-app) (that i forked), and i have the same issue.

Here is what i did in my [fork](https://github.com/Luxiorawa/nestjs-realworld-example-app) :

- 2 npm script to update my database schema, and to generate a migration file
- an enum on User that is named UserTypes

My first enum values were as in the last commit, like this : 

```ts
export enum UserTypes {
  A = 'A',
  B = 'B',
  C = 'C',
}
```

I then execute my script to update the schema, and so far everything works. As you can see in the following screen my enum is there, and can be changed / used..etc

![image](https://user-images.githubusercontent.com/90514525/213968451-183adb08-9e63-4cca-8c48-67485eb25a0e.png)

But if i change the same file, that is, the same enum, but i only change it's values, so that means instead of having the previous enum, i have now the following : 

```ts
export enum UserTypes {
  A = 'A',
  B = 'B'
}
```

Now doing schema:update update nothing as you can see

**Comment by B4nan** [comment] 2023-01-23 08:09
Ok, the problem is indeed in the enum being defined in an external file, weird but I got it reproduced and that's what matters :]

**Comment by Luxiorawa** [comment] 2023-01-23 08:58
Yes I also use that in my own project, and since when you tested in a single file you had no problem it seems to come from here. I see that TsMorphMetadataProvider has a `useCache()` method, is there a way do disable metadata cache ? To let you time to investigate more into this

**Comment by B4nan** [comment] 2023-01-23 09:14
https://mikro-orm.io/docs/metadata-cache

**Comment by B4nan** [comment] 2023-01-24 23:41
The problem here is that the cache is not invalidated automatically - as that is driven by the hash of contents of your entity definition file, and that is not changed when you define the enum outside of it.

This is one of the cases where manual clear is required, you can do that by calling `npx mikro-orm cache:clear` or simply by wiping the temp folder via `rm -rf temp`. I will close this as wontfix, I don't think that we can do much about it (not without rather complex hashing of the whole graph of files based on imports, which could end up being quite expensive).

**Comment by B4nan** [comment] 2023-01-24 23:45
Actually, I might have a way to do this, let me give it a quick try.

**Comment by B4nan** [comment] 2023-01-24 23:52
I don't have an easy way to unit test this, but it should help.

**Comment by Luxiorawa** [comment] 2023-01-30 17:17
@B4nan I updated to the last version, and it works perfectly ! 

Maybe change this ticket status to "Clossed issue" ? Since you tagged it as "Not planned" few days ago, but it got pushed into master, so it may be confusing.

**Closed** 2023-01-30 17:20 UTC
Labels: bug

**Comment by danikane** [comment] 2025-01-09 00:31
Hi, sorry I'm chiming in on a closed issue. My 2 cents:
- my Enum is in the same file
```
enum MyType {
  A: 'A',
  B: 'B',
}
```

- `migration:create` then `migration:fresh` 
- I add an entry to the Enum so now it's:
```
enum MyType {
  A: 'A',
  B: 'B',
  C: 'C',
}
```
- it's not detected
- clearing/deleting cache ❌ 
- deleting snapshot in migrations folder ✔️ 

Thanks! I might switch of snapshots entirely or delete the snapshot as part of package.json scripts.
Reference: https://mikro-orm.io/docs/migrations#snapshots
