### ISSUE TITLE
Many-To-One relationships sometimes fail to populate

### ISSUE THREAD

**Issue by cfraz89** [mikro-orm/mikro-orm#533] opened 2020-05-01 19:18 UTC
**Describe the bug**
In my app, I have a many-to-one property, which is listed in the populate column. However the resulting property is not loaded.

I have made a sort-of reproduction of this case, where a property is not populated. However the cause of this issue seems to be somewhat different. In the production code, EntityLoader.populateMany() successfuly loads the child property, but fails to merge it into the parent. In this reproduction, the property is not even found, unless the entity was loaded with a .find() previously.

**To Reproduce**
1. Clone `git@github.com:cfraz89/nestjs-realworld-example-app.git`
2. Set up as per original example:
  2.1. `yarn install`
  2.2. copy `src/micro-orm.config.example.ts` to `src/micro-orm-config.ts`  and modify with db connection details.
  2.3 copy `src/config.ts.example` to `src/config.ts`
  2.4. `npx mikro-orm:schema-generate --run`
  2.5. `yarn start`
3. Run ` curl -X POST localhost:3000/api/tagging/setup`. It will create some necessary entities, and output their ids. 
Eg `{"userId":1,"articleId":1,"tagId":1}`
4. Run `curl -X POST "localhost:3000/api/tagging/tag?tag=<tagId>&user=<userId>&article=<articleId>" ` substituting in the ids from previously. 
Eg ` curl -X POST "localhost:3000/api/tagging/tag?tag=1&user=1&article=1" `
You will receive an output like `{"taggings":[{"id":1,"tag":"1","addedBy":"1","article":"1"}]}`. Notice that here, article was supposed to be populated, but wasn't.
5. Now run step 4 with the extra parameter `findArticleFirst=true`.
Eg ` curl -X POST "localhost:3000/api/tagging/tag?tag=1&user=1&article=1&findArticleFirst=true" `
This does an explicit findOne() before the result query.
Notice that this cause the `articles` property to be populated, although I don't believe it should have been necessary. 

**Expected behavior**
Article is populated. Instead, only its id is returned.

**Versions**
| Dependency | Version |
| - | - |
| node | 14.1.0 |
| typescript | 3.8.3 |
| mikro-orm | 3.6.11 |
| pg | 8.0.3 |

**Comment by B4nan** [comment] 2020-05-02 23:02
> EntityLoader.populateMany() successfuly loads the child property, but fails to merge it into the parent.

Not really, it actually creates wrong query when loading the children (articles):

`select `e0`.* from `article` as `e0` where 0 = '1' and `e0`.`id` in ('1') order by `e0`.`id` asc`

That `0 = '1'` part always evaluates to false so it fails to fetch the articles.

Will try to fix that soon. As a workaround, you can do this:

`const taggings = await this.taggingRepository.find({article: { id:  articleId }}, {populate: ['article']})`

**Comment by cfraz89** [comment] 2020-05-03 06:38
Oh I was referring to my production code, which I haven't been able to replicate perfectly. This issue was the closest I could get to replicating it. Although the setup was quite similar, the outcome was different, with the reproduction failing to load an article from the db at all (due to the incorrect query). In my original code though, it loaded the data, but didn't merge it in. I ended up rewiring things anyway though, which skirted that issue. Regardless, glad that this is found :)

**Comment by B4nan** [comment] 2020-05-03 08:07
> In my original code though, it loaded the data, but didn't merge it in.

Are you sure it really wasn't merged, or was this discrepancy visible only on the API response? It could be caused by lazy population if its just about the serialized response. 

```typescript
const books = await em.find(Book, {});
const author = await em.findOne(Author, books[0].author);
console.log(JSON.strinfigy(books)); // here the author is not marked as populated so you will get just the id in response

wrap(author).populated();
console.log(JSON.strinfigy(books)); // now it will be there, even though you might have inconsistent response (only one author being popolated)
```

**Comment by B4nan** [comment] 2020-05-03 08:52
Ok so the whole problem of your reproduction code is that you though nest will convert query params to numbers for you, but it does not. 

All of `tagId`, `userId` and `articleId` are in fact strings, but you work with them as with numbers, which breaks the queries. 

```diff
-const taggings = await this.taggingRepository.find({article: articleId}, {populate: ['article']})
+const taggings = await this.taggingRepository.find({article: +articleId}, {populate: ['article']})
```

**Closed** 2020-05-03 09:42 UTC
Labels: bug

**Comment by cfraz89** [comment] 2020-05-10 12:59
Ah well thats silly. At least in the production code I'm using a graphQL api, so the types are good there. 

I am in fact using Promise.all... I'll try removing that.

**Comment by cfraz89** [comment] 2020-05-10 13:29
Ok I've found the critical difference that causes the failure in the production code.

`  
const tagging = this.taggingRepository.create({
  addedBy: user.id,
  tag,
  rateable: rateableId,
});
this.taggingRepository.persist(tagging);
`
Results in retrieving the tagging to have uninitialized `addedBy` after population.

However
`
const tagging = new Tagging();
wrap(tagging).assign(
      {
        addedBy: user.id,
        tag,
        rateable: rateableId,
      },
      { em: this.entityManager },
    );
    this.taggingRepository.persist(tagging);
`

Results in a fully-populated `addedBy` after looking it up.

Should there be this difference?

**Comment by B4nan** [comment] 2020-05-11 07:01
That highly depends on the context, both behaves the same if you pass there reference id (as you do), both will use `em.getReference()` to create actual reference managed by given entity manager. But here I believe you are talking about the JSON response from the API, not about what is actually present on the entity (e.g. when using console.log or debugger), right? 

Because you are not populating `addedBy` anywhere. If you want to have it as part of the JSON response, you need to either populate it via populate API or mark it as populated via `wrap(user).populated()` (if you load it separately, e.g. via some auth middleware). If the entity is already loaded, population process will not repopulate it, but it will mark it this way for you. 

This is done like this because in 99% you don't want to have those "separately loaded" entities actually populated, as it could lead to unstable API response. Imagine you will return a list of books, with not populated authors. But one of the authors will be the user whose token was used to get the response - so that entity would be loaded from db. And you would end up with list of books, where only this particular user/author would be fully populated, but others not (so they would have just the PK).
