### ISSUE TITLE
Cannot read properties of undefined (reading 'name') caused by commit 8d819856d488668b81a187d6335997baab2e075c

### ISSUE THREAD

**Issue by tvacherat** [mikro-orm/mikro-orm#6118] opened 2024-10-07 08:42 UTC
### Describe the bug

Commit 8d819856d488668b81a187d6335997baab2e075c (v6.3.12) causes an access problem to constructor.name in packages/core/src/utils/clone.ts line 92.
Here's the stack trace I got from my logs:
[
  "TypeError: Cannot read properties of undefined (reading 'name')\n" +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:78:94)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)\n' +
    '    at _clone (/var/app/current/node_modules/@mikro-orm/core/utils/clone.js:126:24)',
  'ExceptionsHandler'
]

### Reproduction

Since the source of the bug is obvious and I haven't managed to reproduce it, I haven't set up a repo for it.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

v6.3.12

### Node.js version

Node.js 20

### Operating system

64bit Amazon Linux 2023/6.2.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment] 2024-10-07 08:46
> Since the source of the bug is obvious and I haven't managed to reproduce it, I haven't set up a repo for it.

No, it's not obvious. Closing as not reproducible, let's reopen with a complete reproduction.

**Closed by B4nan** 2024-10-07 08:46 UTC

**Comment by tvacherat** [comment] 2024-10-07 08:54
I apologize for the lack of reproduction. This problem is hidden in a complex sequence of processes. I don't have the time right now, but I'll try to reproduce it as soon as possible. At least you know something's wrong here.

**Comment by B4nan** [comment] 2024-10-08 16:03
FYI I've reverted those changes since they are no longer needed thanks to #6091.
