### ISSUE TITLE
v6 - Partial loading / joins always giving "type string is not assignable to type never" error

### ISSUE THREAD

**Issue by chrisbenincasa** [mikro-orm/mikro-orm#5104] opened 2024-01-09 15:59 UTC
### Describe the bug

Partial selection and relation selection are giving me type errors after bumping from v5 => v6. I've attempted using code from docs and have a simple reproduction (below). 

This happens when working with the EntityManager directly and when using a repository

### Reproduction

Entity:
```typescript
@Entity()
export class Test {
  @PrimaryKey()
  id: string = v4();

  @Property()
  prop1!: string;
}
```

Selection code:
```typescript
await getEm().findAll(Test, {
    fields: ['id'],
});
```

Result:
<img width="495" alt="Screenshot 2024-01-09 at 10 56 15 AM" src="https://github.com/mikro-orm/mikro-orm/assets/1640671/869d2822-f6fe-45d4-8e78-24f921cfd385">

Manually adding the entity type as the first parameter gives something closer...
```typescript
await getEm().findAll<Test>(Test, {
      fields: ['id'],
});
```
<img width="459" alt="Screenshot 2024-01-09 at 10 57 46 AM" src="https://github.com/mikro-orm/mikro-orm/assets/1640671/2f28e432-dddd-4011-b36f-f4a9bb9ac36c">

### What driver are you using?

None

### MikroORM version

6.0.1

### Node.js version

18.18.0

### Operating system

Mac OS Sonoma 14.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment] 2024-01-09 16:02
I am not able to reproduce this, please provide complete reproduction. 

This code works fine for me:

<img width="293" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/615580/dc614fa6-bba9-4519-bdec-b453684f8816">

**Comment by chrisbenincasa** [comment] 2024-01-09 16:06
The same exact code in a single file does not work for me:

```typescript
import { BetterSqliteDriver, MikroORM } from '@mikro-orm/better-sqlite';
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { v4 } from 'uuid';

@Entity()
export class Test {
  @PrimaryKey()
  id: string = v4();

  @Property()
  prop1!: string;
}

const orm = MikroORM.initSync<BetterSqliteDriver>({
  dbName: 'test.sql',
  baseDir: __dirname,
  entities: [Test],
  forceUndefined: true,
});

orm.em.findAll(Test, {
  fields: ['id']
})
```
<img width="939" alt="Screenshot 2024-01-09 at 11 06 43 AM" src="https://github.com/mikro-orm/mikro-orm/assets/1640671/fc8e73df-e4af-497e-819c-42aa6ba3bb7d">

**Comment by chrisbenincasa** [comment] 2024-01-09 16:12
What version of Typescript are you running?

I just verified that reverting to 5.2.2 or 5.3.3 fixes the issue for me, but 5.4.0-dev versions are broken.

**Comment by B4nan** [comment] 2024-01-09 16:21
Yeah, I can reproduce with the dev one. One would expect you mention you use unreleased versions of anything right ahead :]

So closing for now as it's about the dev version, I won't be dealing with TS 5.4 support before it gets released to stable, as this could be just something they will fix before it happens and not a problem in the ORM code. Let's reopen if it's still valid then.

**Closed by B4nan** 2024-01-09 16:21 UTC
Labels: needs clarification

**Comment by chrisbenincasa** [comment] 2024-01-09 16:23
That was my fault, I was certain I had VSCode set to use the workspace's TS version. Thanks!

**Comment by B4nan** [comment] 2024-01-09 16:26
I really hope this is just some glitch on their end. The problem is the inference on the `fields` (as well as `populate` and `exclude`) option is not working, so you get the default type value, which is `*`.

<img width="940" alt="image" src="https://github.com/mikro-orm/mikro-orm/assets/615580/a5cc116e-c13a-4149-bde7-7d8caea8cbab">

The types are pretty complex, I had a hard time making it work already 😭

**Comment by chrisbenincasa** [comment] 2024-01-09 16:27
Yea I spent a buncha time unfurling the type before opening the issue and could tell a lot of thought/work was put into them! Definitely seems like a regression; hopefully it doesn't make it into the stable release.

**Comment by B4nan** [comment] 2024-02-01 11:09
This should help #5197, there will be more small changes required to the codebase before the TS 5.4 update, but the populate hints should be working fine already.
