### ISSUE TITLE
json columnType data are automatically casted to jsonb in Postgres

### ISSUE THREAD

**Issue by sebapatr96** [mikro-orm/mikro-orm#4573] opened 2023-08-01 12:46 UTC
**Describe the bug**
When I use `json` value for `columnType` property of `@Property` decorator option in entity definition class, mikro-orm automatically typecasts inserted data via `::jsonb`. Is this intentional? I use `json` postgres type specifically to avoid json properties reordering of jsonb type, but thanks to automatic jsonb typecast the properties are still being reordered.

The workaround for this is not using columnType option at all, and instead use just `type: JsonType`.

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.7.10 |

**Comment by sebapatr96** [comment] 2023-08-01 12:59
Sure. If I have entity definition like this

```typescript
@Entity()
export class Book {
  @Property({ type: 'json', nullable: true })
  meta?: { foo: string; bar: number };
}
```

Mikro autocasts inserted data via `::jsonb`

But if I keep it like this, it won't typecast to `::jsonb`
```typescript
@Entity()
export class Book {
  @Property({ type: JsonType, nullable: true })
  meta?: { foo: string; bar: number };
}
```

Or am I doing something wrong?

**Comment by B4nan** [comment] 2023-08-01 13:19
Well, it does not behave like that, we have tests for those cases, `type: 'json'` and `type: JsonType` is exactly the same thing, those are alternative ways to do the same, unlike the `columnType` option which serves as a way to override the default mappings. Are you on latest already?

If you pass a known mapping from [those](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/types/index.ts#L41) to the `type` option as a string, it will be used. And both of those will default to `jsonb` column in schema generator. You are mentioning `::jsonb` which is casting, so you are probably not talking about schema generation. That's why I am asking for reproduction, not entity definition, show me what you are doing.

**Comment by B4nan** [comment] 2023-08-01 13:31
I think I understand what you are talking about. There is [this line](https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlPlatform.ts#L276) which is probably causing it. I've already [refactored this away in v6](https://github.com/mikro-orm/mikro-orm/blob/v6/packages/postgresql/src/PostgreSqlPlatform.ts#L295).

I will close this, as the problem is no longer present in v6, just verified in [this test case](https://github.com/mikro-orm/mikro-orm/blob/v6/tests/features/custom-types/json-properties.test.ts#L23-L24). 

I won't be backporting things at this stage, if this is a problem for you, I'd suggest giving v6 a try. Upgrading guide is [here](https://github.com/mikro-orm/mikro-orm/blob/v6/docs/docs/upgrading-v5-to-v6.md).

**Comment by sebapatr96** [comment] 2023-08-01 13:38
> I think I understand what you are talking about. There is [this line](https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlPlatform.ts#L276) which is probably causing it. I've already [refactored this away in v6](https://github.com/mikro-orm/mikro-orm/blob/v6/packages/postgresql/src/PostgreSqlPlatform.ts#L295).
> 
> I will close this, as the problem is no longer present in v6, just verified in [this test case](https://github.com/mikro-orm/mikro-orm/blob/v6/tests/features/custom-types/json-properties.test.ts#L23-L24).
> 
> I won't be backporting things at this stage, if this is a problem for you, I'd suggest giving v6 a try. Upgrading guide is [here](https://github.com/mikro-orm/mikro-orm/blob/v6/docs/docs/upgrading-v5-to-v6.md).

Yes this seems like the issue I was referring to. Thanks

**Comment by B4nan** [comment] 2023-08-01 13:52
Yeah closing again, this was removed as part of this commit, there were some bad rebases which caused some confusing history.

https://github.com/mikro-orm/mikro-orm/commit/9d2ccea2873babd4b438cfe1486ec6a263eeb109

**Closed by B4nan** 2023-08-01 13:52 UTC
