### ISSUE TITLE
MySQL generated migration not including Foreign Key changes

### ISSUE THREAD

**Issue by etienne-bechara** [mikro-orm/mikro-orm#633] opened 2020-07-01 22:56 UTC
**Describe the bug**

When using MySQL connection, any migrations that modifies foreign key behavior are not being generated correctly.

**To Reproduce**

1. Create two basic entities with `@ManyToOne` relationship:

```ts
@Entity()
export class User  {

  @Property()
  public name!: string;

  @ManyToOne()
  public team!: Team;

}

@Entity()
export class Team {

  @Property()
  public slug!: string;

}
```

2. Run schema create to see the foreign key successfully created:

```
npx mikro-orm schema:create -d

=== Output ===

create table `team` (`id` varchar(255) not null, `slug` varchar(255) not null) default 
character set utf8mb4 engine = InnoDB;
alter table `team` add primary key `team_pkey`(`id`);

create table `user` (`id` varchar(255) not null, `name` varchar(255) not null, `team_id` varchar(255) not null) default character set utf8mb4 engine = InnoDB;
alter table `user` add primary key `user_pkey`(`id`);
alter table `user` add index `user_team_id_index`(`team_id`);

alter table `user` add constraint `user_team_id_foreign` foreign key (`team_id`) references `team` (`id`) on update cascade;
```

3. Change the foreign key behavior on User entity:

```ts
@ManyToOne(() => Team, { nullable: false, onDelete: 'cascade' })
public team!: Team;
```

4. Run schema synchronization and see that it comes empty (not using cache):

```
npx mikro-orm schema:update -d

== Output ===

set names utf8mb4;
set foreign_key_checks = 0;

set foreign_key_checks = 1;
```

**Expected behavior**

The output above should be:

```
set foreign_key_checks = 0;

ALTER TABLE `user` DROP FOREIGN KEY user_fk;
ALTER TABLE `user` ADD CONSTRAINT user_fk FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE;

set foreign_key_checks = 1;
```

**Additional context**

It appears that there is something wrong with handling MySQL foreign keys in general, because if I manually drop the FK and try to recreate it with `schema:update` it creates only the index and not the constraint:

Behavior when manually deleting the FK and synchronizing again:

```
npx mikro-orm schema:update -d

=== Output ===
set names utf8mb4;
set foreign_key_checks = 0;

alter table `user` modify `team_id` varchar(255);
alter table `user` drop index `user_team_id_index`;
alter table `user` add index `user_team_id_index`(`team_id`);

set foreign_key_checks = 1;
```

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 3.6.15 |
| mysql2 | 2.1.0 |

**Comment by B4nan** [comment] 2020-07-02 15:31
Closing as duplicate of #579.

**Closed by B4nan** 2020-07-02 15:31 UTC
Labels: bug
