### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.ts for any query with $or and $and

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#208] opened 2019-10-17 13:28 UTC
**Describe the bug**

If i have any query with $and or $or condition like:

```
const reports = await em.find(
        Report,
        {
            $or: [{ title: 'asd' }, { name: 'asd' }],
        },
        {
            populate: ['organization']
        }
    );
```

I see typescript error

```
Type instantiation is excessively deep and possibly infinite.ts(2589)
```

**Versions**

3.0.0-alpha.29

**Comment by vimmerru** [comment] 2019-10-17 13:29
[mikro-orm-test.zip](https://github.com/mikro-orm/mikro-orm/files/3739523/mikro-orm-test.zip)

**Comment by B4nan** [comment] 2019-10-17 13:42
Interesting, this way it works:

```typescript
const cond = { $or: [{ title: 'asd' }, { name: 'asd' }] };
const reports = await em.find(Report, cond, ['organization']);
```

**Comment by vimmerru** [comment] 2019-10-17 13:46
It is because cond type isn't validated.

const cond: FilterQuery<Report> = { $or: [{ title: 'asd' }, { name: 'asd' }] };

will fail too

**Comment by B4nan** [comment] 2019-10-17 13:50
Maybe typescript 3.7 and its support for recursive type aliases will help with this. I think the `FilterQuery` definition is correct, but it is too complex for TS sometimes. If it would be the case, I am thinking about requiring TS 3.7 in MikroORM v3. 

> ...will fail too

Nope, it works ok for me (obviously you have to fill the generic parameter). Also tried to change `asd` to a number to see that it actually validates the thing.

I had to write it this way though, as there were some TS weirdness happening:

```typescript
const cond: FilterQuery<Report> = { $or: [{ title: 'asd' }, { name: 'asd' }] };
let reports: Report[];
reports = await em.find(Report, cond, ['organization']);
```

**Comment by vimmerru** [comment] 2019-10-17 14:01
Seems with ts 3.7 it works

**Comment by B4nan** [comment] 2019-10-17 14:05
Lol looks like the fix is simple as this (including older TS versions):

```typescript
const reports = await em.find<Report>(Report, { $or: [{ title: 'asd' }, { name: 'asd' }] }, ['organization']);
```

By specifying the generic parameter of `em.find` it correctly understands everything. The problem is most probably because it tries to find common denominator of both `entityName` and `where` parameters, as `T` is used in both of them.

**Comment by B4nan** [comment] 2019-10-17 14:06
I think I could solve this by adding second generic parameter so `T` will get inferred only from the `entityName` param.

**Comment by vimmerru** [comment] 2019-10-17 17:05
> I think I could solve this by adding second generic parameter so T will get inferred only from the entityName param.

It works for simple cases, but if move $or or $and a bit deeper the same error.

**Comment by B4nan** [comment] 2019-10-17 17:29
Then please provide example where it does not work.

**Comment by lookfirst** [comment] 2019-10-19 13:37
I am find with 3.7 requirement for v3. I even found a regression bug myself in the compiler while trying out `objection.js` before finding this project. Staying current with TS is great.

**Comment by jsprw** [comment] 2019-10-19 14:42
I am not fine with having a dependency on that version as it breaks support with Angular (3.5.3) then. Would rather not see it break support for such a small error (assumed functionality will not break, only types not shown properly). Maybe have a message saying you need typescript 3.7 to support this func?

**Comment by B4nan** [comment] 2019-10-19 15:08
I don't think there needs to be any breaking change even if we use internally TS 3.7, as the code you will be using will be the transpiled JS and not the source code, so unless we use some TS 3.7 feature in typings, it should be fine. 

I am still waiting for example of the failure, as for me it is working ok when I provide the type parameter explicitly.

**Comment by jsprw** [comment] 2019-10-19 17:14
No, but doesn’t it break when you specify typescript 3.5.3 in package.json (which is required for Angular) and MikroORM uses 3.7? It’s all in the same project.

**Comment by B4nan** [comment] 2019-10-19 17:15
But again, you are using the compiled code from ORM (plus the typings), the TS source code is not even part of the npm package.

**Comment by vimmerru** [comment] 2019-10-21 08:33
@B4nan I don't see cardinal difference between typescript 3.6.4 and 3.7 in behavior. The queries like 

```$or: [{ username: req.usernameOrEmail }, { email: req.usernameOrEmail }],```

require explicit providing of generic type on both versions. The cause is ts most probably can't infer entity type from 2 arguments and i don't know the way how to force ts use only first parameter for type inference. There are workarounds, but they will cause a lot of questions from new users. 

Maybe we can try tp create an issue in typescript repo and they can suggest some solution here.

**Comment by B4nan** [comment] 2019-10-21 08:41
So providing the generic type helps for you too? 

Yeah I was digging around and found some related issues. Unfortunately it is not possible to force inference from first parameter only. Workaround for that is currying, which is super ugly and nothing I would like to introduce to EM public API. 

I think we can live with the requirement for passing the generic type when this error occurs. Will state that in the docs somewhere. 

Maybe one more thing to verify - as this is about the inference of `T`, it should not be an issue with repositories API, where the type is explicitly provided one step above (so it is kinda same as using currying).

**Comment by vimmerru** [comment] 2019-10-21 16:49
> So providing the generic type helps for you too?

It helps. I am ok with this. In general i consider repositories as mostly redundant abstraction, but maybe it is a good reason to try them )

**Comment by B4nan** [comment] 2019-10-23 17:24
Added section about this to the docs: https://github.com/mikro-orm/mikro-orm/blob/dev/docs/entity-manager.md#mitigating-type-instantiation-is-excessively-deep-and-possibly-infinitets2589-error

So closing this as resolved.

**Closed by B4nan** 2019-10-23 17:24 UTC
Labels: bug, typing
