### ISSUE TITLE
When using Single Table Inheritance, child entities' classes will be the base class and not their concrete class in some cases.

### ISSUE THREAD

**Issue by rhyek** [mikro-orm/mikro-orm#2493] opened 2021-12-02 21:55 UTC
**Describe the bug**
When using Single Table Inheritance, child entities' classes will be the base class and not their concrete class in some cases.

You get the concrete child classes when loading the entities directly in a clean entity manager.

You get the super class when in a running entity manager you have loaded other entities that reference our STI super class and then you try to load the STI entites.

I have an example here:  https://github.com/rhyek/mikro-orm-single-table-inheritance-test

This code: https://github.com/rhyek/mikro-orm-single-table-inheritance-test/blob/main/nest-app/src/app.controller.ts#L25-L29
will always output:
```
[
  'BossEntity',
  'EmployeeEntity',
  'BossEntity',
] 
```
On the other hand, this code: https://github.com/rhyek/mikro-orm-single-table-inheritance-test/blob/main/nest-app/src/app.controller.ts#L32-L42
will always output:
```
[
  'PersonEntity',
  'PersonEntity',
  'PersonEntity',
] 
```

**To Reproduce**
Run tests in linked repository.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.1 |
| typescript | 4.4.4 |
| mikro-orm | 4.5.9 |
| your-driver | mysql |

**Comment by rhyek** [comment] 2021-12-02 22:41
I've managed to work around this "issue" by forking the entity manager. So this works:
```ts
  @Get('tasks-then-fork-em-then-persons')
  async getTasksThenForkEmThenPersons(): Promise<any> {
    const tasks = await this.tasksRepository
      .createQueryBuilder()
      .getResultList();
    const persons = await this.em
      .fork(true)
      .createQueryBuilder(PersonEntity)
      .where({
        id: tasks.map((task) => task.person?.id).filter((id) => id),
      })
      .getResultList();
    return persons.map((person) => person.constructor.name);
  }
```
That will return:
```
[
  'BossEntity',
  'EmployeeEntity',
  'BossEntity',
] 
```

**Comment by B4nan** [comment] 2021-12-02 23:47
That kinda implies those entities already existed in the identity map as references, and for references we dont know the correct type. We cant change the prototype once the instance exists, only thing we can do is to automatically join the relation and select the type right ahead when loading the parent entity.

**Comment by B4nan** [comment] 2021-12-03 08:04
Yeah, this is rather a limitation than a bug, will see if I can get around it via the auto-join as mentioned above, similarly to how we handle 1:1 relations on the inverse side. 

Closing as this is a duplicate of #2364 (with a repro in #2404). That issue has a bit different title, but it is the exact same problem - unless we join the target table and select the discriminator value together with the PK, we can't create the right reference instance for it.

**Closed by B4nan** 2021-12-03 08:04 UTC

**Comment by rhyek** [comment] 2021-12-03 13:59
@B4nan sounds reasonable. Although I'd wonder what the configuration for something like that would be. If done automatically for the developer, an implicit join might not be something they'd expect and could potentially have performance issues for some use cases. Setting something explicitly on the relation definition (on the owner side) would make more sense, but its something that if could be avoided would be best.

Out of curiosity, what issues do you see arising from using something like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf?

This makes sense to me and works for my use case:

```ts
const tasks = await this.tasksRepository
  .createQueryBuilder()
  .getResultList();
const persons = await this.personsRepository
  .createQueryBuilder()
  .where({
    id: tasks.map((task) => task.person?.id).filter((id) => id),
  })
  .getResultList();
for (const person of persons) {
  let targetPrototype: object = null;
  if (person.type === 'BOSS') {
    targetPrototype = BossEntity.prototype;
  } else if (person.type === 'EMPLOYEE') {
    targetPrototype = EmployeeEntity.prototype;
  }
  if (targetPrototype instanceof PersonEntity) {
    Object.setPrototypeOf(person, targetPrototype);
  }
}
return persons.map((person) => person.constructor.name);
```
that returns:
```
[
  'BossEntity',
  'EmployeeEntity',
  'BossEntity',
] 
```

**Comment by B4nan** [comment] 2021-12-03 14:08
> Out of curiosity, what issues do you see arising from using something like developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf?

Interesting, I didn't know about that! Sounds like much easier solution, let's do it this way. It should probably happen as part of hydration.

**Comment by rhyek** [comment] 2021-12-03 14:38
@B4nan I agree. That makes the most sense. Should this issue be re-opened or do you think #2364 covers it? I think this case might be a little different because it deals with child entities being hydrated later. In general, IMO, it makes sense for the initial references to be instances of the super class when the discriminating values aren't available yet.

**Comment by B4nan** [comment] 2021-12-03 14:46
It is the very same issue. I will test both reproductions after its fixed, but I am quite sure about that.
