### ISSUE TITLE
Pivot table with time data

### ISSUE THREAD

**Issue by Yaty** [mikro-orm/mikro-orm#428] opened 2020-03-28 11:10 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to save and retrieve time information within the pivot table.

For instance, I have an Event entity and a User entity. Both are connected with a ManyToMany collection which represents user registration for an event.

I would like to know when this registration was created, and when was the last time it was updated.

**Describe the solution you'd like**
Adding two fields (updatedAt/createdAt) inside the pivot table would be enough, it should be configurable through the collection decorator.

Then `user.registrations.getItems` could return `(Event & { updatedAt: Date, createdAt: Date})[]` ?

**Describe alternatives you've considered**
Creating my own pivot table and use OneToMany collection and doing the plumbing myself :)

Event < OneToMany > MyEventUserPivotTable < OneToMany > User

**Comment by B4nan** [comment] 2020-03-28 11:22
If you need additional columns in the pivot table, then it's no longer pivot table. This is not supported and I am not planning to do so. 

Duplicate of #333, take a look there for some links about the why. The alternative you described is the way to go (example of that is here https://mikro-orm.io/docs/composite-keys/#use-case-3-join-table-with-metadata).

**Closed by B4nan** 2020-03-28 11:22 UTC
Labels: enhancement

**Comment by Yaty** [comment] 2020-03-28 11:24
Ok, thanks for the quick answer ! Sorry for the duplicate

**Comment by B4nan** [comment] 2020-03-28 11:24
Btw collections support additional order column, so if this is about being able to maintain insertion order, you can use that (it will be an AI PK):

https://mikro-orm.io/docs/collections/#forcing-fixed-order-of-collection-items
