### ISSUE TITLE
Rework deep assigning of entities and collection and enable it by default

### ISSUE THREAD

**Issue by gyermich** [mikro-orm/mikro-orm#1811] opened 2021-05-15 00:14 UTC
**Describe the bug**
It looks like when trying to update a collection of entities their properties get merged at the index, and not at the id.

Example:
```javascript
console.log(recipe)
// Recipe {
//   id: '3ea3e69c-c221-41b1-a14e-135ef3141ea3',
//   name: 'Salad',
//   ingredients: Collection {
//     '0': Ingredient {
//       id: '16e443a7-b527-493f-ab8a-63012514b719',
//       name: 'Spinach'
//     },
//     '1': Ingredient {
//       id: '1d4876ce-01de-4ba8-9d17-3c1c0d56fe73',
//       name: 'Carrot'
//     }
//     initialized: true,
//     dirty: false
//   }
// }

const data = {ingredients: [
  { id: "16e443a7-b527-493f-ab8a-63012514b719", name: "Spinach" }, // existing
    { name: "Onion" }, // new, should be created
  // carrot should be dropped, id: '1d4876ce-01de-4ba8-9d17-3c1c0d56fe73',
]};

wrap(recipe).assign(data, { updateNestedEntities: true });

await this.orm.em.persistAndFlush(recipe);

const updatedRecipe = await repo.findOne({ id: recipe.id });

console.log(updatedRecipe.ingredients);

//  Collection {
//   '0': Ingredient {
//     id: '16e443a7-b527-493f-ab8a-63012514b719',
//     name: 'Spinach',
//     recipe: Recipe {
//       id: '3ea3e69c-c221-41b1-a14e-135ef3141ea3',
//       name: 'Salad',
//       ingredients: [Collection]
//     },
//   },
//   '1': Ingredient {
//     id: '1d4876ce-01de-4ba8-9d17-3c1c0d56fe73',   <===== This is the id that "Carrot" had, 'name' got updated
//     name: 'Onion'
//     recipe: Recipe {
//       id: '3ea3e69c-c221-41b1-a14e-135ef3141ea3',
//       name: 'Salad',
//       ingredients: [Collection]
//     },
//   },
//   initialized: true,
//   dirty: false
// }
```

**Stack trace**
```
...
```

**To Reproduce**
1. Create an entity with nested collection (oneToMany)
2. Create multiple items in the collection
3. Delete one item and add one item in the collection before updating the entity

**Expected behavior**
In the example above I would expect `Carrot` be deleted, and `Onion` to be a new instance of Ingredient, instead the property `name` of item at index 1 in data gets merged into `Carrot` (see `id` -> stays the same, while the name got updated).

This behavior causes issues when some items in the collection get updated, while other get added/deleted.
Is this intentional? If not, what am I missing?

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| ts-node | 9.1.1 |
| typescript | 4.0.5 |
| mikro-orm | 4.5.5-dev.1 |

**Comment by B4nan** [comment] 2021-05-15 10:51
Yes, this is by design, the flag basically calls `assign()` on the matching paths recursively, and you don't need the PK to be set to assign to entity. The whole idea of using `assign` for deep updates seems a bit wrong to me, this is one of the reasons, everybody is expecting something else from it :] It was originally designed only for the root entity especially for this reason. It's better to make the code more explicit rather than trying to use "one smart command" to do everything. 

```ts
recipe.ingredients.set([
  em.getReference(Ingredient, "16e443a7-b527-493f-ab8a-63012514b719"),
  em.create(Ingredient, { name: "Onion" }),
]);
```

Or of course, you can always craft a helper method that will suite your needs. Check the `EntityAssigner` source code, it is quite simple. Maybe we could make all the methods public to allow reusing them.

**Comment by B4nan** [comment] 2021-05-15 11:00
Maybe we could change the behaviour in v5, I did not want to add more options to the helper as there are way too many already, but on the other hand, I was thinking about enabling the `updateNestedEntities` flag by default, and in that case, this would definitely have to support create/delete items as you are expecting (as that is the behaviour of assign without the flag, but it considers objects as new entities always). Maybe we could have a flag to enable updates only if PK is provided on child entities, and it would be enabled by default, so it would be still possible to preserve old behaviour if anybody depends on it.

**Closed** 2021-06-28 18:12 UTC
Labels: breaking change, enhancement
