### ISSUE TITLE
Create foreign key constraint without relation

### ISSUE THREAD

**Issue by Eskiell** [mikro-orm/mikro-orm#837] opened 2020-09-14 01:31 UTC
Can I add foreign key constraint without relation ? 

exemple:

@Entity()
class PhoneNumber {
    @PrimaryGeneratedColumn(); 
    id: number; 
    
    @Column()
    @ForeignKey((u: User) => u.id)
    userId: string;

    @Column(); 
    phoneNumber: string; 
}

**Comment by B4nan** [comment] 2020-09-14 07:09
This is currently not supported (no tests for this), but someone on the slack channel said it was working for them like this:

```ts
@ManyToOne(() => User)
usedId: string;
```

(But to me it sounds strange, I would expect some issues)

Currently you could define custom hydrator that would do so. It's not documented anywhere, but hydrator layer is where the mapping is handled, its rather simple interface, all you need to do is to implement `hydrateProperty` method:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/hydration/Hydrator.ts
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/hydration/ObjectHydrator.ts
https://mikro-orm.io/docs/configuration/#custom-hydrator

I guess I should make the ObjectHydrator methods protected so it can be reused... 

Closing this as duplicate of #750.

**Closed by B4nan** 2020-09-14 07:09 UTC
Labels: enhancement
