### ISSUE TITLE
Error: Transaction query alread complete, run with DEBUG=knex:tx for more info

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#1885] opened 2021-05-31 15:17 UTC
**Describe the bug**

Have you every received an error like this and can you tell me where to look / enable DEBUG=knex.ts?

The error comes when executing multiple times (quickly) the query:

```
return this.em.findOne(Availability, {
      user: user,
      isAdHocAvailability: true,
      endTime: null,
      startTime: { $lte: new Date() },
    });
```

The error does not pop up all the time, however, when testing with many devices (Android Emulator, iOS Simulator, actual iPhone Device, Websive) all accessing the API (NestJS with MikroORM and Apollo GraphQL), this pops up.

It could be a problem with the Identity Map still, where I haven't found a way to solve this properly with GraphQL Execution Context with NestJS, MikroORM and Postgres (a very popular stack for backend).

**Stack trace**
```
Other error, {"message":"Transaction query already complete, run with DEBUG=knex:tx for more info","locations":[{"line":7,"column":5}],"path":["findOrCreateAdHocAvailability","lastLocation"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"DriverException","stacktrace":["DriverException: Transaction query already complete, run with DEBUG=knex:tx for more info","    at PostgreSqlExceptionConverter.convertException (backend/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)","    at PostgreSqlExceptionConverter.convertException (/backend/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)","    at PostgreSqlDriver.convertException (/backend/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)","    at /backend/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async PostgreSqlDriver.find (/backend/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)","    at async PostgreSqlDriver.findOne (/backend/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:60:21)","    at async SqlEntityManager.findOne (/backend/node_modules/@mikro-orm/core/EntityManager.js:237:22)","    at async AvailabilityService.getLastLocationForAvailability (/backend/dist/modules/availability/availability.service.js:79:38)","    at async target (/backend/node_modules/@nestjs/core/helpers/external-context-creator.js:76:28)","","previous Error: Transaction query already complete, run with DEBUG=knex:tx for more info","    at completedError (/backend/node_modules/knex/lib/transaction.js:358:9)","    at /backend/node_modules/knex/lib/transaction.js:324:24","    at new Promise (<anonymous>)","    at Client_PG.trxClient.query (/backend/node_modules/knex/lib/transaction.js:320:12)","    at Runner.query (/backend/node_modules/knex/lib/runner.js:151:36)","    at /backend/node_modules/knex/lib/runner.js:40:23","    at /backend/node_modules/knex/lib/runner.js:277:24","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async PostgreSqlConnection.executeQuery (/backend/node_modules/@mikro-orm/core/connections/Connection.js:56:25)","    at async PostgreSqlConnection.execute (/backend/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:105:21)"]}}}
at src/globals/index.ts:171:14 in onError$argument_0
at node_modules/@apollo/client/link/error/error.cjs.js:11:40 in utilities.Observable$argument_0
at node_modules/zen-observable/lib/Observable.js:135:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:179:20 in onNotify
at node_modules/zen-observable/lib/Observable.js:235:14 in next
at node_modules/@apollo/client/link/retry/retry.cjs.js:41:25 in RetryableOperation
at node_modules/zen-observable/lib/Observable.js:135:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:179:20 in onNotify
at node_modules/zen-observable/lib/Observable.js:235:14 in next
at [native code]:null in next
at [native code]:null in forEach
at http://192.168.178.52:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:237346:34 in <unknown>
at [native code]:null in forEach
at node_modules/@apollo/client/link/batch/batch.cjs.js:86:31 in batchedObservable.subscribe$argument_0.next
at node_modules/zen-observable/lib/Observable.js:135:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:179:20 in onNotify
at node_modules/zen-observable/lib/Observable.js:235:14 in next
at node_modules/@apollo/client/link/batch-http/batch-http.cjs.js:73:23 in batchHandler
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 4.5.5 |
| postgres |  |

**Comment by B4nan** [comment] 2021-05-31 16:17
> Have you every received an error like this and can you tell me where to look / enable DEBUG=knex.ts?

Just add `DEBUG=knex:tx` environment variable, e.g. you can run the script with `DEBUG=knex:tx` prefix:

```
DEBUG=knex:tx yarn start
```

Similar issue was reported recently when doing this from inside flush events, but this does not seem to be related. The issue is here: #1824 

> The error comes when executing multiple times (quickly) the query:

You should not use single EM instance in parallel. Also seeing `findOrCreateAdHocAvailability` in your stack trace, that is even forbidden, not just suggested, you can't flush in parallel. Also you definitely need to use explicit transaction for that, otherwise the select query won't use the same transaction. Something like this:

```ts
const availability = await em.transactional(async inner => {
  let a = await inner.findOne(Availability, { ... });

  if (!a) {
    a = new Availability(...);
    await inner.persistAndFlush(a);
  }

  return a;
});
```

The transactional callback gets a fork in its parameter (here called `inner`). It will contain all the entities from parent EM too, but ideally it should be clear/empty.

But seeing this is triggered by a find call (which won't create implicit transaction on its own), I guess you are probably already doing something like that?

**Comment by B4nan** [comment] 2021-05-31 16:19
> It could be a problem with the Identity Map still, where I haven't found a way to solve this properly with GraphQL Execution Context with NestJS, MikroORM and Postgres (a very popular stack for backend).

Have you seen this?

https://mikro-orm.io/docs/usage-with-nestjs#request-scoping-when-using-graphql

**Comment by woltob** [comment] 2021-05-31 16:34
Thanks for the quick reply.

This look quite complicated. Why do I have to use em.transactional... for every query? Can't this be handled by MikroORM if (as I understand) this would be required for every query and do I have to change every query in my application to match the above example? Or did I misunderstand?

Looking at other frameworks, one can simply do Entity.findFirst({column: "value"} and done, running perfectly under thousands of concurrent requests.

If I use EntityRepository, would that be simpler?

I believe if you would provide a NestJS example with some typical queries that would run under high concurrency it would help a lot. The app I'm working on needs to go into production soon and has to run without errors or concurrency problems.

Thank you so much for an elaboration.

**Comment by B4nan** [comment] 2021-05-31 16:53
> This look quite complicated. Why do I have to use em.transactional... for every query? Can't this be handled by MikroORM if (as I understand) this would be required for every query and do I have to change every query in my application to match the above example? Or did I misunderstand?

I am talking only about the find-or-create kind of action (= upserts). You need the explicit tx because you need the select query to be executed inside it, otherwise there is no guarantee at the database level. 

> If I use EntityRepository, would that be simpler?

Nope, that's just a thin layer on top of EM, nothing is different with repositories.

**Comment by woltob** [comment] 2021-05-31 16:58
`I am talking only about the find-or-create kind of action (= upserts). You need the explicit tx because you need the select query to be executed inside it, otherwise there is no guarantee at the database level.`

Thanks, understood now, that's actually an important thing :)

**Comment by woltob** [comment] 2021-05-31 17:14
I am still receiving this error: 

```
[Nest] 23794   - 31/05/2021, 19:11:36   [MikroORM] [query] insert into "availability" ("created_at", "end_time", "id", "is_ad_hoc_availability", "start_time", "updated_at", "user_id") values ('2021-05-31T17:11:36.263Z', NULL, 'b2210507-f813-4bad-aeac-6ec1f7fca68a', true, '2021-05-31T17:11:36.263Z', '2021-05-31T17:11:36.263Z', 'c59620ed-37a5-452f-9b3d-d2ff979322ec') returning "id"

(node:23794) UnhandledPromiseRejectionWarning: DriverException: Transaction query already complete, run with DEBUG=knex:tx for more info

ValidationError: You cannot call em.flush() from inside lifecycle hook handlers

```

here is the code:

```

const availability = await this.em.transactional(async (inner) => {
      let availability: Availability | null = await this.em.findOne(
        Availability,
        {
          user: userContext.user,
          isAdHocAvailability: true,
          endTime: null,
          startTime: { $lte: new Date() },
        },
      );

      if (!availability) {
        availability = new Availability({
          user: userContext.user,
          isAdHocAvailability: true,
          startTime: new Date(),
        });
      } else {
        availability.updatedAt = new Date();
      }

      inner.persistAndFlush(availability);
      return availability;
    });

``` 

Any query after this can still be executed and will not cause problems with the above code?

**Comment by woltob** [comment] 2021-05-31 17:15
Okay, I forgot to put await in front of inner.persistAndFlush(availability);. With await inner.persistAndFlush(availability); it seems to be working.

**Comment by B4nan** [comment] 2021-05-31 17:20
Ok good, closing then.

**Closed by B4nan** 2021-05-31 17:20 UTC
Labels: needs clarification
