### ISSUE TITLE
PostgreSQL driver needs superuser privileges

### ISSUE THREAD

**Issue by ujwal-setlur** [mikro-orm/mikro-orm#422] opened 2020-03-24 23:42 UTC
**Describe the bug**
The PostgreSQL driver seems to require superuser privileges. Ay reason? Connecting as a regular user, it complains of ```permission denied to set parameter "session_replication_role"```

**Stack trace**
```
permission denied to set parameter "session_replication_role"
```

**To Reproduce**
1. Spin up PostgreSQL instance
2. Connect to database as an ordinary user
3. Connection fails

**Expected behavior**
A regular user with all privileges on that specific database should be able to connect.

**Versions**
3.5.0

Using cloud managed or hosted PostgreSQL will be challenging under this scenario.

**Comment by ujwal-setlur** [comment] 2020-03-25 02:57
Is there an option I am missing?

**Comment by B4nan** [comment] 2020-03-25 06:55
Duplicate of #190, this is not about connecting to the database, its about running migrations or using schema generator. Just use the `wrap = false` parameter.

I guess it would be better to change that default, I thought it will be needed but shouldn't be nowadays.

**Closed** 2020-03-25 06:55 UTC
Labels: bug

**Comment by ujwal-setlur** [comment] 2020-03-25 14:54
Thanks! I did search for issues before filing, and did indeed see #190, but didn’t read close enough to realize that it was the same thing. Apologies!
