### ISSUE TITLE
ManyToMany - Through table

### ISSUE THREAD

**Issue by Patrick-Nies** [mikro-orm/mikro-orm#838] opened 2020-09-14 09:18 UTC
I would like to join two entities with additional data.

e.G. I have a mission with many resources. Resources can join this mission and leave this mission with some mission specific parameters. (e.G. time joined, load, ....).

In sequelize this will be done by a through parameter

```ts
const Mission = sequelize.define('Mission' ....);
const Resource = sequelize.define('Resource', ...);
const ResourcesInMission= sequelize.define('ResourceInMission', { loadout: DataTypes.STRING,...};
Resource.belongsToMany(Mission, {
    through: "ResourcesInMission"
});
Mission.belongsToMany(Resource, {
    through: "ResourcesInMission"
})
```

Right now I'm doing several ManyToOne with one table inbetween. But maybe there is a better way?

**Comment by B4nan** [comment] 2020-09-14 09:23
No plans to support additional metadata in pivot tables, as there would be no way to read or write those (and the pivot table would be no longer a pivot table). Using multiple m:1/1:m relations is the correct way.

https://mikro-orm.io/docs/composite-keys/#use-case-3-join-table-with-metadata

Duplicate of #333, #697

**Closed by B4nan** 2020-09-14 09:23 UTC
Labels: enhancement
