### ISSUE TITLE
One-to-Many relations inconsistently populated when querying on abstract/parent entity.

### ISSUE THREAD

**Issue by kyllerss** [mikro-orm/mikro-orm#4630] opened 2023-08-16 01:25 UTC
**Describe the bug**

I have a parent/child relation that I am querying from the database. One of the children is properly loaded from the database, while the other child's relations is not. I have confirmed that the database is populating the entries correctly. The list operation by UUID is failing to retrieve the full records on one of the children. I have provided a recreation ([here](https://github.com/kyllerss/mikro-orm-issue-4630)) that illustrates the issue. 

To be more specific: `TrackCommentEntity` holds a one-to-many relation (`TrackCommentPictureEntity`). I have a similar set of entities defined for pools (`PoolCommentEntity` and `PoolCommentPictureEntity`) - though for some reason the pool-related entities don't exhibit this problem.

When I query against the parent definition (`BaseCommentEntity`) for track and pool comment entities, `PoolCommentEntity` is the only one that has its one-to-many relation (picture collection) populated. The `TrackCommentEntity` one-to-many relation is empty.

**Stack trace**
N/A

**To Reproduce**
1. `git clone git@github.com:kyllerss/mikro-orm-issue-4630.git`
2. `npm install`
3. `npm run test`

**Expected behavior**
Relations to be loaded for all the children.

**Versions**

| Dependency | Version |
| - | - |
| typescript | 5.1.6 |
| mikro-orm | 5.7.14 |
| postgresql (pg) | 8.11.2 |

**Comment by B4nan** [comment] 2023-08-16 08:29
That is a very complex reproduction, so complex I wouldn't really call it a reproduction :] Could you please try to minimize this first, so I can focus on the actual problem?

The next steps should be:
- remove svelte and possibly other unrelated dependencies, reproduction should be a script that only uses the ORM
- use the schema generator to rule out your schema is out of sync, this is a very common source of issues
- use fewer entities, I doubt you actually need 9 entities to reproduce anything
- remove the custom repository, and inline the code that actually matters to the test itself
- don't use the `RequestContext` helper
- preferably use sqlite in-memory database

Reproduction should be ideally a self-contained script, like in the https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues.

**Comment by kyllerss** [comment] 2023-08-16 14:31
Ha! You should have seen the original code. ;) Thanks for the suggestions. I'll rework the reproduction.

**Comment by kyllerss** [comment] 2023-08-16 15:49
I have uploaded the simplified reproduction. I followed all of your suggestions except for using SQLite (I wasn't able to find a good way of switching away from Postgres). Hopefully this simplified version helps. Thank you again for your help and this great framework!

**Comment by kyllerss** [comment] 2023-08-16 21:30
I have updated the instructions to be up-to-date with the simplifications.

**Comment by kyllerss** [comment] 2023-08-27 00:39
@B4nan It is worth noting that it seems as if the logic around the discriminator column is the culprit. The query that pulls the relation for both entity types in the test is using the primary keys for both entity types, but the query includes a discriminator column value that corresponds to only one of the two entity types. 

Here are the sequence of queries from this test:

```sql
-- Creates entity #1 + 2 pictures
insert into `comments` (`type`, `uuid`) values ('track', '7ab80573-df78-4158-ba7f-19126a74ae41')
insert into `pictures` (`type`, `uuid`, `comment_uuid`) values 
    ('track_comment', xxxxx, '7ab80573-df78-4158-ba7f-19126a74ae41'), 
    ('track_comment', xxxxx, '7ab80573-df78-4158-ba7f-19126a74ae41')

-- Creates entity #2 + 2 pictures
insert into `comments` (`type`, `uuid`) values ('pool', 'b615efac-5bd4-4418-88d9-10724665045c')
insert into `pictures` (`type`, `uuid`, `comment_uuid`) values 
    ('pool_comment', xxxxx, 'b615efac-5bd4-4418-88d9-10724665045c'), 
    ('pool_comment', xxxxx, 'b615efac-5bd4-4418-88d9-10724665045c')

-- Query against base class 
select `b0`.* from `comments` as `b0` where `b0`.`uuid` in ('7ab80573-df78-4158-ba7f-19126a74ae41', 'b615efac-5bd4-4418-88d9-10724665045c') [took 0 ms, 2 results]

-- Query for base-class's relations 
-- NOTE: uuid's are for both entities #1 and #2, 
--       BUT discriminator column 'type' matches only entity #2's value.  
select `p0`.* from `pictures` as `p0` where `p0`.`comment_uuid` in ('7ab80573-df78-4158-ba7f-19126a74ae41', 'b615efac-5bd4-4418-88d9-10724665045c') and `p0`.`type` = 'pool_comment' order by `p0`.`comment_uuid` asc [took 0 ms, 2 results]

Loaded from database:  track 7ab80573-df78-4158-ba7f-19126a74ae41 0
Loaded from database:  pool b615efac-5bd4-4418-88d9-10724665045c 2

```

**Comment by B4nan** [comment] 2023-08-27 15:20
What you are trying to do is not supported, you cannot map a single column to target different entities, that is just a hidden variant of a polymorphic relation, so closing as a duplicate of #706. Also there is #2388 which is connected to your problem as well (but there its about mapping .

I would generally discourage this pattern, as it cannot work with foreign key constraints, you would be losing the most important feature of a relational database.

**Closed by B4nan** 2023-08-27 15:20 UTC

**Comment by kyllerss** [comment] 2023-08-28 01:35
Sounds good. Part of my confusion is that it *seems* to be supported. When loading either type of entity directly (`entity_manager.find(TrackCommentEntity, uuid)` or `entity_manager.find(PoolCommentEntity, uuid)`), it behaves as one would expect and returns the correct fully-populated values. However, when querying against the base class (`entity_manager.find(BaseCommentEntity, uuids)`) the issue outlined above occurs. 

If this is a feature that isn't likely to get implemented in the visible future, perhaps adding a warning whenever it detects these types of cases would be helpful to people so they don't wonder why it works in one case and not in another.

Thanks again for the clarification! I'll make the necessary changes on my side.
