### ISSUE TITLE
Version property in afterUpdate hooks has unexpected value

### ISSUE THREAD

**Issue by vinverdy** [mikro-orm/mikro-orm#6022] opened 2024-09-12 12:38 UTC
### Describe the bug

returning statement order, when using postgresql is does not always follow where query order

### Reproduction

```ts
import { Entity, MikroORM, Property } from '@mikro-orm/postgresql';

@Entity()
class Test {
  @Property({ primary: true })
  public id!: number;

  @Property()
  public date!: Date;

  @Property({ version: true })
  public version!: number;
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Test],
    clientUrl: `postgresql://test:test@localhost:5432/test`,
    allowGlobalContext: true,
    subscribers: [
      {
        afterUpdate(args) {
          if (args.entity.version !== args.entity.id + 1) {
            throw new Error('Something wrong');
          }
        },
      },
    ],
  });
  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test('test', async () => {
  await orm.em.execute(
    'INSERT INTO test (id,date,version) SELECT version as id, current_timestamp as date, version FROM generate_series(1, 100) as g (version);',
  );
  const all = await orm.em.find(Test, {}, { orderBy: { id: 'DESC' } }); // its success when using 'ASC'
  all.forEach((a) => (a.date = new Date()));
  await orm.em.flush();
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.9

### Node.js version

22.4.1

### Operating system

mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment] 2024-09-13 09:27
This is a duplicate of an issue created just 2 days ago: #6016

> Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) that reports the same bug to avoid creating a duplicate.

I know it's tempting to just tick the checkbox, but you are supposed to do the things they say before ticking...

**Closed by B4nan** 2024-09-13 09:27 UTC
