### ISSUE TITLE
Find / FindOne with refresh set to true doesn't parse custom fields

### ISSUE THREAD

**Issue by andrei-bitca-dc** [mikro-orm/mikro-orm#2109] opened 2021-08-11 14:43 UTC
When trying to `findOne` entity that has custom field type (`json`) using the entity manager and setting `refresh` to `true`, it gets the entity without parsing the custom type field.

**To Reproduce**
```
@Entity()
export class AEntity {
  @PrimaryKey()
  public _id!: ObjectId;

  @SerializedPrimaryKey()
  public id!: string;

  @Property({ type: "json", fieldName: "field" })
  public field!: Record<string, string>;
}

async test() {
  const mikroOrm = await MikroORM.init({
    type: "mongo",
    clientUrl: "",
    dbName: "",
    entities: [AEntity],
    driverOptions: {
      useUnifiedTopology: false,
    },
  });
  
  const entity = await mikroOrm.em.findOne(
    AEntity,
    { id: { $eq: "6113de056f2ee1bb090af460" } },
    { refresh: true },
  );
  
  console.log(entity);
}

test();

```

**Expected behavior**
`EntityManager.findOne` should parse json field:

```
AEntity {
  field: { 'test': 'test' },
  _id: ObjectId('6113de056f2ee1bb090af460')
}
```

but instead it returns stringified `field`.

```
AEntity {
  field: "{\"test\":\"test\"}",
  _id: ObjectId('6113de056f2ee1bb090af460')
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| mongodb | 3.6.10 |

**Comment by B4nan** [comment] 2021-08-11 15:30
I really doubt having `refresh: true` is the cause. It is more likely to be dependency resolution issue and the custom type is not recognized at all. Because in your reproduction you are not having the entity loaded in the context, therefore the `refresh: true` is literally not doing anything, the flag is checked only when checking the identity map for existing/loaded entities. 

Ensure you have only single installation of `@mikro-orm/core` in your `node_modules`. Also ensure you do not use the `mikro-orm` metapackage and all ORM packages are on the very same version. How does your package.json look like?

**Comment by B4nan** [comment] 2021-08-11 15:37
Closing as duplicate of #2091, tried your repro but as expected, this is not reproducing anything. I am quite sure this is dependency resolution as mentioned in previous comment. If you want more help, please provide full (but minimal) repro, executable one.

**Closed by B4nan** 2021-08-11 15:37 UTC

**Comment by andrei-bitca-dc** [comment] 2021-08-12 06:06
@B4nan I'm using a monorepo, but this is the only package that is using mikro-orm, so there is only one installation in the `node_modules`. These are the only 2 packages I have installed:

```
"@mikro-orm/core": "4.5.7",
"@mikro-orm/mongodb": "4.5.7",
```

I'm mentioning that this only happens on `refresh` set to `true`. If not set, it recognizes the custom type.
I'm also mentioning that I'm also using `typeorm` for the `mysql` connections. Is this something that might collide? Though, I really doubt it.

Will try to come back with a reproducible snippet.

Thanks for looking into this, @B4nan!

**Comment by andrei-bitca-dc** [comment] 2021-08-13 09:09
@B4nan I was raw updating the entity in the database and stringifying the json field, that's the reason for that. Thanks!
