### ISSUE TITLE
Under @OneToOne relationship how can I custom foreign column to map columns other than the primary key

### ISSUE THREAD

**Issue by BiuWcs** [mikro-orm/mikro-orm#4889] opened 2023-11-01 13:09 UTC
Here is my code

`  @OneToOne(() => Cart, cart => cart.customer, {
  })
  cart: Cart;`

`  @OneToOne(() => Customer, {
    inversedBy: customer => customer.cart,
    referenceColumnName: 'uuid',
    orphanRemoval: true,
  })
  customer: Customer;
`
When I am trying to save a cart by using code below: 
` const cart = new Cart();
   cart.uuid = uuid();
   customerEntity.cart = cart;
   this..save(customerEntity)` 

sql that i expected is 
`insert into cart_table (uuid, customer_id) values ('95e67479-4064-4067-96da-3ce92316d97a', '2c525587-f307-4499-ab27-bce3e74acfb9') `  customer_id reference to the Customer.uuid which is a unique column, not the primary key Customer.id .
 I was trying to use `referenceColumnName` but it didn't work.

**Comment by B4nan** [comment] 2023-11-01 13:17
This is not supported, closing as a duplicate of #593.

I want to have a closer look into this soon, after v6 is out, I do have an idea of how this could work.

**Closed by B4nan** 2023-11-01 13:17 UTC
