### ISSUE TITLE
wrap(...).isInitialized is not a function when persisting OneToOne

### ISSUE THREAD

**Issue by jshearer** [mikro-orm/mikro-orm#465] opened 2020-04-08 03:48 UTC
**Describe the bug**
---
I'm trying to persist a 1:1 relationship for a "subdocument" by creating an instance of the subdocument and assigning it to `this.subdoc`, expecting that it will get cascaded properly. Instead, I get a cryptic error that `wrap(...).isInitialized` is not a function. This only happens when the 1:1 relationship is "owned" by the subdoc -- moving the ownership to the "main" doc fixes the issue.

**Stack trace**
```
TypeError: wrap(...).isInitialized is not a function

      at Function.propagate (../node_modules/mikro-orm/dist/entity/EntityHelper.js:171:91)
      at ReportLog.set [as report] (../node_modules/mikro-orm/dist/entity/EntityHelper.js:159:30)
      at ../node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:87:39
          at Array.forEach (<anonymous>)
      at ChangeSetPersister.mapReturnedValues (../node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:85:44)
      at ChangeSetPersister.persistEntity (../node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:33:18)
      at ChangeSetPersister.persistToDatabase (../node_modules/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:20:9)
      at UnitOfWork.commitChangeSet (../node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:208:9)
      at UnitOfWork.persistToDatabase (../node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:342:13)
```

**To Reproduce**
---
`Report.entity.ts` _truncated for brevity_
```es6
@Entity()
export class Report extends BaseEntity {
    @OneToOne({
        mappedBy: "report",
    })
    public log: IdentifiedReference<ReportLog>;

    constructor() {
        this.log = Reference.create(new ReportLog()); // I suspect this has something to do with it
    }
}
```

`ReportLog.entity.ts` _truncated for brevity_
```es6
@Entity()
export class ReportLog {
    @OneToOne({
        owner: true,
        primary: true,
    })
    report!: Report;

    @Property({ columnType: "text" })
    logText = "";
}
```

`report.spec.ts` _truncated for brevity_
```es6
describe("RunnerService", () => {
      it("Should work with a reporter instance", async () => {
        expect.hasAssertions();

        const report = new Report();
        await entMan.persistAndFlush(report); // Fails here with the above stack trace
        
        // ...      

        expect(report.status).toEqual(ReportStatus.FINISHED);
        await expect(report.log.get("logText")).resolves.toMatchInlineSnapshot(`...`);
    });
});
```

**Workaround**
---
In order to work around this, I found out that moving the "ownership" of the 1:1 relationship to `Report` works. This means that the `report` table has a `report_log_id` column, instead of `report_log` having a `report_id` column. In the end it doesn't really matter, but it was pretty confusing to have to figure this out.

As an additional piece of (constructive! 🚧) feedback, I feel like the docs surrounding how to use the `OneToOne` field are a bit confusing..  I really just had to fiddle with `owner`, `inversedBy`, `mappedBy`, and the different ways to specify which table is the target (`@OneToOne(()=>Report, report=>report.log)` vs `@OneToOne({mappedBy:"log"})`) to get stuff to work, while simultaneously debugging errors like `Both ReportLog.report and Report.log are defined as inverse sides, use 'inversedBy' on one of them` when I clearly specified `inversedBy`. 

I also encountered a bunch of weird schema generation issues like
```
alter table "report" add constraint "report_log_report_global_id_foreign" foreign key ("log_report_global_id") references "report_log" ("report_global_id") on update cascade; - column "report_global_id" referenced in foreign key constraint does not exist
```

**Versions**
```json
    "mikro-orm": "^3.6.4",
    "nestjs-mikro-orm": "^1.0.3"
```

**Comment by B4nan** [comment] 2020-04-08 07:05
Hmm it is working fine for me, maybe some caching issue? Here is the full test on my end (not I am using reflect metadata provider for tests so the discovery is fast, therefore I had to add one `entity` param there as that is not automatically picked with this provider, same with `wrappedReference`, both not needed with ts-morph metadata provider, the default one):

<details>
<summary>GH issue 465 test</summary>

```typescript
import { unlinkSync } from 'fs';
import { Entity, PrimaryKey, Property, MikroORM, ReflectMetadataProvider, IdentifiedReference, OneToOne, Reference } from '../../lib';
import { SqliteDriver } from '../../lib/drivers/SqliteDriver';

@Entity()
export class Report {

  @PrimaryKey()
  id!: number;

  @OneToOne({ entity: () => ReportLog, wrappedReference: true, mappedBy: 'report' })
  log: IdentifiedReference<ReportLog>;

  constructor() {
    this.log = Reference.create(new ReportLog());
  }

}

@Entity()
export class ReportLog {

  @OneToOne({ primary: true })
  report!: Report;

  @Property({ columnType: 'text' })
  logText = '';

}

describe('GH issue 465', () => {

  let orm: MikroORM<SqliteDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Report, ReportLog],
      dbName: __dirname + '/../../temp/mikro_orm_test_gh465.db',
      type: 'sqlite',
      metadataProvider: ReflectMetadataProvider,
      cache: { enabled: false },
    });
    await orm.getSchemaGenerator().dropSchema();
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(async () => {
    await orm.close(true);
    unlinkSync(orm.config.get('dbName')!);
  });

  test(`1:1 bug`, async () => {
    const report = new Report();
    await orm.em.persistAndFlush(report);
    expect(report.id).toBeDefined();
  });

});
```

</details>

> As an additional piece of (constructive! 🚧) feedback, I feel like the docs surrounding how to use the OneToOne field are a bit confusing.. I really just had to fiddle with owner, inversedBy, mappedBy, and the different ways to specify which table is the target (@OneToOne(()=>Report, report=>report.log) vs @OneToOne({mappedBy:"log"})) to get stuff to work, while simultaneously debugging errors like Both ReportLog.report and Report.log are defined as inverse sides, use 'inversedBy' on one of them when I clearly specified inversedBy.

What docs do you mean? There are multiple places where this is covered. Anyway, for me it works quite clearly:

- fill in `inversedBy` => entity is owning side (no FK)
- fill in `mappedBy` => entity is inverse side (no FK)
- when using the `@OneToOne(() => Ent, e => e.prop)` approach, you need to explicitly mark the owner via `owner: true`, or omit the second parameter on the owner (so yes, in your example, the `owner: true` is not necessary)

https://mikro-orm.io/docs/relationships/#onetoone

> debugging errors like Both ReportLog.report and Report.log are defined as inverse sides, use 'inversedBy' on one of them when I clearly specified inversedBy.

It's a validation error, and you clearly did configure it wrong when you saw it. 

> I also encountered a bunch of weird schema generation issues like

Well this is not really helping, the query is about some `global` thing, that is nowhere in your example. There is no magical place in the schema generator that would add word `global` to your field name.

**Comment by B4nan** [comment] 2020-04-10 11:42
Any update?

**Comment by B4nan** [comment] 2020-04-14 19:39
Closing as I cannot reproduce.

**Closed** 2020-04-14 19:39 UTC
Labels: bug

**Comment by B4nan** [comment] 2020-04-22 12:02
As discussed in #501 the problem here was with the postgres driver. Will release fix later today.
