### ISSUE TITLE
MongoDB Migration

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#1920] opened 2021-06-10 19:36 UTC
**Is your feature request related to a problem? Please describe.**
I was wondering if there's any plan to implement a mongodb migrator. I know there's no major schema synchronizations for mongo but there's a lot of other useful purposes for using migrations ie. Batch document update jobs, db configuration scripts etc. And it would really be nice to utilize the mikro orm migration setup for this.

**Describe the solution you'd like**
Could there be a mongo driver for migrations?

**Describe alternatives you've considered**
All migration tools I've searched are not really supported still, and then the other alternative is to write my own.

**Additional context**
Is there any suggestions as work around for this that I could utilize some of the mikro form migration features by implementing my own driver or something?

Thanks!

**Comment by B4nan** [comment] 2021-06-11 14:58
Duplicate of #295

**Closed by B4nan** 2021-06-11 14:58 UTC
Labels: enhancement
