### ISSUE TITLE
Invalid entity paths on Windows

### ISSUE THREAD

**Issue by itsame-luigi** [mikro-orm/mikro-orm#2654] opened 2022-01-20 04:22 UTC
**Describe the bug**
Paths associated with entity metadata are invalid on Windows when the calling module is an ES module. If an entity's source file is `C:\dev\project\entities\foo.ts`, the entity's path is being calculated as `C:\dev\project\file:\C:\dev\project\entities\foo.ts`, resulting in errors when discovering the schema.

I was able to isolate the issue to the following functions in Utils.ts:
- `normalizePath` - Does not handle cases where a path part is an absolute path or a `file://` URI
  - This seems to be the reason `file:\C:\...` is appended to the base directory (but not the reason for the `file:///C:/` -> `file:\C:\` conversion)
- `relativePath` - Does not handle `file://` URIs, which are then passed to the `path` module verbatim.
  - This seems to be the reason `file:///C:/` is converted to `file:\C:\`

This is an issue due to how NodeJS/v8 formats stack traces in recent versions. The paths in a stack trace sometimes show up as `file:///` URLs instead of local paths. This affects how `Utils.lookupPathFromDecorator` handles path discovery for an entity, since it relies on stack traces.

**Stack trace**
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\dev\project\file:\C:\dev\project\dist\db\entities\foo.js' imported from C:\dev\project\node_modules\@mikro-orm\core\dist\utils\Utils.js
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:321:11)
    at moduleResolve (node:internal/modules/esm/resolve:756:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:867:11)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
    at Loader.import (node:internal/modules/esm/loader:177:28)
    at importModuleDynamically (node:internal/modules/cjs/loader:1041:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:43)
    at exports.importModuleDynamicallyCallback (node:internal/process/esm_loader:30:14)
    at eval (eval at dynamicImport (C:\dev\project\node_modules\@mikro-orm\core\dist\utils\Utils.js:647:16), <anonymous>:3:1)
    at Function.dynamicImport (C:\dev\project\node_modules\@mikro-orm\core\dist\utils\Utils.js:647:50)
    at MetadataDiscovery.initEnumValues (C:\dev\project\node_modules\@mikro-orm\core\dist\metadata\MetadataDiscovery.js:783:45)
    at MetadataDiscovery.initColumnType (C:\dev\project\node_modules\@mikro-orm\core\dist\metadata\MetadataDiscovery.js:744:24)
    at MetadataDiscovery.processDiscoveredEntities (C:\dev\project\node_modules\@mikro-orm\core\dist\metadata\MetadataDiscovery.js:68:28)
    at async MetadataDiscovery.discover (C:\dev\project\node_modules\@mikro-orm\core\dist\metadata\MetadataDiscovery.js:35:9)
    at async MikroORM.discoverEntities (C:\dev\project\node_modules\@mikro-orm\core\dist\MikroORM.js:87:25)
    at async Function.init (C:\dev\project\node_modules\@mikro-orm\core\dist\MikroORM.js:42:9)
    at null.<anonymous> (C:\dev\project\src\db\index.ts:4:20)
```

**To Reproduce**
1. TBD

I will look into putting together a basic test case if the information above isn't sufficient.

**Expected behavior**
Paths are resolved correctly.

**Additional context**

- OS: Windows 11
- Source module was an ES module

I was able to patch `Utils` at runtime to work around this issue:

```ts
import { Utils } from "@mikro-orm/core";
import { platform } from "os";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

function isFileUrl(text: string) {
    return text.startsWith("file://");
}

const prevNormalizePath = Utils.normalizePath;
Utils.normalizePath = function(...parts) {
    // skip parts that come before an absolute path part
    let start = 0;
    for (let i = 0; i < parts.length; i++) {
        if (path.isAbsolute(parts[i])) {
            start = i;
        }
        else if (isFileUrl(parts[i])) {
            start = i;
            parts[i] = fileURLToPath(parts[i]);
        }
    }
    if (start > 0) {
        parts = parts.slice(start);
    }
    return prevNormalizePath(...parts);
};

const prevRelativePath = Utils.relativePath;
Utils.relativePath = function (path, relativeTo) {
    if (!path) return path;
    if (isFileUrl(path)) path = fileURLToPath(path);
    if (isFileUrl(relativeTo)) relativeTo = fileURLToPath(relativeTo);
    return prevRelativePath(path, relativeTo);
};
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.6.2 |
| typescript | 4.5.4 |
| mikro-orm | 5.0.0-dev.645 |
| your-driver | sqlite |

**Comment by itsame-luigi** [comment] 2022-01-20 05:06
For additional reference as to when `file://` URIs are present in stack traces, see the following:
- https://github.com/nodejs/node/issues/39787
- https://nodejs.org/dist/latest-v17.x/docs/api/errors.html#errorstack (see bullet near the end of the section):
  ![image](https://user-images.githubusercontent.com/84438007/150276923-7f2a5952-aa67-4515-8a21-b99fe33dca8a.png)

NOTE: the docs link above points to the NodeJS v17 documentation, but applies to Node v16 as well.

**Comment by B4nan** [comment] 2022-01-20 08:44
Can't help much with windows issues, best way to see this fixed is to contribute :] Your proposal looks good to me, if it does not break any tests, I am fine with merging that. You can open a PR to see if the tests will pass. We don't test on windows, so this would have to be unit test for that `lookupPathFromDecorator` method.

https://github.com/mikro-orm/mikro-orm/blob/master/tests/Utils.test.ts#L250

**Comment by B4nan** [comment] 2022-01-21 08:56
If you are sure the issue is just in the `lookupPathFromDecorator`, all I need from you as a reproduction is how the stack trace used by this method can look like. Btw the stack trace you provided does not contain any `file:///`, which is quite weird then.

**Comment by B4nan** [comment] 2022-01-25 09:19
I am still waiting for the reproduction, as said above, all I need is that example stack trace.

**Comment by B4nan** [comment] 2022-01-28 08:26
@PodaruDragos are you by any chance on windows? Could you help me with the stack trace here? 

otherwise will be closing ¯\_(ツ)_/¯

**Comment by PodaruDragos** [comment] 2022-01-28 08:59
@B4nan not at the time, will try to look at this maybe tomorrow, but no promisses.
I assume the problem here is the same as i had for migrations. the fix should be the same i think.

I had no problems with schema what so ever, but i can try to make an example to see if it breaks.

**Comment by B4nan** [comment] 2022-01-28 09:08
Basically all I need is the example stack trace that contains `file:///` urls on windows, just to see how it looks. So simply `console.log(new Error().stack)`, but from inside ESM on windows.

In other words, I need a unit test like those:

https://github.com/mikro-orm/mikro-orm/blob/master/tests/Utils.test.ts#L250

**Comment by B4nan** [comment] 2022-02-01 21:53
Not reproducible, will be happy to reopen if you provide failing repro.

**Closed by B4nan** 2022-02-01 21:53 UTC
Labels: needs clarification

**Comment by itsame-luigi** [comment] 2022-02-01 22:29
Here's an example of the stack trace I see in `Utils.lookupPathFromDecorator`:

```
Error
    at lookupPathFromDecorator (C:\project\node_modules\@mikro-orm\core\dist\utils\Utils.js:487:26)
    at Function.getMetadataFromDecorator (C:\project\node_modules\@mikro-orm\core\dist\metadata\MetadataStorage.js:26:36)
    at C:\project\node_modules\@mikro-orm\core\dist\decorators\Property.js:9:49
    at DecorateProperty (C:\project\node_modules\reflect-metadata\Reflect.js:553:33)
    at Reflect.decorate (C:\project\node_modules\reflect-metadata\Reflect.js:123:24)
    at __decorate (file:///C:/project/dist/db/entities/foo.js:3:92)
    at null.<anonymous> (C:\project\src\db\entities\foo.ts:16:5)
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
```

**Comment by itsame-luigi** [comment] 2022-02-01 23:57
I looked into crafting a test for this, but was not entirely successful. Jest gets in the way because it wants to control module resolution and passes everything through Babel.

The closest I could come was to do the following:

1. Create a `tests/issues/esm` folder.
2. Add `package.json` to `tests/issues/esm` with the contents `{ "type": "module" }`
3. Add `esmEntity.js` to `tests/issues/esm` with the contents below.
4. Add `GH2654.main.js` to `tests/issues/esm` with the contents below.
5. Add `GH2654.test.ts` to `tests/issues` with the contents below.
6. Run `yarn build` (build outputs are necessary, see below)
7. Run `yarn test -- --testPathPattern GH2654`

**tests/issues/esm/esmEntity.js**
```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
import { Entity, PrimaryKey } from "@mikro-orm/core";
let EsmEntity = class EsmEntity {
    constructor(id) {
        Object.defineProperty(this, "id", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        this.id = id;
    }
};
__decorate([
    PrimaryKey({ type: "string" })
], EsmEntity.prototype, "id", void 0);
EsmEntity = __decorate([
    Entity()
], EsmEntity);
export { EsmEntity };
```

**tests/issues/esm/GH2654.main.js**
```js
import { MikroORM } from '@mikro-orm/core';
import { EsmEntity } from "./esmEntity.js";

const orm = await MikroORM.init({
    entities: [EsmEntity],
    dbName: `:memory:`,
    type: 'sqlite'
});
await orm.close(true);

process.send(EsmEntity.__path);
```

**tests/issues/GH2654.test.ts**
```ts
import { it } from "@jest/globals";
import child_process from "child_process";
import path from "path";

describe('GH #2654', () => {
    (process.platform === "win32" ? it : it.skip)('should infer correct path for entity loaded from es module', async () => {
        const mainJs = path.join(__dirname, "./esm/GH2654.main.js");
        const proc = child_process.fork(mainJs, {
            env: {
                MIKRO_ORM_DYNAMIC_IMPORTS: "1"
            }
        });
        const filePath = await new Promise<string>((resolve, reject) => {
            proc.once("error", e => {
                proc.removeAllListeners();
                reject(e);
            });
            proc.once("message", message => {
                proc.removeAllListeners();
                if (typeof message !== "string") return reject(new Error("Unexpected message received."));
                resolve(message);
            });
            proc.once("exit", () => {
                proc.removeAllListeners();
                reject(new Error("Process exited before sending message."));
            });
        });

        expect(filePath).not.toMatch(/^file:\/[^\/]/);
    });
});
```

The test uses `child_process.fork` to launch a copy of NodeJS that starts by loading an ES Module (GH2654.main.js). This module is running outside of Jest, so it is necessary to have build outputs to import `@mikro-orm/core`. The module then initializes MikroORM using the `EsmEntity` entity, and then uses `process.send` to inform the running test of the path computed for the entity.

On my machine (running Windows), this results in the following test failure:

```
  ● GH #2654 › should be able to find entity with nested composite key

    expect(received).not.toMatch(expected)

    Expected pattern: not /^file:\/[^\/]/
    Received string:      "file:/C:/projects/mikro-orm/tests/issues/esm/esmEntity.js"

      29 |         });
      30 |
    > 31 |         expect(filePath).not.toMatch(/^file:\/[^\/]/);
         |                              ^
      32 |     });
      33 | });
      34 |

      at Object.<anonymous> (tests/issues/GH2654.test.ts:31:30)
```

I'm not sure there's a good way to reliably include this in the tests, since both Jest and ts-node want to get in the way of module resolution, which invalidates the test.

**Comment by itsame-luigi** [comment] 2022-02-02 01:25
I filed #2697 with the proposed changes above. The rather esoteric test I proposed [above](https://github.com/mikro-orm/mikro-orm/issues/2654#issuecomment-1027404674) merely proves that a stack trace may contain a `file://` URL, and is not necessary to verify that the path handling is accurate. Instead, I included tests directly in Utils.test.ts for the expected stack trace that NodeJS would produce in this circumstance.

**Comment by itsame-luigi** [comment] 2022-02-02 17:07
`initEnumValues` is a red herring. The issue is with the path passed to `dynamicImport`, which I traced back to path handling in `normalizePath`/`relativePath` used by `lookupPathFromDecorator`.

**Comment by itsame-luigi** [comment] 2022-02-02 17:08
I should say, it occurs in other places besides `initEnumValues` if there are no enums in the model.

**Comment by B4nan** [comment] 2022-02-02 17:12
> I should say, it occurs in other places besides initEnumValues if there are no enums in the model.

Well, we failed to reproduce that. It might easily be some other misconfiguration. 

https://github.com/vladfrangu/mikro-orm-esm-testing-grounds
