### ISSUE TITLE
Single table inheritance entities show properties from other entities

### ISSUE THREAD

**Issue by MartinAndreev** [mikro-orm/mikro-orm#4014] opened 2023-02-06 12:40 UTC
**Describe the bug**
I have a single-table inheritance model, where I have a base entity for a taxonomy.

```typescript
// abstract class, that comes from a shared library
export abstract class AbstractTaxonomy {
  @PrimaryKey({
    type: 'uuid',
    fieldName: 'id',
  })
  public id: string = v4();

  @Property()
  public name!: string;

  @Property({
    index: true,
    length: 20,
  })
  public type!: string;

  @Property({
    default: true,
    columnType: 'boolean',
  })
  public active = true;

  @Property({
    onCreate: () => new Date(),
  })
  public created!: Date;

  @Property({
    nullable: true,
    onUpdate: () => new Date(),
  })
  public updated?: Date | null = null;

  @Property({
    nullable: true,
    length: 30,
    index: true,
  })
  public code?: string | null = null;

  @Property({
    nullable: true,
    columnType: 'text',
  })
  public description?: string | null = null;

  @Property({
    nullable: true,
    columnType: 'jsonb',
  })
  public meta?: any = null;
}

// Used entities in the application

@Entity({
  tableName: 'taxonomy',
  abstract: true,
  discriminatorColumn: 'type',
})
export abstract class BaseTaxonomy extends AbstractTaxonomy {
  @Enum({
    index: true,
    items: () => GroupType,
  })
  public type!: GroupType;
}

// Couple of Entities that use the STI

@Entity({
  discriminatorValue: GroupType.ACCOUNT,
  customRepository: () => AccountRepository,
})
export class Account extends BaseTaxonomy {
  [EntityRepositoryType]?: AccountRepository;

  @CollectionToArray()
  @OneToMany({
    entity: () => User,
    mappedBy: (user: User) => user.account,
    cascade: [],
    strategy: LoadStrategy.SELECT_IN,
  })
  public users: Collection<User> = new Collection<User>(this);

  @CollectionToArray()
  @ManyToMany({
    entity: () => User,
    cascade: [],
    strategy: LoadStrategy.SELECT_IN,
    inversedBy: (user: User) => user.managerOf,
  })
  public managers: Collection<User> = new Collection<User>(this);

  @Exclude()  // workaround to prevent serialization
  private parent: any;

  @Exclude() // workaround to prevent serialization
  public children: any;

  @ApiProperty({
    type: () => AccountMeta,
  })
  @Embedded({
    entity: () => AccountMeta,
    nullable: true,
    object: true,
  })
  public meta?: AccountMeta;
}

@Entity({
  discriminatorValue: GroupType.BRANCH,
  customRepository: () => BranchRepository,
})
export class Branch extends BaseTaxonomy {
  @Embedded({
    entity: () => BranchMeta,
    nullable: true,
    object: true,
  })
  public meta?: BranchMeta = null;

  @CollectionToArray()
  @OneToMany({
    entity: () => Branch,
    mappedBy: (branch: Branch) => branch.parent,
    cascade: [Cascade.PERSIST, Cascade.REMOVE],
    strategy: LoadStrategy.SELECT_IN,
  })
  public children: Collection<Branch> = new Collection<Branch>(
    this,
  );

  @ReferenceToEntity()
  @ManyToOne({
    nullable: true,
    entity: () => Branch,
    wrappedReference: true,
    strategy: LoadStrategy.JOINED,
    inversedBy: (branch: Branch) => Branch.children,
  })
  public parent: IdentifiedReference<EFrontBranch>;

  @Exclude() // workaround to prevent serialization
  public users: any[];

  @Exclude() // workaround to prevent serialization
  public managers: any[];
}
```

When I do a simple findAll via the AccountRepository, I get a property mixup. I use the NestJS framework if it makes any difference.

The output of a simple console.log. Am I missing something? Same goes, for entities that dont have the meta property for example, it just loads it from some of the other STI entities.
```
[
  Account {
    id: '2229c987-3c53-4088-bd22-682033656688',
    name: 'Test',
    type: 'account',
    active: true,
    created: 2023-01-28T22:14:04.000Z,
    updated: null,
    code: null,
    description: null,
    meta: null,
    parent: null,
    test: undefined,
    users: Collection<User> { initialized: false, dirty: false },
    managers: Collection<User> { initialized: false, dirty: false },
    children: Collection<Branch> { initialized: false, dirty: false }
  },
  Account {
    id: '95904a2a-bb34-4340-9da7-5cf3d44741f5',
    name: 'Test 2',
    active: true,
    created: 2023-01-18T11:11:56.000Z,
    users: Collection<User> { initialized: false, dirty: false },
    managers: Collection<User> { initialized: false, dirty: false },
    meta: null,
    parent: null,
    children: Collection<Branch> { initialized: false, dirty: false },
    type: 'account',
    updated: null,
    code: null,
    description: null
  }
]

```

**To Reproduce**
1. Install and setup the mikro orm module inside a NestJS framework
2. Create the entities as listed above
3. Do a simple findAndCount 

**Expected behavior**
Show only properties that are part of this entity.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.15.0 |
| typescript | 4.3.5 |
| mikro-orm | 5.6.8 |
| @mikro-orm/nestjs | 5.1.6 |
| @nestjs/core | 9.3.2 |

**Comment by MartinAndreev** [comment] 2023-02-06 12:49
Also, this happens only, when fetched from the repository. The properties are missing, when a new entity is created.

**Comment by B4nan** [comment] 2023-02-06 13:01
Would be great if you could simplify this and turn it into a complete repro I can run myself - and nope, this won't be about nestjs, so ideally just a simple script using only the ORM. 

Btw I can't see what exactly you don't like about that console.log, remember, those are your entities, so please tell me what exactly is mixed up :] I see you are trying to redefine the properties with different types in the leaf entities, that will probably not work, and there is another issue for that iirc.

**Comment by B4nan** [comment] 2023-02-06 13:05
Yeah, sounds like a duplicate of #2388. I should look into that for v6.

**Comment by MartinAndreev** [comment] 2023-02-06 13:05
Hey @B4nan. Thanks for the fast reply. When I fetch the entity class, I get relationships, that are not part of this entity.

For example, the account does not have a parent and child, while the branch does not have users and managers, but when I fetch it from the repository, I get them as properties, which results in errors, when it tries to convert it to a plain object. For now, the workaround is to just define them as properties in each entity and call `@Exclude` on them, so the class-transformer, does not pick them and tries to convert them to plain objects.

**Comment by MartinAndreev** [comment] 2023-02-06 14:05
Ok, i will try to make a fresh repo, that reproduces the problem and will send you a link.

**Comment by MartinAndreev** [comment] 2023-02-06 17:36
@B4nan ok, so make an empty simple repo and dont see that behavior, which is super strange and I am at a dead end on what can cause the problem.

**Comment by B4nan** [comment] 2023-02-06 17:41
It if behaves like this locally, just copy your project and start simplifying as long as you can. Start with removing nestjs and turning it into a script, then remove all unrelated entities, then remove all unrelated properties in those entities, then simplify the ORM config as much as you can. Often you will find the culprit yourself on this path.

The first thing I would try in your case is removing the loading strategy overloads, joined strategy could result in different hydration.

**Comment by MartinAndreev** [comment] 2023-02-06 18:46
Loading strategy did not work. I managed to locate one module, that when loaded results in this problem, but I cant explain why.

The entity 

```
@Entity({
  discriminatorValue: GroupType.EFRONT_BRANCH,
  customRepository: () => EfrontBranchRepository,
})
export class EFrontBranch extends BaseTaxonomy {
  @Embedded({
    entity: () => EFrontBranchMeta,
    nullable: true,
    object: true,
  })
  public meta?: EFrontBranchMeta = null;

  @ReferenceToEntity()
  @ManyToOne({
    inversedBy: (branch: EFrontBranch) => branch.children,
    entity: () => EFrontBranch,
    wrappedReference: true,
    nullable: true,
  })
  public parent?: IdentifiedReference<EFrontBranch> | null;

  @CollectionToArray()
  @OneToMany({
    mappedBy: (branch: EFrontBranch) => branch.parent,
    entity: () => EFrontBranch,
    cascade: [],
  })
  public children: Collection<EFrontBranch> = new Collection<EFrontBranch>(
    this,
  );

  public async getChildren() {
    if (!this.children.isInitialized()) {
      await this.children.init();
    }

    return this.children.getItems();
  }

  public async addChild(child: EFrontBranch) {
    await this.getChildren();

    this.children.add(child);
  }

  public async removeChild(child: EFrontBranch) {
    await this.getChildren();

    this.children.remove(child);
  }

  public async getParent(): Promise<EFrontBranch> {
    if (!this.parent.isInitialized()) {
      await this.parent.load();
    }

    return this.parent.getEntity();
  }

  public setParent(parent: EFrontBranch): void {
    this.parent = Reference.create(parent);
  }
}
```

somehow appears in

```@Entity({
  discriminatorValue: GroupType.ACCOUNT,
  customRepository: () => AccountRepository,
})
export class Account extends BaseTaxonomy {
  @ApiProperty({
    type: () => User,
  })
  @CollectionToArray()
  @OneToMany({
    entity: () => User,
    mappedBy: (user: User) => user.account,
    cascade: [],
  })
  public users: Collection<User> = new Collection<User>(this);

  @ApiProperty({
    type: () => User,
  })
  @CollectionToArray()
  @ManyToMany({
    entity: () => User,
    cascade: [],
    inversedBy: (user: User) => user.accountManagerOf,
  })
  public managers: Collection<User> = new Collection<User>(this);

  @ApiProperty({
    type: () => AccountMeta,
  })
  @Embedded({
    entity: () => AccountMeta,
    nullable: true,
    object: true,
  })
  public meta?: AccountMeta;

  public async getUsers() {
    if (!this.users.isInitialized()) {
      await this.users.init();
    }

    return this.users.getItems();
  }

  public async addUser(user: User) {
    await this.getUsers();

    this.users.add(user);
  }

  public async removeUser(user: User) {
    await this.getUsers();

    this.users.remove(user);
  }

  public async getManagers() {
    if (!this.managers.isInitialized()) {
      await this.managers.init();
    }

    return this.managers.getItems();
  }

  public async addManager(user: User) {
    await this.getManagers();

    this.managers.add(user);
  }

  public async removeManager(user: User) {
    await this.getManagers();

    this.managers.remove(user);
  }

  public async isManager(user: User) {
    await this.getManagers();

    return this.managers.contains(user);
  }
}
````


````
Account {
   id: '2229c987-3c53-4088-bd22-682033656688',
   name: 'Test',
   type: 'account',
   active: true,
   created: 2023-01-28T22:14:04.000Z,
   updated: null,
   description: null,
   meta: null,
   users: Collection<User> { initialized: false, dirty: false },
   managers: Collection<User> { initialized: false, dirty: false },
   parent: null,
   children: Collection<EFrontBranch> { initialized: false, dirty: false }
 },
````

**Comment by MartinAndreev** [comment] 2023-02-06 18:59
I think i will just remove the STI, it might become a bigger problem, when the project goed to production and starts to grow.

**Comment by MartinAndreev** [comment] 2023-02-06 19:00
Its still in early stage and it wont be a problem, to do it now.

**Comment by B4nan** [comment] 2023-02-09 07:19
I guess I will close this then, as it's not surfacing on my end, and I still have a hunch it will be connected to #2388 which I'd like to deal with in v6 anyway. Let's reopen with a failing reproduction.

**Closed by B4nan** 2023-02-09 07:19 UTC
