### ISSUE TITLE
Combine concurrent identical queries into one.

### ISSUE THREAD

**Issue by TheNightmareX** [mikro-orm/mikro-orm#2470] opened 2021-11-27 11:38 UTC
**Is your feature request related to a problem? Please describe.**
When the same query is executed multiple times before one of them completes, many duplicate database calls are generated.

For example, the following ORM queries will produce two identical SQL queries.

```ts
// no `await` here, they are concurrent.
repo.findOne(1);
repo.findOne(1);
```

In a GraphQL batch request, there will be multiple queries which will be executed concurrently, so there may be a lot of redundant DB calls because of this.

**Describe the solution you'd like**
Maybe there could be a _Pending Query Map_. Its keys are SQL statements which is pending, and its values are results of those pending SQL statements. After generating the SQL statements and before actually executing the SQL statements, we can check whether the SQL statement to execute is pending and return the promise directly if so?

**Comment by B4nan** [comment] 2021-11-27 11:43
Duplicate of #266

**Closed by B4nan** 2021-11-27 11:43 UTC
Labels: enhancement

**Comment by B4nan** [comment] 2021-11-27 11:45
You might be interested in this: https://github.com/mikro-orm/mikro-orm/commit/c0b8f11379cd01e7a605959ef87bfe681c550c2d#diff-e4aaabcfd2b04489dd5e4e2204906a963c5e66c48e2d9f75c2f371d8899c2bf3R30

**Comment by TheNightmareX** [comment] 2021-11-27 12:00
They are different, I already have dataloaders in my project.

What I mean is to avoid DB calls when the target query is in progress, while dataloaders are to combine 
different queries into one query. They are not the same.

What I mean is that the following statements should produce only one DB call:

```ts
repo.find({ some complex conditions }, { some complex options })
repo.find({ the same conditions }, { the same options })
repo.find({ the same conditions }, { the same options })
repo.find({ the same conditions }, { the same options })
```

And #266 means to combine the following queries:

```ts
repo.findOne(1)
repo.findOne(2)
repo.findOne(3)
```

into:

```ts
repo.find({ id: { $in: [1,2,3] } })
```

**Comment by B4nan** [comment] 2021-11-27 12:07
I can't really see how that could work, if you believe you know how to implement it, feel free to give it a try. There would still need to be some kind of data loader to do the work in the next tick, and given how nested the async calls are, I don't think we can expect to know the actual SQL before executing all of the calls (as it involves async calls to build it). But this field is quite distant to me, maybe my tests with data loader were wrong, so again, if you know how, feel free to give it a try.

**Comment by darkbasic** [comment] 2023-09-07 10:50
> What I mean is that the following statements should produce only one DB call:
```
repo.find({ some complex conditions }, { some complex options })
repo.find({ the same conditions }, { the same options })
repo.find({ the same conditions }, { the same options })
repo.find({ the same conditions }, { the same options })
```

@TheNightmareX this is impossible. What can be done is the following:
```
await Promise.all([
  repo.find({ some complex conditions }, { some complex options }),
  repo.find({ the same conditions }, { the same options }),
  repo.find({ the same conditions }, { the same options }),
  repo.find({ the same conditions }, { the same options }),
]);
```

That can be turned into a single db call.

I suggest you to have a look at this PR: https://github.com/mikro-orm/mikro-orm/pull/4321

That PR is limited to references/collections, but I've already implemented what you ask for (minus the `Promise.all` which is mandatory, unless you make multiple calls into the same tick of the event loop) into its own third party library. I will release it once the other dataloaders get merged.
