### ISSUE TITLE
Make `ref` creation child persistence behaviour configurable with `persist: "relation" | "insert"` option   

### ISSUE THREAD

**Issue by QuestionAndAnswer** [mikro-orm/mikro-orm#4027] opened 2023-02-09 08:11 UTC
**Is your feature request related to a problem? Please describe.**

So, currently there is a bit of a zoo in regards of References and their related approaches, and documentation is good and bad in the same time on them.

There are the ways to create references:
1. `rel` which is `Reference.createNakedFromPK`. This one should be used for POJO entities, as far as I understood. Documentation on this part is really short.
1. `ref` which is `Reference.create` or `Reference.createFromPK` depending on the call signature. This one should be used for entity classes to create references on entities.
1. `em.getReference` which is creates reference in identity map and has to be used if one wants to create parent, without child propagation (child already exist, and only reference itself need to be persisted)
1. `wrap(entity).assign({}, { em: em })` which is the write data into entities method with `em.getReference` behaviour in terms of identity map.

As I am more of a procedural/functional programming style guy, I considered writing pure small and primitive functions first, and mostly used `ref` calls on constructor call entities (because this not requires me to drag em as call argument everywhere), to finally find out about this identity thing and points 3 and 4.

So I used something like
```typescript
function create(input: MyData) {
  const entity = new Entity();
  
  entity.collectionProp.set(input.childIds.map(x => ref(ChildEntity, x)));
  entity.refProp = ref(ChildEntity, input.anotherChildId);
  
  return entity;
}

async function useFunction(em: EntityManager) {
   const entity = create({ childIds: [1,2,3], anotherChildId: 88 });
   
   em.persist(entity);
   
   await em.flush();
}
```
And this would lead to childs, both in collection and reference fields, insertion, when I wanted only relation insert.

and now I have to rewrite a lot like this:
```typescript
function create(em: EntityManager, input: MyData) {
  const entity = new Entity();
  
  entity.collectionProp.set(input.childIds.map(x => em.getReference(ChildEntity, x)));
  entity.refProp = em.getRefernece(ChildEntity, input.anotherChildId);
  
  return entity;
}

async function useFunction(em: EntityManager) {
   const entity = create(em, { childIds: [1,2,3], anotherChildId: 88 });
   
   em.persist(entity);
   
   await em.flush();
}
``` 

And I think there must be an easier way, to keep function's purity (obviously it's easier to reason about and test the function when it is not relying on em), and have persisting configurable on dynamically.

**Describe the solution you'd like**
So, instead of having to drag this `EntityManager` everywhere, pure ref signature can be extended with option of persist action `relation` | `insert`, like this.

```typescript
function create(input: MyData) {
  const entity = new Entity();
  
  entity.collectionProp.set(input.childIds.map(x => ref(ChildEntity, x, { persist: 'relation' })));
  entity.refProp = ref(ChildEntity, input.anotherChildId, { persist: 'relation' });
  
  return entity;
}

async function useFunction(em: EntityManager) {
   const entity = create({ childIds: [1,2,3], anotherChildId: 88 });
   
   em.persist(entity);
   
   await em.flush();
}
```

**Describe alternatives you've considered**
1. Create separate ref creation methods: like `refExisting` and `refInsert`, or shortcuted `refEx` and `refIn`. But adding this new signatures would be an overkill I think, as those 4 ways are already a bit too much for me. But this is subjective.
1. Allow persistence configuration on entity definition level with decorators options. There is already this `cascade: []` thing, but as documentation states, it will be ignored if nothing in identity map yet. In one of the issues you already wrote that this is persistence by reachability. I'm not sure why we can't have both behaviours configured via separate options, though. Option like persist: `relation` | `insert` would work on this level. In this case it would be configured statically. For my use case this also works. 

**Additional context**
My use case is mostly CRUD app, with 20 different entities, polymorphic relations and a lot of different static references.
The flow of a call looks like:
1. Validate input.
1. Create an entity from a validated POJO. Deep inserts only for value objects. All domain entities are split to be created on a separate steps. Basically everything which has an id, shall create relations only, instead of deep inserts, on this step.
1. Persist.
1. Return response.

**Comment by B4nan** [comment] 2023-02-09 08:16
The whole point of using `rel/ref` is that it will never trigger insert query, it gives you managed reference to some entity = representation of FK. You need to create entity instances yourself if you want them to trigger insert.

**Comment by B4nan** [comment] 2023-02-09 08:25
I think you should provide a complete repro for the problem you have, as quite a lot of what you wrote above seems incorrect/not expected.

> rel which is Reference.createNakedFromPK. This one should be used for POJO entities, as far as I understood. Documentation on this part is really short.

Not sure what a POJO entity is in your terms, `rel` is for creating naked reference based on a FK. You should use that if your relation property is _not_ using the reference wrapper (aka `Ref` or `IdentifiedReference`).

> ref which is Reference.create or Reference.createFromPK depending on the call signature. This one should be used for entity classes to create references on entities.

`ref` is the same as `rel`, it just wraps the returned value in the reference wrapper

> em.getReference which is creates reference in identity map and has to be used if one wants to create parent, without child propagation (child already exist, and only reference itself need to be persisted)

`em.getReference` is what is used under the hood for both of them, it does the same as `rel` - `rel/ref` was added so you don't need to hold the EM reference

> wrap(entity).assign({}, { em: em }) which is the write data into entities method with em.getReference behaviour in terms of identity map.

This is not really related to the above anyhow. Assigning uses references as well as creates new entities, based on what you feed in. A FK is considered as reference (will use `em.getReferece`, an object is considered a new entity (will use `em.create`).

**Comment by QuestionAndAnswer** [comment] 2023-02-09 08:44
Okay. That's strange. I debugged the code and saw the lines when it is checking that my referenced entity is not in em's identity map and hence considered it as something for insertions. 

I'll try to make a reproduce.

**Comment by B4nan** [comment] 2023-02-09 08:49
> Okay. That's strange. I debugged the code and saw the lines when it is checking that my referenced entity is not in em's identity map and hence considered it as something for insertions.

Well, depends on where, depends on how you configure things. You can get this behavior from `assign`, but not from the other methods you mentioned, they should never produce any insert queries.

The behavior around assign is described in the docs, if you want updates from it, you either need to pass the FK value (not an object) into reference properties, or you need to ensure the entity you want to update is already loaded into context - as you can never get update query from UoW for entity that wasn't first loaded, the UoW computes changes you made on the entity instance after it was loaded, so not loaded = no state = no updates.

**Comment by QuestionAndAnswer** [comment] 2023-02-09 09:27
So, here is the repro.

https://github.com/QuestionAndAnswer/mikro-orm-test/tree/issue/4027

I've enabled the mikro orm logging, and here is the log:

entity.ts
```typescript
@Entity()
export class Parent {
  @PrimaryKey()
  id!: string;

  @Property()
  createdAt!: Date;

  @ManyToMany({ owner: true, cascade: [] })
  refs = new Collection<Child>(this);
}

@Entity()
export class Child {
  @PrimaryKey()
  id!: string;

  @Property()
  createdAt!: Date;
}
```

index.ts
```typescript

async function bootstrap() {
  const orm = await MikroORM.init(mikroOrmConfig);
  await orm.getMigrator().up();

  // Child entity create

  let em = orm.em.fork();

  const e2 = new Child();
  e2.id = randomUUID();
  e2.createdAt = new Date();

  em.persist(e2);

  await em.flush();

  // Parent referencing child create

  em = orm.em.fork();
  const e1 = new Parent();
  e1.id = randomUUID();
  e1.createdAt = new Date();
  e1.refs.set([ref(Child, e2.id)]);

  em.persist(e1);

  await em.flush();

  return orm;
}

bootstrap().catch((err) => console.error(err));
```

```
> mikro-orm-bug@1.0.0 start
> ts-node src/index.ts

[info] MikroORM version: 5.6.8
[discovery] ORM entity discovery started, using TsMorphMetadataProvider
[discovery] - processing 1 files
[discovery] - processing entity Parent (/Users/username/Projects/mikro-orm-bug/src/entity.ts)
[discovery] - processing entity Child (/Users/username/Projects/mikro-orm-bug/src/entity.ts)
[discovery] - entity discovery finished, found 3 entities, took 740 ms
[info] MikroORM successfully connected to database mikro-orm-test on postgresql://postgres:*****@127.0.0.1:5432
[query] select 1 from pg_database where datname = 'mikro-orm-test' [took 0 ms]
[query] select 1 from pg_database where datname = 'mikro-orm-test' [took 2 ms]
[query] select table_name, table_schema as schema_name, (select pg_catalog.obj_description(c.oid) from pg_catalog.pg_class c where c.oid = (select ('"' || table_schema || '"."' || table_name || '"')::regclass::oid) and c.relname = table_name) as table_comment from information_schema.tables where "table_schema" not like 'pg_%' and "table_schema" not like 'crdb_%' and "table_schema" not like '_timescaledb_%' and "table_schema" not in ('information_schema', 'tiger', 'topology') and table_name != 'geometry_columns' and table_name != 'spatial_ref_sys' and table_type != 'VIEW' order by table_name [took 8 ms]
[query] begin
[query] select * from "public"."mikro_orm_migrations" order by "id" asc [took 1 ms]
Processing 'Migration20230209090552'
[query] savepoint trx3
[query] create table "child" ("id" varchar(255) not null, "created_at" timestamptz(0) not null, constraint "child_pkey" primary key ("id")); [took 5 ms]
[query] create table "parent" ("id" varchar(255) not null, "created_at" timestamptz(0) not null, constraint "parent_pkey" primary key ("id")); [took 3 ms]
[query] create table "parent_refs" ("parent_id" varchar(255) not null, "child_id" varchar(255) not null, constraint "parent_refs_pkey" primary key ("parent_id", "child_id")); [took 7 ms]
[query] alter table "parent_refs" add constraint "parent_refs_parent_id_foreign" foreign key ("parent_id") references "parent" ("id") on update cascade on delete cascade; [took 5 ms]
[query] alter table "parent_refs" add constraint "parent_refs_child_id_foreign" foreign key ("child_id") references "child" ("id") on update cascade on delete cascade; [took 2 ms]
[query] release savepoint trx3
[query] insert into "public"."mikro_orm_migrations" ("name") values ('Migration20230209090552') [took 2 ms]
Applied 'Migration20230209090552'
[query] commit
[query] begin
[query] insert into "child" ("id", "created_at") values ('19c9bf87-bee5-481e-944f-252e1b78ff23', '2023-02-09T09:06:34.035Z') returning "id" [took 1 ms]
[query] commit
[query] begin
[query] insert into "parent" ("id", "created_at") values ('9cc9df5b-199b-467b-aa0e-31609d7d367c', '2023-02-09T09:06:34.039Z') returning "id" [took 2 ms]
[query] rollback
ValidationError: Value for Child.createdAt is required, 'undefined' found
entity: (Child) { id: '19c9bf87-bee5-481e-944f-252e1b78ff23' }
    at Function.propertyRequired (/Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/errors.js:64:16)
    at EntityValidator.validateRequired (/Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/entity/EntityValidator.js:49:48)
    at ChangeSetPersister.processProperties (/Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:77:28)
    at /Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:24:46
    at Array.forEach (<anonymous>)
    at ChangeSetPersister.executeInserts (/Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:24:20)
    at ChangeSetPersister.runForEachSchema (/Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:31)
    at ChangeSetPersister.executeInserts (/Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:21:25)
    at UnitOfWork.commitCreateChangeSets (/Users/username/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:715:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  entity: (Child) { id: '19c9bf87-bee5-481e-944f-252e1b78ff23' }
}
```

I've added createdAt property specifically, as this is the way to demonstrate the issue. On the parent insert step, while I'm using `ref` call, it still trying to insert `Child`, but failing, because ref obviously doesn't have required field `createdAt`.

So, is it a bug, or I'm doing something wrong?

**Comment by B4nan** [comment] 2023-02-09 09:32
>  @ManyToMany({ owner: true, cascade: [] })

You are disabling cascade persist this way, I doubt you want that, and it could have weird side effects, even on your repro here.

**Comment by QuestionAndAnswer** [comment] 2023-02-09 09:35
What do you mean? It is describe in the docs, that if I don't want to have cascade persisting (like disable cascade create, delete and etc.), I need to set cascade: [].

What else can I do? Or how to achieve what I want without `wrap.assign`?

**Comment by QuestionAndAnswer** [comment] 2023-02-09 09:44
Additionally, I think this is intended behaviour, I mean the bug which I see, as per documentation you've written this

> New entities without primary key will be always persisted, regardless of cascade value.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/6842709/217776389-3a256bbb-a14f-42a2-98be-ae11dd1c1a38.png">

So, idk. You confusing me now, when saying it should work, but docs saying the opposite.

**Comment by B4nan** [comment] 2023-02-09 09:55
I think I will just remove the possibility to disable cascade persist. The defaults are what you want 99% of the time I'd say.

> What do you mean? It is describe in the docs, that if I don't want to have cascade persisting (like disable cascade create, delete and etc.), I need to set cascade: [].

But why would you want to disable cascade persist? Do you understand what it does? It just makes the entities you put into the property automatically persisted. That does not affect whether they produce some query, neither it controls if its insert or update.

> What else can I do? Or how to achieve what I want without wrap.assign?

Your repro has no assign call, so idk what you are asking for here?

> New entities without primary key will be always persisted, regardless of cascade value.

Yes, this is called persistence by reachability. It protects you from failed flush calls. If there is an entity in the graph in a relation property, we need to know its PK, hence it needs to be persisted. 

> So, idk. You confusing me now 🙂, when saying it should work, but docs saying the opposite.

Lol, you came here confused in the first place, as seen in the OP :P I don't see what contradiction you see if what I said. That line in the docs is not relevant for your repro, your entity has known PK, not autoincrement one.

Anyway, this looks like a bug.

**Comment by QuestionAndAnswer** [comment] 2023-02-09 10:12
> But why would you want to disable cascade persist? Do you understand what it does? It just makes the entities you put into the property automatically persisted (=em.persist gets called for it, that is no-op for a managed entity). That does not affect whether they produce some query, neither it controls if its insert or update.

To be on a safe side, that no entities are created if I write something wrong on other parts of the code. Let's say, just as another safe belt. I wan't ORM to throw me an error, if I will try to persist more than I wan't during the call. This is mostly the reason.

> Your repro has no assign call, so idk what you are asking for here?

Should it? I mean, for the docs, it is said that assign call is only one of the way. So, that means I still should be able to populate all of the fields manually. Right?

> Yes, this is called persistence by reachability. It protects you from failed flush calls. If there is an entity in the graph in a relation property, we need to know its PK, hence it needs to be persisted.

That's okay with me, but then it is returning us exactly to the issue I've described. Let's clarify, when you referring to this term, we are looking if entity's identity is reachable. Which can be either entity instance itself, or reference. Right?
In this case, when you saying it is a bug, the bug is that reference on some step wasn't considered as entity identity, and instead treated as new, and because of this insert query getting through. Did I get this right?

Because I can't figure out at this step neither workarounds with what orm gives me, neither of what kind of fix to expect.

**Comment by B4nan** [comment] 2023-02-09 10:27
> Should it? I mean, from the docs, it is said that assign call is only one of the way. 

What docs do you mean? The only way for what? Assign is not special, it only does things you can do manually, it is a helper that does similar things as `Object.assign` but respects the references and collections and is EM aware let's say. You can do everything it does yourself (of course, with more code than a single line). All assign is doing is using public APIs.

> That's okay with me, but then it is returning us exactly to the issue I've described. Let's clarify, when you referring to this term, we are looking if entity's identity is reachable. Which can be either entity instance itself, or reference. Right?

The confusing part here is the word "reference" as it refers to both entity instance as well as reference wrapper (which is still an entity instance, just wrapped in the `Reference` class). There is no other difference between "entity instance" and "entity reference". The reference can point to initialized (loaded) entity or not initialized entity (just PK). The docs are a bit fractured here, as initially a reference was called "not initialized entity instance", then the reference wrapper was added, etc.

> In this case, when you saying it is a bug, the bug is that reference on some step wasn't considered as entity identity, and instead treated as new, and because of this insert query getting through. Did I get this right?

Yeah, the code you have should not try to insert the child again. Haven't checked the repro yet, I am quite swamped with other things today.

**Comment by QuestionAndAnswer** [comment] 2023-02-09 10:30
Alright. I'll figure out another ongoing issue I have, and try to see what can I do from my side to solve the issue.

**Comment by B4nan** [comment] 2023-02-10 09:21
The `ref/rel` were implemented only for m:1/1:1 properties, and you are trying to pass it into a collection so that's what is broken. But what I said about cascading applies here, if you disable it on the collection, this feature cannot work at all, you need cascade persist. I guess I will really remove the configurability of cascade persist from v6. It might have some meaning in earlier versions (before all the propagation was implemented), but now I don't think it has any real use case.

**Comment by QuestionAndAnswer** [comment] 2023-02-10 10:18
I still not quite sure how `cascade: []` relates to a problem. As I wrote, I disabled cascading just as an additional safety mechanism, to ensure no entities created where I don't need them to. And this is dictated by the app nature. I split my API to accept smaller chunks of hierarchical data, instead of having to persist whole hierarchy at once.

In (documentation)[https://mikro-orm.io/docs/cascading] it is said:
> When persisting or removing entity, all your references are by default cascade persisted. This means that by persisting any entity, ORM will automatically persist all of its associations.

There are two parts in this quote:
1. references cascading
2. entities cascading 

I need to persist references without entities. You saying that what to do, is it reference or entity needs to be cascaded, can be inferred from is it actually reference wrapper we are looking at, or actual entity instance. Therefore, `cascade: []` makes no sense. Did I get this right?

If yes, then that's okay, but seems like there is still a bug somewhere. 
I've replaced in my repro `ref` to `rel` call, and removed `cascade: []` from the entity definition. Still I get the same error. What am I doing wrong? 🫠

**Comment by B4nan** [comment] 2023-02-10 10:43
As I said, entity and reference are pretty much the same thing. Reference means "reference to entity", so in that sentence, it refers to the relation properties. Entity can be wrapped in the reference wrapper, but it is still an entity. Not initialized entity is again still just an entity. 

> I need to persist references without entities

No, I don't think you _need_ that. That is my whole point. Try removing those `cascade: []` from your code, I doubt anything will change. If the relation property holds a managed entity, it has no effect, as managed entities are all persisted during flush and checked for changes. If it is not managed entity, it will be persisted due to persistence by reachability. 

> I've replaced in my repro ref to rel call, and removed cascade: [] from the entity definition. Still I get the same error. What am I doing wrong? 🫠

I said it is a bug, and that this was implemented only for m:1/1:1 relations. So don't expect it to work, if it would be working, I'd close the issue already. 

> I need to persist references without entities. You saying that what to do, is it reference or entity needs to be cascaded, can be inferred from is it actually reference wrapper we are looking at, or actual entity instance. Therefore, cascade: [] makes no sense. Did I get this right?

No, I don't think it makes sense, it is not doing what you think. In fact, it is not doing anything in vast majority of setups, can't think of a real use case to be honest.

**Comment by QuestionAndAnswer** [comment] 2023-02-10 11:13
> No, I don't think you need that. That is my whole point. Try removing those cascade: [] from your code, I doubt anything will change (I mean generally in your app, not just in the repro). If the relation property holds a managed entity, it has no effect, as managed entities are all persisted during flush and checked for changes. If it is not managed entity, it will be persisted due to persistence by reachability.

So this part really frustrating. The contradiction arises from managed/not managed cases. Assume m:m refs persistence is implemented and working, so, I'm able to persist the references. It doesn't make sense for any relation cardinality:

1. Database already has child entity with id: 1 (C1)
2. I receive request to create parent entity (P) which holds the reference on C1.
3. I create P via constructor call. It is not managed for entity manager (EM).
4. I create ref(C1) and assigning it into P. If C1 is still an entity in your definition, then it is also not managed.
5. I'm trying to persist P. Cascading goes through P's fields and reaches C1. As C1 is not managed it trying to persist it. 
  5.1 If it is 1:1, I'd need only id field to be saved on the owner side. But it will not, because C1 is not managed.
  5.2 If it is 1:m, the same as for 5.1, only ref_id persistence query needs to be issues, but it will not, because C1 is not managed.
  5.3 if it is m:m, only relation entity needs to be inserted (P_id, C_id). But it will try to insert not only that, it will try to insert C1, with already existing id, which should lead to a database level.

I mean, I understand what you are saying. I don't understand how it is suppose to work on practice. Each request starting with an empty identity map, therefore any reference persistence, instead of either optimistic child entity update with ref on P_id or insert of m:m relation record, will try also to persist incomplete entity hidden under the reference (because they are still not managed).

This whole approach only works if children which needs to be referenced are already in the identity map. The only way to make this work is to load into the context 10, 50, 100, children entities (findOne, or find calls). And this seems like overkill. I don't need to have to go to a database for that, and reimplementing application level reference integrity check, rather than relying on existing database's one. Is it the conceptual way you are proposing, or I get it all wrong?

**Comment by B4nan** [comment] 2023-02-10 11:27
You keep describing how it works now - once again, there is a bug. In your example, `ref(c1)` should never produce any query, regardless of what kind of relation it is. And that `c1` entity should be persisted - but not in the sense you probably think - it should become managed by the EM automatically, but it doesn't mean it should produce any query. Your code should not produce insert query for the `ref()` item. 

So let me fix that and then we can talk about your other thoughts, and for that, I would also want to see complete reproductions so it is clear what you are trying to tell me.

**Comment by QuestionAndAnswer** [comment] 2023-02-10 11:32
I thought there is a bug for m:m not for 1:1 or 1:m. I'm just running conceptually what you saying in my head and getting these results, and those are not matching either on what is working at the moment.
If ref's are become managed by EM automatically, then this solves the issue in the flow I've described. Then, only m:m are missing the fix.

Thanks for being patient)

**Comment by B4nan** [comment] 2023-02-10 11:57
> and those are not matching either on what is working at the moment.

Then provide a repro for that, it works fine for m:1/1:1 on my end. 

> If ref's are become managed by EM automatically, then this solves the issue in the flow I've described. Then, only m:m are missing the fix.

Yeah the whole point of this (quite new) `rel/ref` helpers is that you create them without the link to EM, but they will get managed automatically during flush - before the changesets are computed, so it will not have any effect on the queries. 

Basically when you do this:

```ts
book.author = ref(Author, 123);
await em.persist(book).flush();
```

It should behave the same as this:

```ts
book.author = em.getReference(Author, 123);
await em.persist(book).flush();
```

**Closed** 2023-02-10 18:07 UTC
Labels: bug
