### ISSUE TITLE
Migration error when mapping unidirectional entity using @ManyToOne with a composite foreign key.

### ISSUE THREAD

**Issue by ZilRahman** [mikro-orm/mikro-orm#1687] opened 2021-04-15 21:02 UTC
**Describe the bug**
So, I might just not "get" how to model mikro-orm entities, but I am facing an issue when I go to make unidirectional `@ManyToOne` migrations.

I have 4 entities: `Country`, `State`, `City`, and `User`. I want to create a `@ManyToOne` relation between a `User` and a `City` (using the city id I can access the state and country in the em later on thanks to the city's composite primary key).

Goal is that many users can belong to one city.

[Sample Repo](https://github.com/ZilRahman/mikro-orm-error)

Here is what my entities look like:

````
@Entity()
export class Country {

    @PrimaryKey()
    id!: number;

    @Property()
    name!: string;

    @Property()
    currency!: string

    @Property()
    currencySymbol!: string

    @OneToMany(() => State, state => state.country, { cascade: [Cascade.ALL], nullable: true })
    states = new Collection<State>(this);


}
````

````
@Entity()
export class State {
    
    @ManyToOne(() => Country, {primary: true})
    country!: Country;

    @PrimaryKey()
    id!: number;

    @Property()
    name!: string;

    @OneToMany(() => City, city => city.state, {cascade: [Cascade.ALL], nullable: true})
    cities = new Collection<City>(this);

    [PrimaryKeyType]: [number, number];


}
````

Notice the composite key on the city entity.
````
@Entity()
export class City {

    @ManyToOne(()=> State, {primary: true})
    state!: State

    @PrimaryKey()
    id!: number;

    @Property()
    name!: string;

    [PrimaryKeyType]: [number, number, number];

}
````

Finally, the user. This is where the problem lies.

````
@Entity()
export class User {

    @PrimaryKey()
    id!: string;

    @Property()
    email!: string;

    @OneToOne(()=> UserImage, (image)=> image.user, {owner: true, nullable: true})
    profile_image?: UserImage;

    @Property({nullable: true})
    first_name?: string;

    @Property({nullable: true})
    last_name?: string;

    @Property({columnType: "date", nullable: true})
    date_of_birth?: Date;


    @Property({columnType: "timestamptz", nullable: false})
    created = new Date();


    @Property({columnType: "timestamptz", onUpdate: () => new Date().toISOString() })
    modified = new Date();

    
    // Crux of the issue.
    @ManyToOne()
    city: City;


}
````

Everything works fine until I go and run migrations, and boom it gives me this error.

**Stack trace**
```
InvalidFieldNameException: alter table "user" add constraint "user_city_state_country_id_city_state_id_city_id_foreign" foreign key ("city_state_country_id", "city_state_id", "city_id") references "city" ("state_country_id", "state_id", "id") on update cascade; - column "city_id" referenced in foreign key constraint does not exist
    at PostgreSqlExceptionConverter.convertException (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:34:24)
    at PostgreSqlDriver.convertException (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
    at /Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Function.runSerial (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/@mikro-orm/core/utils/Utils.js:472:22)
    at /Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/@mikro-orm/migrations/MigrationRunner.js:23:17
    at PostgreSqlConnection.transactional (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:53:25)
    at MigrationRunner.run (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/@mikro-orm/migrations/MigrationRunner.js:20:13)
    at Parser.parseErrorMessage (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/zil/Downloads/express-ts-example-app-e875544b9f6d1ba822c37be82ab0d90564f8e0e3/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:378:20)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**To Reproduce**
1. Create these entities.
2. Run migrations.

**Expected behavior**
I should be able to see a new column added to the `user` table. But its not there.

**Additional context**
I am using type-grapqhl and apollo-express.

**Versions**

| Dependency | Version |
| - | - |
| node | 15.10.0 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.3 |
| pg | 8.6.0 |

**Comment by B4nan** [comment] 2021-04-16 07:57
Few notes:

1. the problem is already in your initial migration, there is no `user.city_id` column at all. 
2. issues like this has literally nothing to do with migrations - it is about `SchemaGenerator`
3. if you want to make it more friendly for me, single file reproductions are much easier to work with

Anyway, with #1641 this is not reproducible, so it will be addressed in v5. No plans to do any changes to schema diffing in v4.

**Comment by ZilRahman** [comment] 2021-04-16 14:58
Thanks a lot! I was able to temporarily fix it by adding a `user.city_id` column in the migration file.

**Comment by ZilRahman** [comment] 2021-04-16 18:13
Sorry for this noob question but I am facing issues when inserting data now.

The composite key values for the city get converted into json for some reason.

This is what my code looks like:
````
const newUser = new User(user.id, user.email)
        newUser.first_name = user.first_name
        newUser.last_name = user.last_name
        newUser.date_of_birth = user.date_of_birth

        const city = await em.findOneOrFail(City, {id: 16152})
        newUser.city = city
        await em.persistAndFlush(newUser);
        
````


Error:
````
"insert into \"user\" (\"city_id\", \"city_state_country_id\", \"city_state_id\", \"created\", \"date_of_birth\", \"email\", \"first_name\", \"id\", \"last_name\", \"modified\", \"status\") values (NULL, '{\"country\":1,\"id\":866}', 16152, '2021-04-16T18:09:51.707Z', '1995-04-12T00:00:00.000Z', 'test@gmail.com', 'Zil', '3f1f8783-8e27-473d-852e-93c94c4f270b', 'R', '2021-04-16T18:09:51.707Z', true) returning \"id\" - invalid input syntax for integer: \"{\"country\":1,\"id\":866}\""
````

**Comment by B4nan** [comment] 2021-04-16 21:06
That's another issue, try `4.5.4-dev.9`, should be addressed there.

**Closed** 2021-04-16 21:12 UTC
Labels: bug
