### ISSUE TITLE
Entities created by mikro's internals that also include private class fields throw an error

### ISSUE THREAD

**Issue by vladfrangu** [mikro-orm/mikro-orm#1226] opened 2020-12-21 14:55 UTC
**Describe the bug**

I started recently using mikro-orm in my projects, and it works beautifully (❤️), however I encountered an issue with an Entity that also uses private class fields (used to store variables that are unrelated to the data itself, but are needed for the structure). Thanks to @kyranet, we found the issue to be this line in EntityFactory

```ts
// creates new entity instance, bypassing constructor call as its already persisted entity
const entity = Object.create(meta.class.prototype);
```

This is fine for normal usage, and even for fields that are soft-privates (annotated with the `private` keyword in TS, but NOT using the `#` types of privates). I don't know if this is easy to solve, or if we should just not use private class fields with mikro-orm (something I don't directly mind, but would be a nice to have)

**Stack trace**
```
Encountered unexpected error: TypeError: Cannot write private member #client from an object whose class did not declare it
    at ScheduleEntity.setup (C:\Users\Vlad\Desktop\Development\TypeScript\TicketBot\dist\lib\schedule\ScheduleEntity.js:47:26)
    at ScheduleManager.init (C:\Users\Vlad\Desktop\Development\TypeScript\TicketBot\dist\lib\schedule\ScheduleManager.js:16:38)
```

**To Reproduce**
1. Create a simple entity with a private field
```ts
@Entity()
export class Example {
	@PrimaryKey()
	public id!: number;

	#myPrivateProp!: boolean;

	public setup(isAwesome: boolean) {
		this.#myPrivateProp = isAwesome;
	}
}
```
2. Attempt to construct it within your code, and persist it to the database
```ts
// This code sample will work just fine
const entry = new Example();
example.setup(true);

await em.persistAndFlush(entry);
```
3. Attempt to fetch an entity with a private class field, and try to read/write to the private properties
```ts
const fetchedEntry = await em.findOne({ id: 1 })!;

// This WILL throw, even though the `prototype` IS the "same"
fetchedEntry.setup(false);
```

**Expected behavior**
There should be no issues with creating such structures, however, due to the current way they're created (by bypassing the constructor), they become "shadow extensions" of the base class, and will throw.

**Additional context**

`fetchedEntry instanceof Example` -> true
`fetchedEntry.__proto__ === Example` -> `fetchedEntry` extends `Example` but isn't strictly an `Example`; `this` isn't `Example`, while `this.__proto__` is

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.3 |
| typescript | 4.1.3 |
| mikro-orm | 4.3.4 |
| @mikro-orm/postgresql | 4.3.4 |

**Comment by B4nan** [comment] 2020-12-21 15:18
If that line is the problem, I'd call it a won't fix right ahead. The ORM never uses entity ctor (with only exception being `em.create()`) - this invariant is esential to allow using ctors for new entities only. 

We could have a toggle to use the ctor all the time, but disabled by default, as changing it would be a huge breaking change. This way you could choose what is more important to you, native private fields or entity ctors.

**Comment by vladfrangu** [comment] 2020-12-21 16:14
If there's no other way to fix it, is it possible per chance to get it as an option that is per entity? That way, you do your trade offs only where you want them, and not globally across all possible entities 👀😅

**Comment by B4nan** [comment] 2020-12-21 16:16
Sure, we can make the option both global and entity based (so it would be a `boolean | Constructor<AnyEntity> | string` basically).

**Comment by B4nan** [comment] 2020-12-21 16:25
Btw to verify I also asked on SO if this is possible to get around but apparently this is intended behaviour of native private fields:

https://stackoverflow.com/questions/65395454/object-create-and-native-private-fields

Looking at how TS compiles/downlevels native props I don't see a way around that othe than using the ctor.

**Closed** 2021-01-15 11:42 UTC
Labels: enhancement

**Comment by B4nan** [comment] 2025-02-06 12:44
Not sure what you mean, I am not aware of any issues with inheritance, can you provide a [complete reproduction](https://github.com/mikro-orm/reproduction)?

**Comment by WhereJuly** [comment] 2025-02-06 12:49
> Not sure what you mean, I am not aware of any issues with inheritance, can you provide a [complete reproduction](https://github.com/mikro-orm/reproduction)?

I see. To my view referring to the above code it is pretty clear `Object.create()` does not call `Entity` constructor meaning it does not call `super()` meaning the parent class `BaseClass` is never constructed meaning inheritance is broken. If you do not get it just leave as is. Maybe someone finds these explanations here helpful and that is enough.

**Comment by B4nan** [comment] 2025-02-07 06:44
I still don't understand what you consider "broken inheritance". `instanceof` checks will work just fine. Constructors wont be fired, which is expected/wanted behaviour. That means that property initializers wont be fired. And to me, it feels like you just don't like that behaviour. Yes it affects base classes too. That does not mean "inheritance is broken", its the same story, you do not want that on managed entities, only on new ones. 

> BTW: The getters on BaseObject retrieving a state in the nested object (assigned to a property in BaseObject) and updated via BaseObject's methods will not work even when the forceEntityConstructor is in place.

This is not true. Metadata of base entities are inlined during discovery. There is no base object on runtime.

Again, without a complete reproduction, I don't know what you are talking about.

**Comment by WhereJuly** [comment] 2025-02-07 12:45
@B4nan Thanks for seeing in it. For now I am just pretty busy, no time for reproduction unfortunately. 

> And to me, it feels like you just don't like that behaviour

No, that is not the problem at all. The constructor call issue mitigated with `forceEntityConstructor` config option so that is not the issue.

> you do not want that on managed entities

That is not the case for me. I want the entire inheritance chain to work for both managed entities and we may say so natural object. 

This is difficult to match discussion contexts, but for me the nested properties of MikroORM entity are not at all and not always have to be other MikroORM entities if that delivers some meaning to you. Of course discussing the code in words is a bad idea :))

> This is not true. Metadata of base entities are inlined during discovery. 

I am not sure how the object getters are metadata but let it be so. Again in words is pretty pointless. I will take my time and would make a reproduction some day.

Have a nice day. Love MikroORM and thanks for it. Huge work is too small word for this.
