### ISSUE TITLE
ECMAScript Modules support

### ISSUE THREAD

**Issue by kyranet** [mikro-orm/mikro-orm#1010] opened 2020-10-31 13:56 UTC
**Is your feature request related to a problem? Please describe.**

Greetings! First of all, thank you for such an amazing module, it's pretty updated so I'm looking forward using it very soon :)

I have been trying to migrate some of my projects to use ESM because of its benefits (asynchronous module resolution, immunity to circular imports, etc). I have read https://github.com/mikro-orm/mikro-orm/issues/604#issuecomment-642184929 too, but I would like to be able to use Mikro-ORM while targetting ESNext modules.

**Describe the solution you'd like**

Add support for ECMAScript Modules.

**Describe alternatives you've considered**

There are multiple ways to go around it:

1. We can write a `index.mjs` file and somehow try to get them updated with the (output) `index.js` file. It would look similar to [this](https://github.com/discordjs/discord.js/blob/master/esm/discord.mjs).
2. We can use [`rollup`](https://www.npmjs.com/package/rollup) to output both CommonJS and ECMAScript Modules, only one will be loaded, so there isn't really an overload in memory usage, just slightly duplicates disk usage.
3. We can have a mixture of two, auto-generate an `index.mjs` from `index.js`'s exports, using [gen-esm-wrapper](https://www.npmjs.com/package/gen-esm-wrapper), which auto-generates the .mjs file, and it works!

<details>
  <summary>Generated <code>gen-esm-wrapper</code> code from <code>mikro-orm@4.2.3</code></summary>

Command run:
```sh-session
$ npx gen-esm-wrapper .\node_modules\mikro-orm\index.js index.mjs
```

Output `index.mjs` file:
```typescript
import mod from "./node_modules/mikro-orm/index.js";

export default mod;
export const __esModule = mod.__esModule;
export const PrimaryKeyType = mod.PrimaryKeyType;
export const EntityMetadata = mod.EntityMetadata;
export const EntityRepositoryType = mod.EntityRepositoryType;
export const GroupOperator = mod.GroupOperator;
export const QueryOperator = mod.QueryOperator;
export const ARRAY_OPERATORS = mod.ARRAY_OPERATORS;
export const QueryOrder = mod.QueryOrder;
export const QueryOrderNumeric = mod.QueryOrderNumeric;
export const QueryFlag = mod.QueryFlag;
export const SCALAR_TYPES = mod.SCALAR_TYPES;
export const ReferenceType = mod.ReferenceType;
export const Cascade = mod.Cascade;
export const LoadStrategy = mod.LoadStrategy;
export const LockMode = mod.LockMode;
export const EventType = mod.EventType;
export const ValidationError = mod.ValidationError;
export const OptimisticLockError = mod.OptimisticLockError;
export const MetadataError = mod.MetadataError;
export const NotFoundError = mod.NotFoundError;
export const DriverException = mod.DriverException;
export const ConnectionException = mod.ConnectionException;
export const ServerException = mod.ServerException;
export const ConstraintViolationException = mod.ConstraintViolationException;
export const DatabaseObjectExistsException = mod.DatabaseObjectExistsException;
export const DatabaseObjectNotFoundException = mod.DatabaseObjectNotFoundException;
export const DeadlockException = mod.DeadlockException;
export const ForeignKeyConstraintViolationException = mod.ForeignKeyConstraintViolationException;
export const InvalidFieldNameException = mod.InvalidFieldNameException;
export const LockWaitTimeoutException = mod.LockWaitTimeoutException;
export const NonUniqueFieldNameException = mod.NonUniqueFieldNameException;
export const NotNullConstraintViolationException = mod.NotNullConstraintViolationException;
export const ReadOnlyException = mod.ReadOnlyException;
export const SyntaxErrorException = mod.SyntaxErrorException;
export const TableExistsException = mod.TableExistsException;
export const TableNotFoundException = mod.TableNotFoundException;
export const UniqueConstraintViolationException = mod.UniqueConstraintViolationException;
export const MikroORM = mod.MikroORM;
export const EntityRepository = mod.EntityRepository;
export const EntityIdentifier = mod.EntityIdentifier;
export const EntityValidator = mod.EntityValidator;
export const EntityAssigner = mod.EntityAssigner;
export const assign = mod.assign;
export const SerializationContext = mod.SerializationContext;
export const EntityTransformer = mod.EntityTransformer;
export const EntityHelper = mod.EntityHelper;
export const EntityFactory = mod.EntityFactory;
export const ArrayCollection = mod.ArrayCollection;
export const Collection = mod.Collection;
export const EntityLoader = mod.EntityLoader;
export const Reference = mod.Reference;
export const BaseEntity = mod.BaseEntity;
export const WrappedEntity = mod.WrappedEntity;
export const wrap = mod.wrap;
export const EventManager = mod.EventManager;
export const EntityManager = mod.EntityManager;
export const ChangeSetType = mod.ChangeSetType;
export const ChangeSetComputer = mod.ChangeSetComputer;
export const ChangeSetPersister = mod.ChangeSetPersister;
export const CommitOrderCalculator = mod.CommitOrderCalculator;
export const UnitOfWork = mod.UnitOfWork;
export const IdentityMap = mod.IdentityMap;
export const Configuration = mod.Configuration;
export const ConfigurationLoader = mod.ConfigurationLoader;
export const Logger = mod.Logger;
export const ObjectBindingPattern = mod.ObjectBindingPattern;
export const compareObjects = mod.compareObjects;
export const compareArrays = mod.compareArrays;
export const compareBuffers = mod.compareBuffers;
export const equals = mod.equals;
export const Utils = mod.Utils;
export const RequestContext = mod.RequestContext;
export const QueryHelper = mod.QueryHelper;
export const expr = mod.expr;
export const NullHighlighter = mod.NullHighlighter;
export const EntityComparator = mod.EntityComparator;
export const Hydrator = mod.Hydrator;
export const ObjectHydrator = mod.ObjectHydrator;
export const EntityManagerType = mod.EntityManagerType;
export const DatabaseDriver = mod.DatabaseDriver;
export const Connection = mod.Connection;
export const Platform = mod.Platform;
export const ExceptionConverter = mod.ExceptionConverter;
export const Type = mod.Type;
export const DateType = mod.DateType;
export const TimeType = mod.TimeType;
export const BigIntType = mod.BigIntType;
export const BlobType = mod.BlobType;
export const ArrayType = mod.ArrayType;
export const EnumArrayType = mod.EnumArrayType;
export const JsonType = mod.JsonType;
export const AbstractNamingStrategy = mod.AbstractNamingStrategy;
export const MongoNamingStrategy = mod.MongoNamingStrategy;
export const UnderscoreNamingStrategy = mod.UnderscoreNamingStrategy;
export const EntityCaseNamingStrategy = mod.EntityCaseNamingStrategy;
export const EntitySchema = mod.EntitySchema;
export const MetadataDiscovery = mod.MetadataDiscovery;
export const MetadataStorage = mod.MetadataStorage;
export const MetadataProvider = mod.MetadataProvider;
export const MetadataValidator = mod.MetadataValidator;
export const JavaScriptMetadataProvider = mod.JavaScriptMetadataProvider;
export const ReflectMetadataProvider = mod.ReflectMetadataProvider;
export const NullCacheAdapter = mod.NullCacheAdapter;
export const FileCacheAdapter = mod.FileCacheAdapter;
export const MemoryCacheAdapter = mod.MemoryCacheAdapter;
export const OneToMany = mod.OneToMany;
export const PrimaryKey = mod.PrimaryKey;
export const SerializedPrimaryKey = mod.SerializedPrimaryKey;
export const Entity = mod.Entity;
export const OneToOne = mod.OneToOne;
export const ManyToOne = mod.ManyToOne;
export const ManyToMany = mod.ManyToMany;
export const Property = mod.Property;
export const Enum = mod.Enum;
export const Formula = mod.Formula;
export const Index = mod.Index;
export const Unique = mod.Unique;
export const Repository = mod.Repository;
export const Embeddable = mod.Embeddable;
export const Embedded = mod.Embedded;
export const Filter = mod.Filter;
export const Subscriber = mod.Subscriber;
export const BeforeCreate = mod.BeforeCreate;
export const AfterCreate = mod.AfterCreate;
export const BeforeUpdate = mod.BeforeUpdate;
export const AfterUpdate = mod.AfterUpdate;
export const OnInit = mod.OnInit;
export const BeforeDelete = mod.BeforeDelete;
export const AfterDelete = mod.AfterDelete;
export const CLIHelper = mod.CLIHelper;
export const CLIConfigurator = mod.CLIConfigurator;
export const EntityGenerator = mod.EntityGenerator;
export const Migrator = mod.Migrator;
export const Migration = mod.Migration;
export const MigrationRunner = mod.MigrationRunner;
export const MigrationGenerator = mod.MigrationGenerator;
export const MigrationStorage = mod.MigrationStorage;
export const TsMorphMetadataProvider = mod.TsMorphMetadataProvider;
```
</details>

**Additional context**

N/a, nothing to add, except maybe stating the obvious regarding `gen-esm-wrapper` being written by Node.js's core developers.

**Comment by B4nan** [comment] 2020-10-31 14:19
I'd rather not use any bundler, so 3. sounds like the best option. Can you share some example project I can use to test this? Not using ESM anywhere myself. 

Btw do I get it right that for end user it is currently possible to use that tool to generate what is needed inside node_modules? (ofc it would be wiped after another install/update)

**Comment by B4nan** [comment] 2020-10-31 14:31
> I have read #604 (comment) too, but I would like to be able to use Mikro-ORM while targetting ESNext modules.

Btw this should be limitation only for CLI (afaik). So are we talking about CLI only?

**Comment by kyranet** [comment] 2020-10-31 14:32
> Can you share some example project I can use to test this? Not using ESM anywhere myself.

Retarding `gen-esm-wrapper`, you can find a list of projects using it [here](https://github.com/addaleax/gen-esm-wrapper/network/dependents). A notable one that is being used in production is the thread-pool [piscina](https://github.com/piscinajs/piscina/blob/current/package.json#L40) which runs the utility in the `build` script (line 12 in the same file).

The README includes an example about the library's usage with ESM (and how it compares to CJS) too.

If you meant an example project using the utility and mikro-orm, I don't have one yet, but I can make a small example like the existing ones.

> Btw do I get it right that for end user it is currently possible to use that tool to generate what is needed inside node_modules? (ofc it would be wiped after another install/update)

Yeah, it's completely possible for end-users to run this utility on their end, however, it'd force us to use relative paths to our project (and to some point even to [`module-alias`](https://www.npmjs.com/package/module-alias) so we import as `@deps/mikro-orm`), but it's less than ideal as there isn't really an easy way to ensure the files will be completely synchronized with `node_modules`.

> Btw this should be limitation only for CLI (afaik). So are we talking about CLI only?

I'm not sure what you meant, `gen-esm-wrapper` is a CLI-only tool, so it's to be used as a development dependency only.

**Comment by B4nan** [comment] 2020-10-31 14:40
> I'm not sure what you meant, gen-esm-wrapper is a CLI-only tool, so it's to be used as a development dependency only.

You linked issue #604, and the issue is only about using the CLI, I am not aware of any other ESM issue when running the app itself. Solution to that issue is to have dedicated tsconfig for CLI only, it has nothing to do with running the app itself.

That's mainly the reason why I'd like you to provide a repo on which I can see what should be fixed, as if its only about the CLI, I believe there might be easier ways around.

**Comment by kyranet** [comment] 2020-10-31 15:06
After testing a little, turns out Node.js LTS and v15 can indeed import this library without extra tools, given the following code (and nothing more):

`main.mjs`:
```javascript
import Mikro, { Entity } from 'mikro-orm';

console.log(Mikro.Entity, Entity);
```

When running LTS (or v15) with `node main.mjs`, it'll log `[Function: Entity] [Function: Entity]`, which is the behaviour I wanted (I found about this just now).

However, early v14 and older (v12 included) doesn't have this behaviour, and the following error would be thrown with the code above:

```javascript
file:///mnt/d/r/tmp/mikro/main.mjs:1
import Mikro, { Entity } from 'mikro-orm';
                ^^^^^^
SyntaxError: The requested module 'mikro-orm' does not provide an export named 'Entity'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

The idea was mostly to support this behaviour evenly in all Node.js versions, although it's fine if you decide not to support ESM's usage in this library to encourage developers to update to v14 LTS as ESM support is more stable, and the minimum reproducible code works.

**Comment by B4nan** [comment] 2020-11-14 16:24
Will close this as apparently there is no traction. I believe people should go for the latest stable node version that is possible if they want to use cutting edge features. Especially when it also works out of box with latest LTS version.

**Closed** 2021-04-17 13:35 UTC
Labels: enhancement
