### ISSUE TITLE
4.0.0-rc.3 and 4.0.0-rc.4 with escaya break projects that depend on acorn

### ISSUE THREAD

**Issue by msheakoski** [mikro-orm/mikro-orm#783] opened 2020-08-26 21:08 UTC
**Describe the bug**
After updating from 4.0.0-rc.2 to rc.3 and rc.4, dependencies of my project which use acorn, such as [@nestjs/graphql](https://github.com/nestjs/graphql), stop working. I narrowed it down to a potential conflict between escaya and one of the acorn packages, but because I am not familiar with the internals, I do not yet know the specific cause. I think potentially escaya might be making a declaration that is overwriting something that acorn also uses.

**Stack trace**
```
GraphQLError [Object]: Input Object type AccessTokenCreateInput must define one or more fields.
  at SchemaValidationContext.reportError (/example/node_modules/graphql/type/validate.js:88:19)
  at validateInputFields (/example/node_modules/graphql/type/validate.js:420:13)
  at validateTypes (/example/node_modules/graphql/type/validate.js:218:7)
  at validateSchema (/example/node_modules/graphql/type/validate.js:54:3)
  at graphqlImpl (/example/node_modules/graphql/graphql.js:79:62)
  at /example/node_modules/graphql/graphql.js:28:59
  at new Promise (<anonymous>)
  at Object.graphql (/example/node_modules/graphql/graphql.js:26:10)
  at GraphQLSchemaFactory.<anonymous> (/example/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:49:52)
  at Generator.next (<anonymous>)

(node:65595) UnhandledPromiseRejectionWarning: Error: Schema generation error (code-first approach)
  at GraphQLSchemaFactory.<anonymous> (/example/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:51:27)
  at Generator.next (<anonymous>)
  at fulfilled (/example/node_modules/@nestjs/graphql/node_modules/tslib/tslib.js:111:62)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.8.0 |
| typescript | 4.0.2 |
| mikro-orm | 4.0.0-rc.4 |
| your-driver | postgresql |

**Comment by merceyz** [comment] 2020-08-26 21:42
> dependencies of my project which use acorn, such as @nestjs/graphql, stop working

Can you point to where it's using `acron`, I can't find it. This sounds like a undeclared dependency issue

**Comment by msheakoski** [comment] 2020-08-26 22:25
> Can you point to where it's using `acron`, I can't find it. This sounds like a undeclared dependency issue

It does not look like @nestjs/graphql has a runtime dependency on acorn, and the error does not happen while doing a `yarn build`, but it does happen during a `yarn start:dev`, so maybe an indirect conflict with one of the devDependencies that depend on acorn such as eslint or jest.

**Comment by msheakoski** [comment] 2020-08-26 22:41
It is very possible that it has nothing to do with escaya. I know for sure the issue is somewhere between 3a07a82 and d83c6a1. What would be the best way to install the packages as a group, commit by commit, to see where specifically the error starts?

**Comment by B4nan** [comment] 2020-08-27 05:05
Escaya has no dependencies, how could it affect acorn in any way?

**Comment by B4nan** [comment] 2020-08-27 05:52
There is no `AccessTokenCreateInput` in the whole escaya repository, nowhere. What makes you think this is caused by MikroORM and not something else?

**Comment by B4nan** [comment] 2020-08-27 09:40
Looking at the diff (https://github.com/mikro-orm/mikro-orm/compare/3a07a8251bc6aed05cffb88a8e91c3f9bc38cca4...d83c6a14e8ce2b9b663056efc1dd9b7cb45c122a), could it be maybe caused by the upgrade to TS 4? 

Also tried to google that error, maybe this one could help?

https://stackoverflow.com/questions/59527847/input-object-type-typename-must-define-one-or-more-fields

In general, it feels very weird that this would be caused by upgrading MikroORM. Without a reproduction repository this is not actionable.

**Comment by msheakoski** [comment] 2020-08-27 13:56
I will try to put together a reproduction repository. I did narrow down the part that seems to be breaking in the upgrade from rc.2 -> rc.4 to Nest's [GraphQL CLI Plugin](https://docs.nestjs.com/graphql/cli-plugin) [repo](https://github.com/nestjs/graphql/tree/master/lib/plugin) which is responsible for AST processing.

Normally, it will detect the GraphQL types from the code, but after upgrading to rc.4, I get the errors above. I can manually add @Field decorators to the properties of the classes that triggered the errors to make all errors go away, but I noticed that now other fields which were previously auto-detected have disappeared from the auto-generated GraphQL schema.

I will continue investigating.

**Comment by pigulla** [comment] 2020-09-01 08:38
@msheakoski I just ran into a similar issue. Did you make any progress on this?

**Comment by msheakoski** [comment] 2020-09-01 15:39
@pigulla I will not have time to investigate further until after this week. For now, I have frozen all versions to rc.2 in my package.json (works with yarn, not sure about npm):

```json
{
  "dependencies": {
    "@mikro-orm/cli": "4.0.0-rc.2",
    "@mikro-orm/core": "4.0.0-rc.2",
    "@mikro-orm/migrations": "4.0.0-rc.2",
    "@mikro-orm/postgresql": "4.0.0-rc.2"
  },
  "resolutions": {
    "**/@mikro-orm/core": "4.0.0-rc.2",
    "**/@mikro-orm/entity-generator": "4.0.0-rc.2",
    "**/@mikro-orm/knex": "4.0.0-rc.2",
    "**/@mikro-orm/migrations": "4.0.0-rc.2"
}
```

**Comment by KFlash** [comment] 2020-09-02 16:37
How can this be related to EScaya? Only exposed to global is the parsing methods and it uses it's own AST. If you need Estree for bug tracking you can custom parse and add your own AST.

TypeScript v. 4.x isn't compatible with ESLint yet. Maybe look into that?

**Comment by msheakoski** [comment] 2020-09-02 16:49
> How can this be related to EScaya? Only exposed to global is the parsing methods and it uses it's own AST.

It is possible that a declaration in a d.ts file is being picked up by other packages and overwriting a class with the same name. In a declaration file, everything is implicitly exported. You can prevent this by adding `export {}`. See https://github.com/microsoft/TypeScript/issues/32182#issuecomment-507006868

> TypeScript v. 4.x isn't compatible with ESLint yet. Maybe look into that?

The project is working just fine with MikroORM rc.2 on TypeScript 4.0.2. All I know is that something in the range of commits I referenced earlier breaks the AST parsing in Nest's GraphQL plugin, and escaya is the only change related to AST.

**Comment by B4nan** [comment] 2020-09-02 16:53
@msheakoski just shipped `rc.5`, can you re-test with that version? would be good to have a reproduction

**Comment by msheakoski** [comment] 2020-09-02 17:28
@B4nan The issue still remains with rc.5 unfortunately.

**Comment by B4nan** [comment] 2020-09-06 10:26
I really believe this should be filed at the nestjs repository instead. Will close it now, will be happy to reopen if you provide a reproduction that actually points to an issue on MikroORM side, but I highly doubt it, if there is something wrong, it will be in the nestjs/graphql and not here. Also I doubt it has something to do with escaya.

**Closed by B4nan** 2020-09-06 10:26 UTC
Labels: bug, needs clarification

**Comment by msheakoski** [comment] 2020-09-18 02:02
I am happy to report that as of v4.0.3 I no longer experience this error. I am not sure what specific changes in my project or its dependencies in the past 3 weeks fixed the issue, but I would like to thank everyone for their input and help!

@pigulla hopefully 4.0.3 works for you as well!
