### ISSUE TITLE
NestJS e2e testing with Jest

### ISSUE THREAD

**Issue by rmaes4** [mikro-orm/mikro-orm#532] opened 2020-05-01 17:13 UTC
**Describe the bug**
I am trying to set up e2e testing in Nest with Jest. Because I am using the Nest CLI GraphQL plugin I followed the steps [here](https://github.com/nestjs/graphql/issues/810#issuecomment-618308354). I am now running into the following error.

**Stack trace**
```
 dist/test/app.e2e-spec.js
  AppController (e2e)
    ✕ /user/register (POST) (274ms)

  ● AppController (e2e) › /user/register (POST)

    Cannot find module './base.entity' from 'base-collection.entity.ts'

    Require stack:
      /Users/robmaes/Documents/ccp/api/src/entities/base-collection.entity.ts
      /Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js
      /Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/metadata/index.js
      /Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/utils/Configuration.js
      /Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/utils/index.js
      /Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/EntityManager.js
      /Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/MikroORM.js
      /Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/index.js
      /Users/robmaes/Documents/ccp/api/node_modules/nestjs-mikro-orm/mikro-orm.common.js
      /Users/robmaes/Documents/ccp/api/node_modules/nestjs-mikro-orm/mikro-orm.providers.js
      /Users/robmaes/Documents/ccp/api/node_modules/nestjs-mikro-orm/mikro-orm.module.js
      /Users/robmaes/Documents/ccp/api/node_modules/nestjs-mikro-orm/index.js
      src/app.module.js
      test/app.e2e-spec.js

      1 | import { ObjectType } from '@nestjs/graphql';
      2 | import { Property } from 'mikro-orm';
    > 3 | import { Base } from './base.entity';
        | ^
      4 | 
      5 | @ObjectType()
      6 | export abstract class BaseCollection extends Base {

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:299:11)
      at Object.<anonymous> (../src/entities/base-collection.entity.ts:3:1)
```

**To Reproduce**

tsconfig.e2e-test.json
```json
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "dist"]
}
```

test/jest-e2e.json
```json
{
  "moduleFileExtensions": ["js", "json"],
  "rootDir": "../dist",
  "testEnvironment": "node",
  "testRegex": ".e2e-spec.js$",
  "transform": {
    "^.+\\.(t)s$": "ts-jest"
  }
}
```

test/app.e2e-spec.ts
```ts
import { INestApplication } from '@nestjs/common';
import {
  FastifyAdapter,
  NestFastifyApplication
} from '@nestjs/platform-fastify';
import { Test, TestingModule } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from './../src/app.module';

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule]
    }).compile();

    app = moduleFixture.createNestApplication<NestFastifyApplication>(
      new FastifyAdapter()
    );
    await app.init();
  });

  it('/user/register (POST)', () => {
    return request(app.getHttpServer())
      .post('/user/register')
      .send({
        email: '####',
        password: '####',
        firstName: '####',
        lastName: '####'
      })
      .expect(201);
  });
});
```

package.json
```json
...
"build:e2e": "nest build -p tsconfig.e2e-test.json",
...
"test:e2e": "jest --config ./test/jest-e2e.json"
...
"jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
```

Run `yarn build:e2e` then `yarn test:e2e`

**Expected behavior**
The test should pass (or at least run without the above error).

**Additional context**
I think this is related to the fact that I'm having to compile the test to JS before running?

In general I found the docs / Nest examples lack testing examples. Perhaps it could be improved upon.

Thanks!

**Versions**

| Dependency | Version |
| - | - |
| node | 12.14.1 |
| typescript | ^3.7.4 |
| mikro-orm | ^3.6.12 |
| pg | ^8.0.3 |
| jest | ^25.1.0 |
| @nestjs/common | ^7.0.0 |

**Comment by B4nan** [comment] 2020-05-01 17:25
Not sure how is this connected to MikroORM? Its error with inports, no orm involved, right?

**Comment by rmaes4** [comment] 2020-05-01 17:33
Well everything else imported fine. I thought it was related to 
```
/Users/robmaes/Documents/ccp/api/src/entities/base-collection.entity.ts
/Users/robmaes/Documents/ccp/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js
```

I guess I'll keep searching

**Comment by B4nan** [comment] 2020-05-01 17:40
How does the ORM config look like?

**Comment by B4nan** [comment] 2020-05-01 17:44
Maybe the problem is that you want to run against compiled entities in dist, but you are still using ts-jest to run it. ORM will detect that and use entities from src automatically. 

You can add tsNode: false to the config to force usage of the compiled entities.

**Comment by rmaes4** [comment] 2020-05-01 17:52
Ok I set tsNode: false and now I get
```
ValidationError: Multiple property decorators used on 'Base.createdAt' property

      2 | var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
      3 |     var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    > 4 |     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        |                                                                                            ^
      5 |     else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
      6 |     return c > 3 && r && Object.defineProperty(target, key, r), r;
      7 | };

      at Function.multipleDecorators (../node_modules/mikro-orm/dist/utils/ValidationError.js:109:16)
      at Function.validateSingleDecorator (../node_modules/mikro-orm/dist/entity/EntityValidator.js:13:43)
      at ../node_modules/mikro-orm/dist/decorators/Property.js:10:34
      at DecorateProperty (../node_modules/reflect-metadata/Reflect.js:553:33)
      at Object.decorate (../node_modules/reflect-metadata/Reflect.js:123:24)
      at __decorate (entities/base.entity.js:4:92)
      at Object.<anonymous> (../src/entities/base.entity.ts:12:3)
      at Object.<anonymous> (../src/entities/base-collection.entity.ts:3:1)
```

and my config:
```ts
import { registerAs } from '@nestjs/config';
import { Options } from 'mikro-orm';

export default registerAs(
  'database',
  (): Options => ({
    type: 'postgresql',
    host: process.env.DATABASE_HOST,
    port: parseInt(process.env.DATABASE_PORT),
    user: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    dbName: process.env.DATABASE_DATABASE,
    debug: process.env.NODE_ENV !== 'production',
    forceUtcTimezone: true,
    entitiesDirs: ['dist/entities'],
    entitiesDirsTs: ['src/entities'],
    tsNode: false
  })
);
```

**Comment by rmaes4** [comment] 2020-05-01 17:58
Ok I deleted the dist folder, changed entitiesDirs to 'dist/src/entities' and now it works!

**Comment by B4nan** [comment] 2020-05-01 18:09
Ok closing it then

**Closed by B4nan** 2020-05-01 18:09 UTC
Labels: bug
