### ISSUE TITLE
MikroORM does not discover entities when running from jest in my nestjs app

### ISSUE THREAD

**Issue by tma-isbx** [mikro-orm/mikro-orm#2006] opened 2021-07-03 03:02 UTC
I get a `MetadataError: No entities were discovered` when I try to use jest to run my tests.

If I build first, then MikroORM seems to be able to discover my entities from my `dist` directory. But I get a 
```
ValidationError: Trying to persist not discovered entity of type User. Entity with this name was discovered, but not the prototype you are passing to the ORM. If using EntitySchema, be sure to point to the implementation via `class`.
```

I am able to reproduce the `No entities were discovered` issue with https://github.com/mikro-orm/nestjs-realworld-example-app when I try to run `yarn test`y

**To Reproduce**
1. Clone https://github.com/mikro-orm/nestjs-realworld-example-app
2. Copy mikro-orm.config.ts.example to mikro-orm.config.ts
3. Run `yarn test`

**Expected behavior**
I expect the tests to run with entities discovered from my `src` directory as the `dist` entities may not be current.

**Versions**
Using the versions specified in the yarn.lock
| Dependency | Version |
| - | - |
| node | 14.15.2 |
| typescript | ? |
| mikro-orm | ? |
| your-driver | ? |

**Comment by B4nan** [comment] 2021-07-03 08:03
It works fine for me, this is not enough to reproduce anything. 

> Using the versions specified in the yarn.lock

Well, then just upgrade, that lock file is very outdated. Always first upgrade to latest before filing a bug report. 

Also that second error when you build the app points to using different entity than you discover, in other words, you discover JS entity but execute via ts-node or vice versa. You always need to discover the same files you will use - so for ts-node you need to discover TS files from src, for node you need to discover JS files from dist. 

Closing this, as there is nothing to reproduce and this is definitely just a misconfiguration. Will update the example project and add a CI pipeline to make sure it works fine, but again, I am using the project locally quite often and it works just fine.

**Closed by B4nan** 2021-07-03 08:03 UTC

**Comment by B4nan** [comment] 2021-07-03 08:16
Ok so apparently this is working fine on macos but not on linux as the CI failed - but still, what I said above applies, correct way is to enfore TS mode via `tsNode: true` in the ORM config for tests. 

https://github.com/mikro-orm/nestjs-realworld-example-app/commit/7ceea8f5b70d9cc88e16fb1a48bc2cfeebeeec2b#diff-f57a902481ea8bc7a2ff9d6b216cdebec531ba08edb691443b6b4ca2647e5adbR15

**Comment by tma-isbx** [comment] 2021-07-03 08:23
Hi!

Odd. I am on MacOS Big Sur. Adding the `tsNode: true` when running the tests through ts-jest seems to solve the problem.

Thanks!

**Comment by B4nan** [comment] 2021-07-03 11:40
Apparently it was not working even for me, but the tests were passing because I had the project built and the test did not really required anything ORM specific to pass, so discovering JS files was enough. 

Anyway, asked the ts-jest guys if we can detect this somehow, and apparently we can't, so I PR'ed it (https://github.com/kulshekhar/ts-jest/pull/2717) - expect some future ts-jest and MikroORM versions to support this automatically :]
