### ISSUE TITLE
Embedded field with the JSON type is not saved correctly in postgres

### ISSUE THREAD

**Issue by Weplik** [mikro-orm/mikro-orm#3492] opened 2022-09-12 10:28 UTC
**Describe the bug**
I have an embeddable entity with field that have the json type. This entity is embedded in another entity as an array. In schema terms, it turns out that I have a JSON type field embedded in another JSON type field.

And when I save an entity with a embeddable entity, the nested json is saved to the postgres as a string, which is not correct, since I expect that json will be saved.

**To Reproduce**
Minimal code example:

```ts
@Embeddable()
export class FieldValueEntity {
    @Property()
    field: string;

    @Property({ type: types.json })
    values: string[] = [];
}

@Entity({ tableName: 'field' })
export class FieldEntity {
    @Embedded({ entity: () => FieldValueEntity, array: true })
    values: FieldValueEntity[] = [];
}
```

As a result of saving the `FieldEntity` , I see the following value `[{"field": "first_field", "values": "[\"value_one\",\"value_two\"]"}]` in the `values` column

**Expected behavior**
I would like to see the value not `[{"field": "first_field", "values": "[\"value_one\",\"value_two\"]"}]`, but the value `[{"field": "first_field", "values": ["value_one", "value_two"] }]` in the postgres. Because I'm expecting nested json, which I can then use to build queries without any casts. 

**Versions**

| Dependency | Version |
| - | - |
| node | 16.16.0 |
| typescript | 4.6.2 |
| mikro-orm | 5.3.1 |
| postgresql | 5.3.1 |

**Comment by B4nan** [comment] 2022-09-12 10:31
What if you define it as regular property? 

```ts
@Embeddable()
export class FieldValueEntity {
    @Property()
    field: string;

    @Property()
    values: string[] = [];
}
```

**Comment by Weplik** [comment] 2022-09-12 11:16
> What if you define it as regular property?

Result is the same as the description. 

And here I am, another issue https://github.com/mikro-orm/mikro-orm/issues/3327. In this issue, the problem is deserialization of data, but if they were immediately saved with the correct type, then deserialization would not be necessary.

**Comment by B4nan** [comment] 2022-09-12 11:21
Right, so this might be actually a duplicate of that issue, but lets keep both open before we are sure. I'll try to look into that later this week.

**Comment by B4nan** [comment] 2022-09-12 14:31
So the workaround is using some other mapped type that does not mutate the value anyhow. One example is the `StringType`, might sound weird, but this seems to work fine:

```ts
@Embeddable()
class FieldValue {

  @Property({ type: t.string })
  primitive?: string | number | boolean | null;

  @Property({ type: t.string })
  object?: Record<string, boolean>;

}
```

The problem is that we can't have the JSON type set inside nested embeddables - will need to find a way to ignore it, it should be fine to set it, but internally the processing of JSON needs to happen only for the top level JSON property that actually maps to a database column, not recursively.

**Comment by B4nan** [comment] 2022-09-12 14:32
I will close this one, it is indeed a duplicate of #3327, I should have a fix soon.

**Closed by B4nan** 2022-09-12 14:32 UTC
