### ISSUE TITLE
Make globby optional

### ISSUE THREAD

**Issue by stalniy** [mikro-orm/mikro-orm#953] opened 2020-10-23 09:01 UTC
**Is your feature request related to a problem? Please describe.**

This is a minor issue but I'd like not to depend on libraries that I don't use. I prefer to use explicit `entities` array and don't use entity discovery mechanism through paths, so I don't want related libraries to be installed.

**Describe the solution you'd like**

At the first sight, path discovery can be easily opted out and be replaced by this (suppose we have `entities` folder and inside each we export entity through default export:

```js
import globby from 'globby';

const orm = await MikroORM.init({
   entities: await globby(['./entities/*.js'], { cwd: __dirname })
})
```

**Additional context**

Additionally `entitiesTs` option can be moved to `TsMorphMetadataProvider` provider, as far as I understand this is the only `MetadataProvider` which does magic with TypeScript source code

**Comment by stalniy** [comment] 2020-10-23 09:03
By the way, can help with this if you are OK.

**Comment by B4nan** [comment] 2020-10-23 09:20
Globby is used in more places than just here. I am not sure if we can make it optional easily. 

Also your proposal won't work, its not that easy. It could work only with default exports of the entities, and you would also need to set up `entitiesTs` accordingly.

Is it really worth it? I would expect globby to be rather small dependency. Also this would be breaking change, which I am not willing to make just yet.

**Comment by stalniy** [comment] 2020-10-23 09:33
OK, I'll take a look at other places and will come back with a better proposal. It's not something that is critical right now but I'd like to.

**PROS** of this change:

* simpler internal code, no need to check for folders, files, fs stuff
* cleaner api, no confusing `entitiesTs` which as far as I understand currently is used only by `TsMorphMetadataProvider`
* less heavy library size
* use whatever discovery strategy you can imagine, just provide entities back

**Comment by B4nan** [comment] 2020-10-23 09:43
Well I don't really agree. See - you proposed a way, and it was wrong. I already see all the issues :]

> simpler internal code, no need to check for folders, files, fs stuff

You say simpler codebase, but the only place this would simplify is a single method of `MetadataDiscovery` class (not even a complex one).

> cleaner api, no confusing entitiesTs which as far as I understand currently is used only by TsMorphMetadataProvider

As said above, it would bring more room for confusion as people do not understand the difference of requiring JS and TS file. And nope, it is not only needed for ts-morph.

> less heavy library size

Agreed with this one, but for me the difference is not worth a breaking change and all the added confusion.

> use whatever discovery strategy you can imagine, just provide entities back

You can already do that, there is no restriction because we depend on globby (or the fact that we offer folder based discovery). This is invalid for me.

**Comment by stalniy** [comment] 2020-10-23 09:52
Frankly speaking, I don't think it will add more confusion around `entitiesTs`. If you confused with it, you either confused or know what to do :) 

But I see your point, if you think the issue doesn't make sense, I agree to close it.

**Comment by B4nan** [comment] 2020-10-23 10:13
> Frankly speaking, I don't think it will add more confusion around entitiesTs. If you confused with it, you either confused or know what to do :)

Idk, for me current state helps a lot, you have two options, one for JS, one for TS. By removing folder based discovery, users would have to understand fully what is needed where, provide "the right list of entities" based on how they run the app (node vs ts-node). 

Maybe we could make the dependency optional by not importing it as usual, but making it peer dependency and using conditional require with try/catch.

I believe it could work - if the dependency is needed, we could throw "install globby" if its not found. This is something I would not really considered breaking change, as it would give you precise error that would be solved with single command.

Still I would rather not do it unless there is a real difference (and I would rather do it in v5 as it is still a BC). I already see another group of problems, being webpack and yarn pnp builds. 

On the other hand, I can confirm globby is fat, it is around 25% of the `core` package size. Idk why the whole JS universe things its fine to use 22 dependencies for something that could have zero dependencies. Usually I tend to do the hard work and port things myself so they are dependency free (like I did with the highlighters to replace the fat highlight.js). But here I am not really hesitant to do so, messing with files usually end up with issues on windows and I hate to debug those :]

**Comment by stalniy** [comment] 2020-10-23 11:49
For me it's fine to wait for v5, as I said it's not urgent but something what I think make sense to do eventually.

I'm currently familiarizing with the ecosystem of mikro-orm because I'm considering whether to use it for the next my project

**Comment by B4nan** [comment] 2020-10-23 12:46
Looking at the globby source and its dependencies, maybe I will give it a shot and try to implement something myself. This is nuts, 22 dependencies, many of them being single file deps, many of them being oldschool, using old language constructs, or even providing CLI interface (oh god, why)... 

On the other hand, I would be more interested in getting rid of knex, that is much worse/bigger/more-oldschool dependency... :] Remembering your issue where you asked for it, I must say I regret the decision to go all in for knex, so many obstacles from that, nothing is moving on their end (like the sqlite FKs issue), and I keep finding new blockers (like the tx isolation levels or lateral joins, not talking about anything schema related)... It's weird that there is literally no modern alternative to it.

**Comment by stalniy** [comment] 2020-10-23 13:00
I’d not recommend you to implement your own globby :) this just seems redundant. I can help with the issue (Real code) if you decide to opt out it. 

By the way, npm 7 installs peer dependncies: https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

**Comment by stalniy** [comment] 2020-10-23 13:09
> Looking at the globby source and its dependencies, maybe I will give it a shot and try to implement something myself. This is nuts, 22 dependencies, many of them being single file deps, many of them being oldschool, using old language constructs, or even providing CLI interface (oh god, why)...
> 
> On the other hand, I would be more interested in getting rid of knex, that is much worse/bigger/more-oldschool dependency... :] Remembering your issue where you asked for it, I must say I regret the decision to go all in for knex, so many obstacles from that, nothing is moving on their end (like the sqlite FKs issue), and I keep finding new blockers (like the tx isolation levels or lateral joins, not talking about anything schema related)... It's weird that there is literally no modern alternative to it.

If all good, I plan to write a custom database driver for Postgres based on https://github.com/porsager/postgres. This I guess will help a bit to get rid of knex, at least for Postgres

**Comment by merceyz** [comment] 2020-10-23 13:16
> By the way, npm 7 installs peer dependncies: https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

@stalniy Not if marked as optional

> I already see another group of problems, being webpack and yarn pnp builds.

@B4nan they should be fine, webpack ignores missing dependencies if it can prove that it's in a try catch, PnP shouldn't matter here

**Comment by B4nan** [comment] 2020-10-23 13:26
@merceyz Sounds good, thanks for the insight! Ok then I think having it as optional peer dependency in the way I described above is the way to go. 

The only question is whether its fine to ship it as 4.x, or wait for 5.0.

> If all good, I plan to write a custom database driver for Postgres based on porsager/postgres. This I guess will help a bit to get rid of knex, at least for Postgres

Not sure, we need abstraction over pooling and transactions (that is partially there already), this needs to be driver independent, as it will be the same for all sql drivers. So basically the same as `@mikro-orm/knex`, but without knex. But let's see where you end up.

The end goal for removing knex would be to allow using pretty much any db connector easily as it would be only about running queries and mapping raw response (let it be pg, porsager/postgres, mysql2, sqlite3, better-sqlite3, ...), rest should be handled in the ORM code.

**Comment by merceyz** [comment] 2020-10-23 13:37
> The only question is whether its fine to ship it as 4.x, or wait for 5.0.

It's a breaking change so I'd say no

**Comment by wkrueger** [comment] 2020-10-25 19:42
I 9999999% prefer things that work out of the box.

Peer dependencies work but they also another level of complexity both to users and to lib devs. Unfortunately NPM doesnt have something like "features" from rust.

**Comment by jgod** [comment] 2020-12-29 15:25
> If all good, I plan to write a custom database driver for Postgres based on https://github.com/porsager/postgres. This I guess will help a bit to get rid of knex, at least for Postgres

Very cool. I came to mikro-orm from that library, I would love to use it as a driver. How is it going? @stalniy

**Comment by stalniy** [comment] 2020-12-29 20:06
The requirements for my project is quite different from the general purpose ORM that’s why I decided to write a custom thin layer over postgres.js.

**Comment by B4nan** [comment] 2021-01-29 13:03
I feel like not doing this will be better. This issue was open for about 3 months, and I saw just one person saying we should not do it, and noone expect the OP in favour of doing so. 

So closing for now, if this is an actual issue for anybody, it should be possible to get around it via webpack build. Will be happy to reconsider if there is actual demand for this change.

**Closed by B4nan** 2021-01-29 13:03 UTC
Labels: breaking change, enhancement

**Comment by wenerme** [comment] 2024-06-12 07:52
@B4nan Hi, sorry to bather this old issues, I hope globby is optional ,because mikroorm is cjs, newer globby is esm only, I have to downgrade globby to 11 to avoid this error.

```
const globby_1 = __importDefault(require("globby"));
                                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /nodejs/node_modules/.pnpm/globby@14.0.1/node_modules/globby/index.js from /Users/wener/works/z66-inc/xiubi-nodejs/node_modules/.pnpm/@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/utils/Utils.js not supported.
```
