### ISSUE TITLE
Upsert doesn't seem to have any effect

### ISSUE THREAD

**Issue by KevinMusgrave** [mikro-orm/mikro-orm#3667] opened 2022-10-27 05:43 UTC
**Describe the bug**
I tried a simple example of `em.upsert` but it doesn't seem to have any effect.

**To Reproduce**

The following code consists of an entity `User` with an id and optional name. A user is created and written to the db, and then `em.upsert` is used to update the name, but the name doesn't actually get updated. 

```typescript
import { Entity, PrimaryKey, MikroORM, Property } from '@mikro-orm/core';

@Entity()
class User {
  @PrimaryKey()
  id!: number;

  @Property({ nullable: true })
  name: string;
}

describe('GH issue 3667', () => {
  let orm;
  let em;

  beforeAll(async () => {
    orm = await MikroORM.init({
      type: 'postgresql',
      dbName: 'test',
      allowGlobalContext: true,
      entities: [User],
    });
    await orm.schema.ensureDatabase();
    await orm.schema.dropSchema();
    await orm.schema.createSchema();
    em = orm.em;
  });

  afterAll(async () => {
    await orm.close(true);
  });

  test(`GH issue 3667`, async () => {
    const user1 = new User();
    em.persist(user1);
    await em.flush();

    await em.upsert(User, { id: 1, name: 'john' });
    await em.flush();
    const x = await em.findOne(User, { id: 1 });
    expect(x.name).toEqual('john'); //x.name is undefined

    em.clear();
  });
});
```
**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.2 |
| typescript | 4.3.5 |
| mikro-orm | 5.5.0 |
| postgres | 14.5

**Comment by B4nan** [comment] 2022-10-31 13:26
The issue is valid for sure, but let me give you few general points to your repro:
- `em` is typed to `any` this way, you dont want that. in the other issue, you even used signatures that dont exist and hence wont type check (e.g. `em.find()` with a single parameter)
- no point in `em.clear()` at the end of test, if something, this belongs to `beforeEach` hook (but its not necessary for a single test suites)
- in the scope of this repository, global context is allowed for tests, hence no need to use `allowGlobalContext` explicitly
- your final `em.findOne` call does nothing, you query entity by its PK, and that entity is already loaded in context = you just get the exact same object reference as `user1`, and in fact you dont reload anything - either use `em.clear()` to similate separate requests, or use multiple forks, or use `em.refresh()` or `refresh: true` in find options
- for anything unrelated to specific driver, use in-memory sqlite database instead - always try to do it, as this way you can confirm whether the issue is driver specific or not (and for those that are not, we want to use in-memory sqlite database so its as fast as possible)

Here is a modified test ready to be merged to the repo:

```ts
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/sqlite';

@Entity()
class User {

  @PrimaryKey()
  id!: number;

  @Property({ nullable: true })
  name?: string;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [User],
    debug: true,
  });
  await orm.schema.createSchema();
});

afterAll(async () => {
  await orm.close(true);
});

test(`GH issue 3667`, async () => {
  const user1 = new User();
  orm.em.persist(user1);
  await orm.em.flush();

  // if you uncomment this, things start to work -> this is a problem only if you try to upsert entity you created in the same context
  // orm.em.clear();

  await orm.em.upsert(User, { id: 1, name: 'john' });
  await orm.em.flush();

  const x = await orm.em.fork().findOneOrFail(User, user1.id);
  expect(x.name).toEqual('john');
});
```

**Comment by KevinMusgrave** [comment] 2022-11-01 06:09
Thanks for the pointers!

**Closed** 2022-11-01 20:41 UTC
Labels: bug
