### ISSUE TITLE
Collections not inserting in child entities of STI hierarchy

### ISSUE THREAD

**Issue by alisd23** [mikro-orm/mikro-orm#1032] opened 2020-11-04 14:08 UTC
**Describe the bug**
When using an STI hierarchy, where the root entity has a collection. Inserting a child entity with some items in that collection fails. 

**To Reproduce**
1. Go here: https://github.com/alisd23/mikro-orm-nestjs-starter/tree/bug/sti-collections
3. Run test case: `yarn test` (this will run all migrations automatically)

This will run the following code (`Manager` extends `BasePerson`, where `BasePerson` has a collection defined on it):
```ts
const manager = new Manager();
manager.addresses.add(new Address('some address', manager));

await orm.em.persistAndFlush(manager);
```

**Expected behavior**
This is a very basic case so the `Manager` entity should be inserted with a corresponding address. Instead, the error returned is:
```
NotNullConstraintViolationException: insert into `address` (`line1`) values ('some address') - Field 'person_id' doesn't have a default value
```

It seems MikroOrm fails to insert the collection of a parent entity in an STI setup. I'm guessing it must be some entity metadata issue, as if I change the address `ManyToOne` relationship from `@ManyToOne(() => BasePerson)` to `@ManyToOne('Manager')`, it works. 

I did find a test case [here](https://github.com/mikro-orm/mikro-orm/blob/0b97af8404fd557836f8afae9cce255aca083873/tests/issues/GH845.test.ts) but I'm not sure how that is passing given the case I provided above. I think the test cases around this need to be fleshed out a bit, and maybe tested against a real MySQL database (in docker world)?

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.3 |
| typescript | 4.0.3 |
| mikro-orm | 4.2.3 |
| your-driver | MySQL |

**Comment by B4nan** [comment] 2020-11-05 08:09
This might be actually already fixed, at leats I am not able to reproduce in master (and there were fixed in some complex STI cases). Can you try the latest dev version?

But beware there is one dev version published accidentally - latest is `4.2.4-dev.99` (for all packages), but there is also `4.2.4-dev.499`, which is actually older, so you might need to use yarn resolutions to ensure you do not install that. The `499` is marked as deprecated, so you should see a warning if it gets installed.

**Comment by alisd23** [comment] 2020-11-05 23:17
Ok great, you're ahead of me! Just tried with the `4.2.4-dev.103` versions and it looks like it's working for me now too. Nice work. 👍 

Any ETA for next release?

**Comment by B4nan** [comment] 2020-11-06 07:53
Ok good, will close this then. Will ship stable 4.3 probably during weekend, want to squash some of the recently reported bugs first.

**Closed by B4nan** 2020-11-06 07:53 UTC
