### ISSUE TITLE
IdentifiedReference is not properly discovered with ts-morph

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#1088] opened 2020-11-17 10:13 UTC
**Describe the bug**
After upgrading from 4.2.3 to 4.3.0 the id property of IdentifiedReference is possible undefined. In Addition, after mitigating the changes in typing, the metadata generation no longer works.

**To Reproduce**
~~~javascript
@Entity({ tableName: 'core_object' })
export class CoreObjectEntity {
  @PrimaryKey()
  id!: integer

 @Property()
  test!: string
}
~~~
~~~javascript
@Entity({ tableName: 'core_permission' })
export class CorePermissionEntity {

  @PrimaryKey()
  id!: integer

  @ManyToOne(() => CoreObjectEntity, { onDelete: 'cascade', onUpdateIntegrity: 'cascade' })
  object!: IdentifiedReference<CoreObjectEntity>
}
~~~

![image](https://user-images.githubusercontent.com/4943440/99375594-33a3b580-28c4-11eb-924d-1ed33b459015.png)

In addition metadata discovery does not seem to work in this case:
~~~javascript
MetadataError: Entity '{ object?: import("/home/mlink/workspace/pitapi/node_modules/@-/core/src/index").CoreObjectEntity | undefined; } & import("/home/mlink/workspace/pitapi/node_modules/@mikro-orm/core/index").Reference<DirectoryBookEntity>' was not discovered, please make sure to provide it in 'entities' array when initializing the ORM (used in DirectoryContactEntity.book)
~~~

**Expected behavior**
Object shouldn't be possible undefined like before.

**Additional context**
In 4.2.3 there were no type errors and metadata generation worked. The commit
https://github.com/mikro-orm/mikro-orm/commit/c9afabb5819a05006d0c13ed3de51b43d2052abc seems to be the culprit.

**Versions**
| Dependency | Version |
| node | 15.2.1 |
| typescript | 4.0.5 |
| mikro-orm | 4.3.0  |

**Comment by B4nan** [comment] 2020-11-17 11:41
Duplicate of #1084, this is on purpose. 

Regarding the metadata error, that sounds very weird, not sure what you are doing. Also your entity definitions are not valid typescript. Are you using ts-morph? If not, you are missing `wrappedReference: true` in there, also you are missing the PK type argument.

```ts
  @ManyToOne(() => CoreObjectEntity, { onDelete: 'cascade', onUpdateIntegrity: 'cascade', wrappedReference: true })
  object!: IdentifiedReference<CoreObjectEntity, 'id'>
```

**Comment by ml1nk** [comment] 2020-11-17 13:03
Sorry for the duplicate, thanks for the help.

I'm using ts-morph and I could reproduce the error everywhere where Reference or IdentifiedReference is used.

~~~
MetadataError: Entity 'Reference<DirectoryBookEntity>' was not discovered, please make sure to provide it in 'entities' array when initializing the ORM (used in DirectoryContactEntity.book)
~~~

![image](https://user-images.githubusercontent.com/4943440/99392955-dff19600-28dc-11eb-92f5-c80fb93706c4.png)

![image](https://user-images.githubusercontent.com/4943440/99393088-19c29c80-28dd-11eb-99ca-b38633e7d9d8.png)

![image](https://user-images.githubusercontent.com/4943440/99393185-41196980-28dd-11eb-8ac7-9258e87e4f5f.png)

~~~javascript

@Entity({ tableName: 'directory_contact' })
export class DirectoryContactEntity {
  @PrimaryKey()
  id!: integer

  @ManyToOne({
    onDelete: 'cascade',
    onUpdateIntegrity: 'cascade',
    wrappedReference: true
  })
  book!: Reference<DirectoryBookEntity> // , 'object' does not make any difference

  @Property({ columnType: 'citext' })
  title!: string

  @Property({ columnType: 'citext' })
  description!: string

}
~~~

~~~javascript

@Entity({ tableName: 'directory_book' })
export class DirectoryBookEntity {
  [PrimaryKeyType]: number
  [PrimaryKeyProp]: 'object' // object.id is the primary key
  @OneToOne({ primary: true, onUpdateIntegrity: 'cascade', onDelete: 'cascade', eager: true })
  object!: CoreObjectEntity

  @Property()
  username!: string | null
}

~~~

**Comment by B4nan** [comment] 2020-11-17 13:55
Understood, I guess I know whats happening.

**Comment by B4nan** [comment] 2020-11-18 13:27
You can try the fix via `4.3.1-dev.13`

**Comment by quinnturner** [comment] 2020-11-18 13:47
@B4nan I can confirm that `4.3.1-dev.13` fixed my reproduction of the identical issue.

**Comment by B4nan** [comment] 2020-11-18 13:49
Good, want to squash few more bugs but will aim to ship 4.3.1 today or tomorrow.

**Comment by ml1nk** [comment] 2020-11-18 15:58
Thanks for your work. At least my special case still has this issue.

~~~javascript
  // PbxLocationEntity
  @ManyToOne({ nullable: true, onDelete: 'SET NULL', onUpdateIntegrity: 'CASCADE' })
  sip!: IdentifiedReference<PbxSipEntity> | null
~~~
~~~javascript
  // PbxSipEntity
  [PrimaryKeyType]: number
  [PrimaryKeyProp]: 'object'
  @OneToOne({ primary: true, onUpdateIntegrity: 'cascade', onDelete: 'cascade', eager: true })
  object!: CoreObjectEntity
~~~
CoreObjectEntity contains a property id as primary key

version: 4.3.1-dev.13+cd46f62f42 
prop.type:
~~~javascript
'({ object?: CoreObjectEntity | undefined; } & import("/home/mlink/workspace/pitapi/node_modules/@mikro-orm/core/dist/index").Reference<PbxSipEntity>)'
~~~

Do you need more information?

**Comment by B4nan** [comment] 2020-11-18 16:01
Interesting, the parens are not expected by current regexp that parses the type. Thanks, will handle that too, no additional input is needed.

**Comment by B4nan** [comment] 2020-11-18 16:05
Btw as a workaround you can specify the type explicitly:

```ts
  @ManyToOne({ entity: () => PbxSipEntity, wrappedReference: true, nullable: true, onDelete: 'SET NULL', onUpdateIntegrity: 'CASCADE' })
  sip!: IdentifiedReference<PbxSipEntity> | null
```

Or this should also help:

```ts
  @ManyToOne({ type: 'IdentifiedReference<PbxSipEntity>', nullable: true, onDelete: 'SET NULL', onUpdateIntegrity: 'CASCADE' })
  sip!: IdentifiedReference<PbxSipEntity> | null
```

**Comment by ml1nk** [comment] 2020-11-18 16:18
I really appreciate your help and your suggestion is applied.

Working:
~~~javascript
  @ManyToOne({ entity: () => PbxSipEntity, wrappedReference: true, nullable: true, onDelete: 'SET NULL', onUpdateIntegrity: 'CASCADE' })
  sip!: IdentifiedReference<PbxSipEntity> | null
~~~

Not-Working:
~~~javascript
  @ManyToOne({ type: 'IdentifiedReference<PbxSipEntity>', nullable: true, onDelete: 'SET NULL', onUpdateIntegrity: 'CASCADE' })
  sip!: IdentifiedReference<PbxSipEntity> | null
~~~
prop.type is IdentifiedReference<PbxSipEntity> and no matching class name found.

**Comment by B4nan** [comment] 2020-11-19 10:39
Try `4.3.1-dev.18`

**Comment by ml1nk** [comment] 2020-11-19 11:21
Works like a charm :+1:

**Comment by ml1nk** [comment] 2020-11-19 16:58
Found another case:

In 4.3.1-dev.18:

~~~javascript
type:'{ node?: ({ id?: number | undefined; } & import("/home/mlink/workspace/pitapi/node_modules/@mikro-orm/core/dist/index").Reference<import("/home/mlink/workspace/pitapi/packages/core/dist/src/entity/CoreNodeEntity").CoreNodeEntity>) | undefined; } & import("/home/mlink/workspace/pitapi/node_modules/@mikro-orm/core/dist/index").Reference<CoreTenantEntity>'
~~~
=>
~~~javascript
type:'import'
~~~

Before regex:
![image](https://user-images.githubusercontent.com/4943440/99697492-13285680-2a90-11eb-9cb7-c5020fc336dc.png)
After regex:
![image](https://user-images.githubusercontent.com/4943440/99695879-5f729700-2a8e-11eb-8fcb-30cc830df045.png)


~~~javascript
export class CoreDomainEntity {
  @PrimaryKey()
  id!: integer

  @ManyToOne({ onUpdateIntegrity: 'cascade', onDelete: 'cascade' })
  tenant!: IdentifiedReference<CoreTenantEntity>
}

export abstract class CoreTenantEntity {
  [PrimaryKeyType]: number
  [PrimaryKeyProp]: 'node'
  @OneToOne({ onDelete: 'cascade', onUpdateIntegrity: 'cascade' })
  node!: IdentifiedReference<CoreNodeEntity>
}

export abstract class CoreNodeEntity {
  @PrimaryKey()
  id!: number
}
~~~

**Comment by B4nan** [comment] 2020-11-19 18:44
lol, ok :D

**Closed** 2020-11-20 20:49 UTC
Labels: bug
