### ISSUE TITLE
Array of embeddables property is not loaded from the database.

### ISSUE THREAD

**Issue by ps-aux** [mikro-orm/mikro-orm#2957] opened 2022-03-26 09:32 UTC
**Describe the bug**
[Array of embeddables](https://mikro-orm.io/docs/embeddables#array-of-embeddables) is not loaded

**To Reproduce**

#### Entities

```
@Entity()
export class AppUser {
    @PrimaryKey()
    id?: number

    @Property()
    name!: string

    @Embedded(() => Img, {
        array: true
    })
    images: Img[] = []
}
```

```
@Embeddable()
export class Img {
    @Property()
    url!: string
}
```

```
create table app_user
(
    id     serial primary key,
    name   text not null,
    images text
);


```

#### Test bootstrap

Simulates 2 different request contexts (2  REST endpoint invocations)

```
import { MikroORM } from '@mikro-orm/core'
import db from '../db.json'

import type { PostgreSqlDriver } from '@mikro-orm/postgresql'
import { AppUser } from './ad/User'
import { Img } from './ad/Img' // or any other driver package

const go = async () => {
    const orm = await MikroORM.init<PostgreSqlDriver>({
        entities: [AppUser, Img], // path to our JS entities (dist), relative to `baseDir`
        clientUrl: db.local.url,
        type: 'postgresql'
    })
    try {
        const em = orm.em.fork()

        let u = new AppUser()
        u.name = 'John Doe'
        u.images = [{ url: 'url 2' }, { url: 'url 2' }]
        await em.persist(u)
        await em.flush()
        u = await em.findOne(AppUser, { id: u.id })
        console.log('Before clear', u)
        em.clear()

        u = await em.findOne(AppUser, { id: u.id })
        console.log('After clear', u)
    } finally {
        await orm.close()
    }
}

go().catch(console.error)
```

#### Result

```
Before clear
AppUser {
  images: [ { url: 'url 2' }, { url: 'url 2' } ],
  name: 'John Doe',
  id: 14
}
After clear
AppUser { id: 14, name: 'John Doe', images: undefined }

```

**Expected behavior**
'Before clear` and `After clear` obects should be the same - `images` should not be undefined.

**Additional context**

When debugging, from the compiled code it seems that for some reason an array instance is expected but the instance type is string.

![image](https://user-images.githubusercontent.com/4789301/160233543-11cdad07-c4cf-4d62-b5bf-aafe810e98e0.png)

**Versions**
```
 "@mikro-orm/core": "^5.1.1",
 "@mikro-orm/postgresql": "^5.1.1",
 "pg": "^8.7.3",
```

| Dependency | Version |
| - | - |
| node | v16.8.0 |
| typescript | ts-node 10.0.0 |
| mikro-orm | 5.1.1|
| your-driver | pg  8.7.3 |

**Comment by B4nan** [comment] 2022-03-26 09:47
Please provide executable repro, there are tests exactly like this that are passing just fine, so its probably in something you havent shared.

**Comment by ps-aux** [comment] 2022-03-26 19:39
Could you please suggest a tool for providing executable example which supports node.js and docker? The only possibility I know of  as of now is having a dedicated Git repo.

**Comment by Langstra** [comment] 2022-03-27 08:11
You could clone this repo, write a failing test case and submit that as a PR?

**Comment by B4nan** [comment] 2022-03-27 09:01
You dont need any tools, just prepare a project that I can run myself fully, ideally as a test case or a script - no migrations, no web frameworks, no additional dependencies, no configuration layers, just the ORM code. If you can reproduce the same behaviour with sqlite, use sqlite in memory database, but of course it can be driver specific - something you should be ideally able to tell me upfront (exactly by testing it with other drivers like sqlite yourself).

General reproduction examples: https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues

Tests for embeddables: https://github.com/mikro-orm/mikro-orm/tree/master/tests/features/embeddables

Note that I see your reproduction is wrong, you assign an array of POJOs to the entity directly, while it should be array of instances of that embeddable:

```
// this is wrong
u.images = [{ url: 'url 2' }, { url: 'url 2' }]

// this is correct
const url1 = new Url(...);
const url2 = new Url(...);
u.images = [url1, url2]

// you can use `em.assign()` or `em.create()` to do it in a single step
em.assign(u, { images: [{ url: 'url 2' }, { url: 'url 2' }] }) // this will build the instances for you automatically
```

Definitely start by enabling debug mode and ensure the query that saves your entity is correct, and that the data in your database table actually have this array stored, as it can be also issue with saving, not loading.

**Comment by B4nan** [comment] 2022-03-27 09:13
> When debugging, from the compiled code it seems that for some reason an array instance is expected but the instance type is string.

It is the postgres driver (`node-postgres` dependency) that does the conversion automatically based on column type, so this might actually be a problem with your database schema. I see you provided the schema as SQL, and it is indeed also wrong, as you have a `text` column type instead of `jsonb` type. Change your column type to `jsonb` and it will get converted automatically. 

Closing, as the reason is your schema being out of sync/not correct, just confirmed this locally. Ideally you should use the provided schema generator instead of managing schema manually.

**Closed by B4nan** 2022-03-27 09:13 UTC
Labels: needs clarification
