### ISSUE TITLE
ManyToMany relation on other field than PK

### ISSUE THREAD

**Issue by Jeremyllanta** [mikro-orm/mikro-orm#2766] opened 2022-02-16 10:07 UTC
**Is your feature request related to a problem? Please describe.**

I have a ManyToMany relation with a pivot table but on one of the table, the relation isn't on the PK id. 
See example ERD :
![erd](https://user-images.githubusercontent.com/55086552/154239692-169e746a-5be4-43fb-82f8-a404597c43f1.png)
On `Authors` side, the relation is based on the PK `id` of `Authors` table.
On `Books` side, the relation is based on `another_id` column which is an unique id field.

The SQL generated is  
```
select * from authors 
left join authors_books on authors.id = authors_books.author_id
left join books on authors_books.another_id = books.id <---
```
Expected 
```
select  * from authors 
left join authors_books on authors.id = authors_books.author_id
left join books on authors_books.another_id = books.another_id <---
```
I can't find on the documentation how to change the field where the relation is made

**Describe the solution you'd like**

I would like to override the default PK id field on a ManyToMany relation.

**Comment by B4nan** [comment] 2022-02-16 10:08
This is a duplicate of #593 and partially also of #2757.

**Closed by B4nan** 2022-02-16 10:08 UTC
Labels: enhancement

**Comment by Jeremyllanta** [comment] 2022-02-16 11:01
Yeah I saw [#593](https://github.com/mikro-orm/mikro-orm/issues/593) but it didn't solve my issue

My Entities currently look like this :

```javascript
@ManyToMany({
    entity: () => Books,
    pivotTable: "authors_books",
    owner: true,
})
books = new Collection<Books>(this);
```

```javascript
@ManyToMany({
    entity: () => Authors,
    inversedBy: e => e.books,
    joinColumn: "author_id",
    referenceColumnName: "another_id",
} as any)
authors = new Collection<Authors>(this);
```

**Comment by B4nan** [comment] 2022-02-16 11:02
That issue is open for a reason, this is indeed not resolved and not possible anyhow.

**Comment by Jeremyllanta** [comment] 2022-02-16 13:14
Ok, thanks for your answers! Thought there was an alternative solution (like cast as any for a ManyToOne in [#593](https://github.com/mikro-orm/mikro-orm/issues/593)). I'll wait for the solution you mentioned :)
