### ISSUE TITLE
Serializing not working on collections when using BigIntType

### ISSUE THREAD

**Issue by jeroni** [mikro-orm/mikro-orm#1968] opened 2021-06-26 15:20 UTC
Serializing cycles on collections when using BigIntType on id's.

```
RangeError: Maximum call stack size exceeded
    at /home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/EntityTransformer.js:103:18
    at Array.map (<anonymous>)
    at Function.toObject (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/EntityTransformer.js:103:14)
    at Book.prototype.toJSON (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/EntityHelper.js:27:62)
    at WrappedEntity.toJSON (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/WrappedEntity.js:37:28)
    at /home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/ArrayCollection.js:36:62
    at Array.map (<anonymous>)
    at Collection.toArray (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/ArrayCollection.js:36:32)
    at Function.processCollection (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/EntityTransformer.js:178:24)
    at Function.processProperty (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/entity/EntityTransformer.js:148:38)

```

Example:
```ts
    @Entity()
    class Author {

        @PrimaryKey({type: BigIntType})
        id?: string;

        @Property()
        name!: string;

        @OneToMany({ entity: () => Book, mappedBy: (book: Book) => book.author, orphanRemoval: true})
        books: Collection<Book> = new Collection<Book>(this);

    }

    @Entity()
    class Book {

        @PrimaryKey({type: BigIntType})
        id?: string;

        @Property()
        name!: string;

        @ManyToOne({entity: () => Author})
        author!: Author;
    }

    const orm = await MikroORM.init({
        entities: [Author, Book],
        dbName: 'mikro-test',
        type: 'postgresql',
        // Connection fields omitted
        debug: true,
    });

    try {

        const em = orm.em

        const stephenKing = await em.findOne(
            Author,
            {name: 'Stephen King'},
            ['books']
        );

        console.log(JSON.stringify(stephenKing));

    } catch (e) {

        console.log(e);

    } finally {
        await orm.close();
    }

```

If BigIntType is removed from id's it works normally.

node 14.16.0
typescript 4.3.4
mikro-orm 4.5.6
postgresql

**Comment by B4nan** [comment] 2021-06-29 19:13
Seems to be already fixed in master, but I can reproduce it in `4.x` branch. I did cherry pick all the fixes that were easily portable, but it did not help, so it was most probably fixed as part of some v5 feature or refactoring. Closing (with a test case) as fixed in v5, you will need to wait for that (or use the dev version, there are not that much BCs, mostly internal things). 

Should be possible to get around issues like this via custom `toJSON` method or property serializers.

**Closed** 2021-06-29 19:13 UTC
