### ISSUE TITLE
date property with defaultRaw() throwing NotNullConstraintViolationException

### ISSUE THREAD

**Issue by devin-fee-ah** [mikro-orm/mikro-orm#719] opened 2020-08-08 18:49 UTC
**Describe the bug**
Consider two columns defined on a User entity, such as:
```ts
  @Property({
    columnType: "uuid",
    defaultRaw: "uuid_generate_v4()",
    primary: true,
  })
  id: string | undefined;

  @Index()
  @Property({
    columnType: "timestamptz",
    defaultRaw: "now()",
    // onCreate: (v: BaseEntity) => v.createdAt ?? new Date(),
    type: DateType,
  })
  createdAt: Date | undefined;
```

Notice that neither of those columns have `onCreate` specified, because we want to rely on the DB server to generate uuids and timestamps.

However, while `id` is not passed along when creating the model (if it has no value), `created_at` *is* passed along as `null` and this violates the not-null constraint on `created_at`. 

**Stack trace**
```
    NotNullConstraintViolationException: insert into "users" ("admin", "bio", "created_at", "deleted_at", "email_address", "first_name", "last_name", "password", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "id", "created_at", "updated_at", "admin" - null value in column "created_at" violates not-null constraint

      at PostgreSqlExceptionConverter.convertException (../../../common/temp/node_modules/.pnpm/@mikro-orm/postgresql@4.0.0-alpha.12_@mikro-orm+core@4.0.0-alpha.12/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:24:24)
      at PostgreSqlDriver.convertException (../../../common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-alpha.12_7d63d2278d9dca93dadae96a689026e9/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:144:54)
      at ../../../common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-alpha.12_7d63d2278d9dca93dadae96a689026e9/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:148:24
      at PostgreSqlDriver.nativeInsert (../../../common/temp/node_modules/.pnpm/@mikro-orm/knex@4.0.0-alpha.12_21b91daa455215dbf013fa34a9d70a3e/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:141:21)
      at ChangeSetPersister.persistEntity (../../../common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-alpha.12_7d63d2278d9dca93dadae96a689026e9/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:38:19)
      at ChangeSetPersister.persistToDatabase (../../../common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-alpha.12_7d63d2278d9dca93dadae96a689026e9/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:20:9)
      at UnitOfWork.commitChangeSet (../../../common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-alpha.12_7d63d2278d9dca93dadae96a689026e9/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:266:9)
      at UnitOfWork.persistToDatabase (../../../common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-alpha.12_7d63d2278d9dca93dadae96a689026e9/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:394:13)
      at UnitOfWork.commit (../../../common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-alpha.12_7d63d2278d9dca93dadae96a689026e9/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:144:13)
      previous error: insert into "users" ("admin", "bio", "created_at", "deleted_at", "email_address", "first_name", "last_name", "password", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "id", "created_at", "updated_at", "admin" - null value in column "created_at" violates not-null constraint
      at Parser.parseErrorMessage (../../../common/temp/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/parser.ts:357:11)
      at Parser.handlePacket (../../../common/temp/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/parser.ts:186:21)
      at Parser.parse (../../../common/temp/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/parser.ts:101:30)
      at Socket.<anonymous> (../../../common/temp/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/index.ts:7:48)
```

**Expected behavior**
Undefined and null should be treated differently. The column (when value is `undefined`) should be omitted from create / update statements.

**Additional context**
It's really odd that this impacts "timestamptz"s but not "uuid"s. I'm not sure if this is a `pg` driver problem or a library problem.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.3 |
| typescript | 3.9.7 |
| mikro-orm | 4.0.0-alpha.12 |
| your-driver | postgres |

**Comment by B4nan** [comment] 2020-08-09 05:58
> Undefined and null should be treated differently. The column (when value is undefined) should be omitted from create / update statements.

This is not about handling them differently, this is about you passing an actual value (let it be `null` or `undefined`), instead of not defining it all. The difference is in `{ foo: 1 }` vs `{ foo: 1, bar: undefined }` - swapping `undefined` with `null` won't make any difference, the problem is that you have that key defined. 

> However, while id is not passed along when creating the model (if it has no value), created_at is passed along as null and this violates the not-null constraint on created_at.

And that is your problem. Don't assign it as `null`.

**Closed by B4nan** 2020-08-09 05:58 UTC
Labels: wontfix

**Comment by devin-fee-ah** [comment] 2020-08-09 16:04
> This is not about handling them differently, this is about you passing an actual value (let it be null or undefined), instead of not defining it all.

My intuition says that [implicit `undefined`] === [explicit `undefined`] (semantically) but !== [`null`]. However, it turns out this isn't even a Mikro-ORM distinction.

[on PG documentation](https://node-postgres.com/features/queries)
[on PG issue tracker](https://github.com/brianc/node-postgres/issues/1274)

I guess I'll have to understand this as a known issue with PG.
