### ISSUE TITLE
@Check constraint breaks schema generator

### ISSUE THREAD

**Issue by surfous** [mikro-orm/mikro-orm#4505] opened 2023-07-06 19:46 UTC
**Describe the bug**
SchemaGenerator (CLI or called programmatically) fails on _subsequent_ runs when a check constraint is placed on a column.

**Stack trace**
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at replaceKeyBindings (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/formatter/rawFormatter.js:46:23)
    at Raw.toSQL (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/raw.js:79:13)
    at Raw.Target.toQuery (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/builder-interface-augmenter.js:9:21)
    at Raw.toString (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/raw.js:70:17)
    at /Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/schema/tablecompiler.js:381:35
    at Array.map (<anonymous>)
    at TableCompiler_PG._addChecks (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/schema/tablecompiler.js:378:12)
    at TableCompiler_PG.createQuery (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/dialects/postgres/schema/pg-tablecompiler.js:49:13)
    at TableCompiler_PG.create (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/schema/tablecompiler.js:59:10)
    at TableCompiler_PG.toSQL (/Users/surf/Developer/git/comfortai-consumer/targets/server/node_modules/knex/lib/schema/tablecompiler.js:42:22)
```

**To Reproduce**
1. Define property w/ check constraint: 
```  
@Property({ type: 'number', columnType: 'bigint', default: null, nullable: true })
@Check({ expression: columns => '"unsignedIntField" IS NULL OR ("unsignedIntField" >= 0 AND "unsignedIntField" <= 4294967295)' })
'unsignedIntField'?: number;
```
2. Run schema:fresh - first run succeeds
```
npx mikro-orm schema:fresh --run
```
3. Run schema:fresh again - this time it fails; repeated runs also fail
```
npx mikro-orm schema:fresh --run
```
4. Modify the check expression
```
@Property({ type: 'number', columnType: 'bigint', default: null, nullable: true })
@Check({ expression: columns => '"unsignedIntField" IS NULL OR ("unsignedIntField" >= 0 AND "unsignedIntField" <= 4294967295)' })
'unsignedIntField'?: number;
```
5. Run schema:fresh - succeeds again once
```
npx mikro-orm schema:fresh --run
```
6. Run schema:fresh again - back to failure mode; repeated runs also fail 
```
npx mikro-orm schema:fresh --run
```
7. Comment/remove the check expression
```
@Property({ type: 'number', columnType: 'bigint', default: null, nullable: true })
// @Check({ expression: columns => '"unsignedIntField" IS NULL OR ("unsignedIntField" >= 0 AND "unsignedIntField" <= 4294967295)' })
'unsignedIntField'?: number;
```
5. Run schema:fresh - back to success; repeated runs also succeed
```
npx mikro-orm schema:fresh --run
```

**Expected behavior**
Schema should drop/build successfully each time with the check constraints in place

**Additional context**
This feels similar to #4312 in behavior, but the stack trace is quite different. 

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.0 |
| typescript | 4.8.4 (also tried with 4.9.5) |
| mikro-orm | 5.7.12 |
| your-driver | postgresql |

**Comment by B4nan** [comment] 2023-07-15 11:24
I am not able to reproduce this, please provide a complete repro, ideally as a script (using schema generator programmatically). The stack trace is from creating the schema, so it needs to origin in the `createSchema()` call (as `fresh` command does `dropSchema` followed by `createSchema`).

**Comment by B4nan** [comment] 2023-07-21 08:00
Let's reopen with a failing repro, closing as not reproducible for now.

**Comment by kpervin** [comment] 2023-08-11 14:27
@B4nan I am also running into this issue with 5.7.12, but noticed that it only occurs when cache is present. I will attempt to create a failing repo, but hopefully this one tidbit helps steer in the right direction in the meantime.

I also did some debugging and noticed that it seems metadata is generated properly, but somewhere down the line when TableCompiler_MySQL.toSQL is called, the @Check expression function provided is undefined.

**Comment by kpervin** [comment] 2023-08-14 14:32
@B4nan I have a failing representation of the issue here:

https://github.com/kpervin/MikroORM-Issue-Example-Repo/tree/4505-Check-constraint-breaks-schema-generator

Run `test/schema-failing.spec.ts` to see the issue.

**Comment by B4nan** [comment] 2023-08-14 15:11
Thanks, got it reproduced, its indeed about the metadata cache.

**Closed** 2023-08-24 19:20 UTC
Labels: bug
