### ISSUE TITLE
Flush generates update on data that was not modified

### ISSUE THREAD

**Issue by YanDjin** [mikro-orm/mikro-orm#4115] opened 2023-03-10 19:42 UTC
**Describe the bug**
I have data structure modeled as below:
- An entity named Operation
- Each Operation has multiple OperationItem (OneToMany)
- Each OperationItem has one OperationItemData (OneToOne nullable)

When using a findOne on the operation, and then getting its items either using the init method or by using a find and passing the operationId as a parameter. The next flush will do a strange update on the OperationItemData table ??? and then, when loading the OperationItemData of each item after that, the ORM does not do a request, and uses only partially available data from the update it seems.

```ts
  async test() {
    const em = this.em.fork();
    try {
      // load the items
      const items = await em.find(OperationItem, {
        operation: 'e074c152-36c9-4677-9e1d-b85382b21217',
      });

      // this flush generates an update request for the OperationItemData model
      await em.flush();

      for (const item of items) {
        // load OperationItemData relation
        // this will not load all the needed data because of the update it seems
        const data = await item.data.load();
        console.log(data);
      }

      return true;
    } catch {
      await em.rollback();
      return false;
    }
  }
```
this code will generate the following logs, with the update before the commit and the partial data is logged after that
![image](https://user-images.githubusercontent.com/46947921/224412393-546e6810-1129-4a44-90c8-3995290ca2e9.png)

**To Reproduce**
1. clone the following repository https://github.com/YanDjin/micro-orm-bug-on-flush
2. run npm install
3. spin up the docker containers using the docker-compose file (spins up the postgres database and the nest application with the bug)
4. run the migrations (creates tables and adds the data needed)
5. launch a GET request to http://localhost:3000/test
6. the debug param is passed to nest.js, you should see the strange update request, and the partially loaded data is then logged

**Expected behavior**
Do not fire an update on flush, and load all the models data when using the `await model.relationRef.load()` method

**Additional context**
- Using Nest.js 8
- Tested multiple versions and the bug started with the version **5.6.10**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.16 |
| typescript | 4.8.4 |
| mikro-orm | 5.6.13 |
| your-driver | postgresql |

**Comment by B4nan** [comment] 2023-03-11 08:31
I'd like to see a _minimal_ reproduction if you think it is really an ORM bug - no web servers, [just a script](https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues), it should also create the data and assert the difference. I see you have a custom naming strategy, that's the first place I would focus on, try switching to one of the ORM-provided ones, and use schema generator to ensure your schema is really in sync with it. If it works, you know it's something in your naming strategy. Your implementation looks exactly like what the `EntityCaseNamingStrategy` already does.

Note that your code is an example of how to produce N+1, you should use `em.populate` outside of the for loop to load all the relations in a single query. Your code is also weird in the way that it calls `em.rollback` but never `em.begin` or `em.commit`, so I don't think it works like you want. There is no open transaction by the time it can reach the catch clause.

**Comment by YanDjin** [comment] 2023-03-11 16:10
Thanks for the reply. I followed your instructions and got rid of the web server, naming strategy..., I created a script, you can find it on the same repository url [here](https://github.com/YanDjin/micro-orm-bug-on-flush)
Thank you for the advices regarding the code, it was just a case I devised to showcase the bug, while getting rid of the logic I forgot the rollback, the loop is there just to show the load function does not generate a new request and just returns partial data (some fields are missing) and seems like the fields that are returned are those updated on flush because they are in the identity map I guessed.

**Comment by B4nan** [comment] 2023-03-11 17:01
Perfect, thank you! Will try to look into this soon, I don't see anything wrong there right now.

**Comment by B4nan** [comment] 2023-03-12 15:40
Looks like this is actually the same problem as #4121, resolved by https://github.com/mikro-orm/mikro-orm/commit/f2fa2bd5c30d70f511009a8cbc20966587be46c5

**Closed by B4nan** 2023-03-12 15:40 UTC
Labels: bug
